### ISSUE TITLE
Show community projects on github

### ISSUE THREAD

**Issue by Tomoli75** [pterodactyl/panel#1120]
Feature request (for github page):

Please show all community-built things, such as eggs and themes, and have links to them?

This makes it easier for new panel administrators to know "Hey, I like this." and install it.

**Comment by Daxorinator** [comment]
All of those are already listed in the discord server, there's an eggs channel and a themes repo in the server.

**Comment by lancepioch** [comment]
Thank you for your suggestion, just to let you know The Pterodactyl team is currently working on a site that will let people distribute and share Eggs they've made.
One of the ideas is to integrate it into the panel itself to make it even easier to download custom Eggs.
As for Themes, I don't think I've ever heard or seen anybody do anything beyond just modifying the base theme (it's hard work tbh).

Since the team has already been working on this, I'll be closing the issue. There will be a Discord announcement when it's complete and there is no current ETA, thank you.
