### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by dueckers5** [pterodactyl/panel#1131]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.7
* Server's OS: Ubuntu 166.04
* Your Computer's OS & Browser: Windows 10. Google Chrome. 

------------------------

So im trying to start some servers and all of them give an error like this

[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 8120M / 10000M
[Pterodactyl Daemon] Ensuring file permissions.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] Oh dear, it seems something has gone horribly wrong while attempting to boot this server. Please contact your administrator for assistance. PTDL:ERR_ID:bfMtaQ62nT8PWlMrdpNA
[Pterodactyl Daemon] An error was encountered while attempting to rebuild this container. Please contact your administrator for assistance. PTDL:ERR_ID:7q7LZcchplkjoyFDntun

**Comment by lancepioch** [comment]
We need the actual Daemon log file that has the errors and where they occurred in the code so that we can address this.

Try this command to retrieve them:

    cd /srv/daemon/ && npm run diagnostics

**Comment by parkervcp** [comment]
Please restart your daemon after importing an egg.

If this fixes the issue it is another reason #837 should be a thing.

**Comment by dueckers5** [comment]
https://hastebin.com/citanenize
that is the link to the log from /srv/daemon

**Comment by HexDevOfficial** [comment]
Correction.
It's from /drv1/daemon-data as we have a second harddrive

**Comment by HexDevOfficial** [comment]
Thanks for the quick response, I completely forgot that my server only connects to the private ip, which then gets bridged over to the public IP.

**Comment by PatricosTheFurry** [comment]
Help ME PLS server@idley~ Error Event [28ccb546-5f0e-47d4-8280-ffdb4733b304]: another power action is currently being processed for this server, please try again later

**Comment by Anezlyy** [comment]
i have this problem to:

[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Your server container needs to be rebuilt. This should only take a few seconds, but could take a few minutes. You do not need to do anything else while this occurs. Your server will automatically continue with startup once this process is completed.
[Pterodactyl Daemon] Server marked as STOPPING
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] Rebuilding server container...
[Pterodactyl Daemon] New container built, rotating hamsters...
[Pterodactyl Daemon] Container is being initialized...
[Pterodactyl Daemon] Completed rebuild process for server. Server is now booting.
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 39M / 25600M
[Pterodactyl Daemon] Ensuring correct ownership of files.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
:/home/container$ java -Xms128M -Xmx6144M -jar server.jar
Error: Invalid or corrupt jarfile server.jar
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon] Exit Code: 1
[Pterodactyl Daemon] Out of Memory: false
[Pterodactyl Daemon] Error Response:
[Pterodactyl Daemon] Server process detected as entering a crashed state; rebooting.
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 39M / 25600M
[Pterodactyl Daemon] Ensuring correct ownership of files.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
:/home/container$ java -Xms128M -Xmx6144M -jar server.jar
Error: Invalid or corrupt jarfile server.jar
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon] Exit Code: 1
[Pterodactyl Daemon] Out of Memory: false
[Pterodactyl Daemon] Error Response:
[Pterodactyl Daemon] Aborting automatic reboot due to crash within the last 60 seconds.
