### ISSUE TITLE
API: Enable functionality to specify a custom user ID when creating a user.

### ISSUE THREAD

**Issue by ryanbentley** [Pterodactyl/Panel#115]
It's better if my software can do a "lazy lookup" so to speak without having to query my own database for Ptero user IDs.

Example: In the current build, I would have to store the Ptero UID in my user database and each API call would then require me to perform a lookup first and then make the call.

In my suggested feature, I would just make a call and assume that the Petro UID == My User ID, and if things fail, we go from there.

It would be nice to be able to search user by e-mail or other attributes also instead of iterating over the list user call.

**Comment by schrej** [comment]
If you know the UID of the user in your application, why don't you know the Ptero UID then? Just have it always stored in the player object as well?
Afaik the UID is just using auto incrementing and that would break/work weird if you can specify the user id.
As email has to be unique (i think) that could be used to identify users instead of their UID in Ptero i think. At least i would like that better, the UID should be created by each system individually imho.

**Comment by DaneEveritt** [comment]
We talked about this on IRC a lot. Basically it is easier for some applications, especially those using Pterodactyl as a backend moreso than a frontend.

In this case he is looking at using the panel and daemon behind a custom panel that his users see. Its a relatively minor change to the API to make this possible, and also opens up SSO possibilities.

**Comment by ryanbentley** [comment]
@schrej If you could perhaps lookup a user by e-mail that would be handy.

**Comment by DaneEveritt** [comment]
Will add an API route to find users by given variables, e.g `/api/users?where=email&eq=<email>`
