### ISSUE TITLE
Get rid of usernames

### ISSUE THREAD

**Issue by Sergzy** [pterodactyl/panel#1196]
Usage of usernames in software like this panel does not really offer any benefit, since users are not able to communicate between each other.

The email is already used as login, so what's the purpose of the username? There's also First and Last name saved in the panel, which together with the email offers all the bewnefits needed (showing client's name instead of email for aesthetic purposes and email where user needs to provide identification).

The concept of usernames is needed in a software where anonymity is needed because users can interact with other users and the public (forums, GitHub, etc). Pterodactyl at no point offers any such functionality, therefore username does not offer any functional benefits, only additional code and possible complications.

**Comment by JaydenDownes** [comment]
Username are shorter and much easier to use at login. They also provide a means for a native or foreign key in the databases, although I don't think Pterodactyl uses them for this. They also are responsible for the user's picture from the Gravatar site and are all around nicer to use. I really don't think they use any resources at all and if you want to remove the code for usernames to make the code simpler to read and use fewer resources then go for it but they are a standard for any login application. Hosting providers may also wish that staff use usernames instead of emails when going to their support due to the shorter length and the client generally preferring it as emails are sometimes seen as confidential information. Also, you mentioned that they are not needed for anonymity as there are no chat applications built into pterodactyl where a regular user would need to simply put in a friends account but this is actually seen when creating a server or adding users to an existing server.

**Comment by schrej** [comment]
The usernames were introduced to make logging in easier (if you have a long email address for example).
We're not using them as keys and they also don't provide the Gravatar profile pictures (that's the email).

Imo we should add settings that allow to switch between using full names and usernames, still keeping the usernames for login in any case though.

**Comment by Sergzy** [comment]
@JaydenDownes as @schrej pointed out, usernames are currently only used on login and nowhere else (Even in panel itself the name is displayed, not username;).


Instead of keeping usernames around, the login form should remember last entered email (as for example Paypal does) and it would be much more elegant way to solve this concern. Having the username thing is nothing, but confusing since they are not used for anything else than having "easy login" thing.

**Comment by DaneEveritt** [comment]
Whats your plan for logging into SFTP?

**Comment by Sergzy** [comment]
SFTP username would then be {UserID}.{ShortUUID} (e.g. 15.ab5sd53) or something alike.

I guess it's not worth taking time to take it all out now then.

**Comment by schrej** [comment]
We should make using full names optional though and allow switching between full names and usernames maybe. Also display the username if there is no full name.
Might be nice for gaming communities where people generally use usernames instead of real names.

**Comment by DaneEveritt** [comment]
Thats just overly complex for no gain. It is also a major BC break for anyone reliant on usernames already in custom code, as well as everyone using SFTP.
