### ISSUE TITLE
2FA Manual Code Nonexistent.

### ISSUE THREAD

**Issue by JaydenDownes** [pterodactyl/panel#1197]
* Panel or Daemon: Panel
* Version of Panel/Daemon:  0.7.6
* Your Computer's OS & Browser:  Chrome & Firefox

**Describe the bug**
The panel describes when setting up 2FA to " take a picture of the QR code to the left, or manually enter the code under it". It seems that the 2FA backup code instead of the image isn't integrated into the panel.

**To Reproduce**
1. Head over to {Panel-URL}/account/security
2. Click Enable 2-Factor Authentication.
![screencapture-test01-vectra-space-account-security-2018-06-12-20_59_13](https://user-images.githubusercontent.com/35357527/41292211-7af4c868-6e84-11e8-8154-3eca1a78c40f.png)

**Comment by DaneEveritt** [comment]
I mean its a bug, but I'm also actively rewriting that entire section with the VueJS changes so its not going to be fixed before I roll out those changes.

I'm going to close this since it is difficult to track a bug fix like this when the feature is being completely changed. Just know that it will be addressed 👍

**Comment by DaneEveritt** [comment]
Actually, that was kinda pointless, I'll keep it open and close it when the new 2FA changes roll.

**Comment by DaneEveritt** [comment]
closed in https://github.com/pterodactyl/panel/commit/7711b697ada423893d5c26e2e9b051f6ea787674
