### ISSUE TITLE
Default to NoIndex in documentation

### ISSUE THREAD

**Issue by n-valverde** [pterodactyl/panel#1208]
Hi guys,
Could you please consider updating documentation about webserver config to include NoIndex / NoFollow ? It looks like everyone is following the docs without any knowledge of what they're doing, ending with tons of search results on Google "Index of Pterodactyl/app/..........."
I know it's not really your concern, but it makes researches about your project a lot harder ! Try to Google "pterodactyl app console commands".

**Describe the solution you'd like**
Just update the apache/nginx config section of doc with NoIndex

**Describe alternatives you've considered**
At least advise user in doc that they should consider improving webserver default config.

**Additional context**
See yourself, and this is just page one, same results till page 3 : 

![image](https://user-images.githubusercontent.com/39206748/41717816-48770260-755b-11e8-8c3e-781c8f9e1486.png)

![image](https://user-images.githubusercontent.com/39206748/41717876-6dcdaa0a-755b-11e8-8966-270abc02f684.png)

**Comment by lancepioch** [comment]
https://docs.pterodactyl.io/docs/webserver-configuration

The red colored section at the top. Truth be told this application is not meant to be set up by people with no experience. Along with this way, there are a thousand other ways that somebody can mess their app up (usually in worse ways). Since Pterodactyl is OSS, this isn't as big of a deal.

![image](https://user-images.githubusercontent.com/1296882/41719781-0f9123da-752f-11e8-9576-ed8f9ff4c21d.png)

Anyways, the whole docs are being rewritten: https://github.com/pterodactyl/documentation

Feel free to suggest the edits anyways on docs.pterodactyl.io

**Comment by schrej** [comment]
We also changed the docs so the suggested installation path is outside of the default document root to reduce accidental exposition
