### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by gzzchh** [pterodactyl/panel#1242]
A Plugins System for developers to add feature to the panel by writing plugins. Sometimes I want to add some custom features to the panel, but they will lose in the update.Also I can't assess compatibility for the future versions.
If there will be a Plugin System.Every people can write their plugins to enhance the panel. That will be cool.
English is not my native language,I am using Google Translate.

**Comment by DaneEveritt** [comment]
Yeah, going to close this out. As much as I'd love to see a plugin system like this I do not believe I would be able to properly build out and maintain it given the limited resources we currently have available and the complexity of the underlying system.

Maybe one day down the road we will have a better events driven system to allow you to easily hook into common actions (so a pseudo-plugin system), but thats quite far down the road.

Right now the best way to handle custom modifications is to fork Pterodactyl and just track your changes in a remote branch, merging our releases/develop/master builds into yours as you see fit. Its not as easy as just using a plugin system, but it does work, and gives you the flexibility you need right now without hacking bad plugin implementations on top.

**Comment by patchbank** [comment]
Hello @DaneEveritt !

I really appreciate your honest statement.

Since it is now almost two years ago that you've posted this, I would like to ask if anything has changed. Unfortunately Pterodactyl is a software mainly used by people who just want a working software, so there are not a lot of contributors. Actually, you're mostly the only one in this project.

A plugin system is a lot of work, I understand that. Would you agree to the implementation of a plugin system if someone helps you like laying the foundation for it which we can build upon together? I personally see a lot of potential in a plugin system like it was mentioned before, as it allows private people and hosting companies to extend the panel properly. There are some "plugins" out there. Actually they're just dirty hacky things overwriting original Pterodactyl files.

To get some air out of it: It doesn't have to be a huge thing on it's first release. How about designing and developing it in little steps?
For example:
- Adding Pages / Categories to the menu & loading static templates
- Supporting Controllers for more dynamic custom pages
- Allow to listen a small set of events (start, stop, crash for example)
- A basic interface to be able to handle a server (start, stop ...)

That's just a very poor sketch to visualize what I mean. I recently worked on a customers project who needed a similar thing in his Laravel/VueJS web application, so I might be able to help here and there, if I find some time for it.

What do you think about it?

Best wishes & stay healthy!

**Comment by DaneEveritt** [comment]
@patchbank I'm open to PRs implementing basic plugin functionality, especially if it helps people write some more composer-esq plugins that don't just blindly overwrite files.

We would need to get a bit creative on the frontend since its a pre-compiled React frontend right now, so templates trying to expand upon that could be interesting. I think the codebase is mostly stable now (although theres still a fair amount of code cleanup I need to complete), so building in a basic plugin system shouldn't be too hard.

Feel free to hit me up in Discord if you want to go back and forth in more real-time about this when I have a bit more time during the week. :)
