### ISSUE TITLE
Swap Usage Monitor

### ISSUE THREAD

**Issue by Dovahkiin-Warrior** [pterodactyl/panel#1259]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just something I'd like to see on the panel so I know what's there.

**Describe the solution you'd like**
I'd like to be able to see the swap memory usage of an installed server. Physical memory usage is there yes, so is CPU, but I'd also like to see the virtual memory usage (disk swap). I feel that because we can control the amount of swap used by a server that it would also be extremely helpful to see the swap usage in real time.

**Describe alternatives you've considered**
Webmin shows the swap usage in the process manager, but it's really annoying to go in there and retrieve a bland number that is showing total swap.

**Additional context**
Nothing really. Like I say, if we can see the swap usage by individual servers that would be really beneficial to anyone who uses pterodactyl.

**Comment by DaneEveritt** [comment]
This isn't something returned easily by docker, so I'm not going to be adding this in anytime soon.

**Comment by MrRinkana** [comment]
Could one not use docker inspect and top?
like for [example](https://forums.docker.com/t/how-to-see-container-swap-memory/88380/4):
```
foo@lab-01:~$ docker inspect -f '{{.State.Pid}}' <CONTAINER ID>  #use this to find the PID of the container on the host

foo@lab-01:~$ top -p <Returned PID above>
```

Since swap-space can be configured per server, not seeing its usage is a bug: it becomes very hard to know if excessive swap has been given (or too little) as well as checking whether the swap is being used (if one added it as a safeguard and expects it not to be used)..
