### ISSUE TITLE
Scheduled task manually launched run 2 times

### ISSUE THREAD

**Issue by Kperroch** [pterodactyl/panel#1288]
**Background (please complete the following information):**
* Panel or Daemon: Panel or Daemon
* Version of Panel/Daemon: Latest
* Server's OS: Debian 9
* Your Computer's OS & Browser: Windows 10 / Opera

**Describe the bug**
When a schedule task is manually lauched from the pannel it start task 2 times (they can run at the same time or one after the other)

**To Reproduce**
1. Create a shedule with steps
2. launch it manually
3. the commands are executed 2 times

**Expected behavior**
I expect that the task run only one time

**Comment by DaneEveritt** [comment]
This is the most frustrating bug I think I've ever encountered with this panel.

**Comment by DaneEveritt** [comment]
Found a few things here:

1.) Remember to completely remove your old development environment before debugging scheduled tasks. I spent 8 hours trying to figure out where random tasks were being called from only to discover I had a separate instance of Pterodactyl sharing the DB.

2.) When tasks were manually triggered they'd set the next_run_at time to the current time, which was kind of smart, but ultimately pointless because a.) it is incorrect technically and b.) it was never set to the correct next run time at the end.

3.) The query to get schedules to run failed ignored schedules that were actively being processed.
