### ISSUE TITLE
Panel allows assignment of new server with in-use port

### ISSUE THREAD

**Issue by xyeLz** [pterodactyl/panel#1301]
I have an existing server named Server1 which is assigned ports 1111, 1112, and 1113. It no longer needs ports 1112 and 1113 so I remove them from the allocation. I forget to reboot the server. Thus, the Docker container never restarts and the ports technically aren't free, even though to the panel they are.

I create a new server named Server2 and attempt to assign them these ports. It assigns successfully but when the server attempts to boot, it states that something has gone horribly wrong.

**Comment by DaneEveritt** [comment]
Theres not really a good way to solve this issue because it is handled at the docker level. I mean theoretically we could wait for an API call from the Daemon telling the Panel that the ports are free, but then you risk communication errors and ports that get stuck in limbo, plus another API endpoint to support.

This seems like a pretty rare issue to occur, I'm not aware of servers having ports unassigned and then reassigned frequently while still running. Most cases are just adding ports to existing servers.

**Comment by xyeLz** [comment]
Definitely more mentioning this as a bug than anything else. I honestly agree with your assessment of the issue. I just brought it up since I noticed it and thought it should be fixed, but I ultimately defer to you and your best judgment. At the very least, and if possible (if you don't plan to fix it), maybe change the error output when a new server is deployed so that it's not so generic. If I didn't remember what I was doing I would have been thoroughly confused as to why I was unable to deploy a new server.

**Comment by DaneEveritt** [comment]
It should have shown up in the daemon error logs, this really just comes down to showing more information to admins when servers fail to install I guess.

**Comment by xyeLz** [comment]
Absolutely.

I know how much you love being spammed on Discord why X or Y isn't working. Might just make your lives easier in the long run with a little bit more effort in the short-term to display more logging within the console. Like I said though, I defer to you! Just wanted to report it.

**Comment by DaneEveritt** [comment]
I'm going to close this issue since it is specifically focused at something I don't plan on changing. We have an open issue somewhere about showing more error details, and if not it is at the top of my personal list to do.
