### ISSUE TITLE
404 When changing server owner

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#1379]
**Background (please complete the following information):**
* Panel or Daemon: 
* Version of Panel/Daemon: 0.7.11
* Server's OS: Ubuntu 18
* Your Computer's OS & Browser: Win10 / Chrome

**Describe the bug**
Panel: PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Attempting to change the server owner throws a 404 Error

**To Reproduce**
Steps to reproduce the behaviour:
1. Select a server
2. Proceed to the admin side of the selected server
3. Attempt to change the `Server Owner` to another user
4. Clicking Update Details -> Returns 404
**Expected behavior**
I think its obvious?

**Comment by Bl4ckSpr4y** [comment]
@Sir3lit I can't reproduce, https://i.imgur.com/z2oVOJ7.gif

**Comment by Sir3lit** [comment]
Hmm, Seems to magically fixed itself... Very weird.

**Comment by Sir3lit** [comment]
Other users are reporting this same issue, mine has seems to resolved itself,

https://discordapp.com/channels/122900397965705216/404106122127998977/513288440909922324

**Comment by MelcomX** [comment]
I have the same error.

Background (please complete the following information):

Panel or Daemon:
Version of Panel/Daemon: 0.7.11/0.6.8
Server's OS: Ubuntu 16.04
Your Computer's OS & Browser: Win10 / Chrome & Win10 / Edge
Describe the bug
Panel: PHP 7.2.11-3+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Oct 25 2018 06:43:25) (NTS )
Attempting to change the server owner throws a 404 Error

To Reproduce
Steps to reproduce the behaviour:

Select a server
Proceed to the admin side of the selected server
Attempt to change the Server Owner to another user
Clicking Update Details -> Returns 404
Expected behavior
I think its obvious?

**Comment by DaneEveritt** [comment]
I can't reproduce this.

**Comment by kieransouth** [comment]
I'm having this issue now.

Went into debug mode and changed environment to local but no error appeared in my logs.

Changed server owner and clicked update details and returns a 404.

**Comment by TrixterTheTux** [comment]
To add on top of ^, error log with all error reporting enabled: https://bin.ptdl.co/sf7e5/
So by the looks of it, this will happen always when the daemon key doesn't exist (so the owner hasn't opened the server in a while), throwing a 404 due to the daemon key not being found.

**Comment by marrobHD** [comment]
How can I fix this without loggin in to the account?
