### ISSUE TITLE
Treat white space in terminal output as preformatted (cont)

### ISSUE THREAD

**Issue by jcsnider** [pterodactyl/panel#1394]
This PR (#1238) was merged back in July to treat white space in the terminal output as preformatted. That PR also has media showing why I suggested the change.  It looks like on Sept. 15th that commit was reverted by @ayan4m1 in 955617d.

I'm guessing the css change broke other text in some way/shape/form, but I couldn't find any issues/mentions of either commit.  I was hoping I could figure out what went wrong, and potentially help find another solution.

**Comment by fabm3n** [comment]
Have you any example? Or is it just a thought.

**Comment by Sir3lit** [comment]
It was removed because with minecraft it added an extra line after every console line.

https://justmyrandomstuff.com/img/KgcGy7l.png -> With white-space: pre;
https://justmyrandomstuff.com/img/POh72xm.png -> Without white-space: pre;

If it's that big of an issue, you can edit the file on your end.

**Comment by jcsnider** [comment]
That's unfortunate but makes sense, Minecraft is not a game I am actively running on my end. Thanks guys for the quick responses! Going to close this for now and deal with it locally.
