### ISSUE TITLE
Error 500 with no logs

### ISSUE THREAD

**Issue by LewaIngame** [pterodactyl/panel#1475]
hello everyone i have an error 500 with my pterodactyl and a white page with no logs plz help

**Comment by matthewpi** [comment]
If Pterodactyl was returning a 500 error there would be content on the page.  Most likey you didn't configure your webserver properly.

Please ask for assistance in the Discord instead of opening a new issue.

**Comment by LewaIngame** [comment]
i am banned from the discord 👎 
and i have reinstalled the pterodactyl 2

**Comment by Lunaversitay** [comment]
Error 500 just means there's a fatal error with the panel. Most likely misconfiguration of the panel itself.

If you're **not** on production you can go to your .env and turn debug to true and put production to local and it'll give you a detailed reason why its erroring.

If you're on production make sure to check the /storage/logs folder for error logs. (If there are no error logs, its probably because Laravel doesn't have permission to create them, which would cause an error 500)

**Comment by LewaIngame** [comment]
i have chown -R www-data:www-data * and no logs

**Comment by LewaIngame** [comment]
i have found that [2019-02-10 20:48:10] production.NOTICE: A query exception was encountered while trying to load settings from the database: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'panel.settings' doesn't exist (SQL: select * from `settings`)

**Comment by Lunaversitay** [comment]
You didn't migrate the tables properly.

**Comment by schrej** [comment]
If you are banned from Discord it's your own fault. This issue tracker is for bugs and features, and not for support.
