### ISSUE TITLE
Allow pterodactyl to generate stronger passwords for mysql

### ISSUE THREAD

**Issue by weeryan17** [pterodactyl/panel#1508]
**Is your feature request related to a problem? Please describe.**
pterodactyl currently when it generates a password for a database user it doesn't generate a strong enough password so if mysql password policy level is at medium or higher the panel will error.

**Describe the solution you'd like**
pterodactyl should generate stronger mysql passwords to work for any password policy level.

**Describe alternatives you've considered**
You could read the password policy level from mysql and generate passwords based off of that, or you could have the panel automatically lower the password policy level.

**Comment by MatthewSH** [comment]
Looking at the policy and running the function over 100 times it looks pretty consistent in what it throws back.

The only rule it's violating really is the special character rule because of the way it works. So...here's the policies as of MySQL 8.0 (pulled from the reference docs) with if the current system satisfies it or not (Pass / Fail)

Low:
- Must be at least 8 characters long (Pass)

Medium:
*All of the above and...*
- Must have at least 1 numeric character (Pass)
- Must have at least 1 uppercase and 1 lowercase character (Pass)
- Must have at least 1 special character (Fail)

High:
*All of the above and...*
- substrings of 4 and longer must not match any word in a dictionary file (Pass, but in theory could fail because random bytes but I highly doubt this could ever fail...but you never know)

What we could do is throw in some random special characters (like @, +, =, and !) in the password randomly spread with a random amount between 1-6 or something. Would increase the password length to 25-30 characters long...so it should be good or we can rewrite the random string function to account for a random set of special characters while keeping the length of 24 or we could just subtract 1-6 letters from the generated output and replace them with special characters. Either way, that should satisfy all three levels.
