### ISSUE TITLE
Add multiplicators to Storage/RAM related input fields

### ISSUE THREAD

**Issue by schrej** [Pterodactyl/Panel#154]
## Product

Please check the corresponding boxes below for which products this is about.
- [x] Panel
- [ ] Daemon
- [ ] Dockerfile(s) [Please list if so: __ ]
## Type
- [ ] Bug or Issue
- [ ] Feature Request
- [x] Enhancement
- [ ] Other

Storage and RAM fields should allow multiplicators for easier values. We would only need G (Gigabytes) and T (Terabytes) i think.
You could then enter `2G` instead of `2048`. This is especially useful for larger amounts like 70Gb of Storage which would be 71680 Mb but who wants to pull out a calculator every time?

Also the output should use those as well i'd propose.

**Comment by Taronyuu** [comment]
It is only a small change but I really think it comes in handy so I decided to create a small snippet.

```javascript
    $("input[type='text']").on('change', function(){
        var value = $(this).val(); //Store value for ease of use
        
        var isOnlyNumbers = /^\d+$/.test(value); //Test if there are non numeric characters
        if(!isOnlyNumbers){
            var multiplicator = value.replace(/[0-9]/g, '').toLowerCase(); //Store the multiplication for ease of use
            value = value.replace(/\D/g, ''); //Remove all non numeric characters
            if(multiplicator == 't'){
                //Terabyte
                var multiplication = 1048576;
                value = value*multiplication;
            }else if(multiplicator == 'g'){
                //Gigabyte
                var multiplication = 1024;
                value = value*multiplication;
            }
        }
        
        $(this).val(value);
    });
```

Obviously it should listen to a separate class and might be expanded with more multiplicators. The reason I chose to use Javascript is because we are able to show the actual amount of MB's back to the user before submitting the form.

**Comment by DaneEveritt** [comment]
@Taronyuu — it appears that JS is just taking a user input like `12g` and converting it to MB and then replacing the field value?

**Comment by Taronyuu** [comment]
Yes it is, I think this is more user friendly to immediately update the value than parsing it later on using PHP. 

More so because the user isn't able to 'check' their given amount of MB's before submitting, and if anything fails while parsing it the user is required to fill in all the select menu's again. (Because those are not prefilled when returning the user)

**Comment by DaneEveritt** [comment]
Yeah, the select menu's is currently just a flaw in my setup (although it'd be possible to fix, just not a priority).

I'll go ahead and work in that code in a bit.
