### ISSUE TITLE
Pterodactyl not support creating and using servers in username space docker mode

### ISSUE THREAD

**Issue by Elrondo46** [pterodactyl/panel#1540]
The daemon and node runs correctly but server can't be created with username space mode, in docker pure (and this is unsafe), pterodactyl runs flawlessly

**Comment by DaneEveritt** [comment]
There are specific design and implementation reasons for this. As a team we feel very comfortable with the current security measures implemented in the daemon. If you feel we are not doing enough you are welcome to open an issue with specific details and examples of what would be mitigated. If you have a real world example of an attack against the daemon you're welcome to email me directly (`dane@[website].io`) and let me know more about it.

However, based on what I saw in our Discord server, you're simply making broad statements believing that the entire daemon is vulnerable simply because we're not using namespace remapping in containers, ignoring the numerous other security measures that have been employed.

**Comment by CruzeiroKZ** [comment]
The concern is that for someone very comfortable with system administration, already having a secure docker in username space, installing the daemon is impossible. It would only be good, to bring this compatibility. I would like to specify that if docker is in root mode, in case of a docker failure, you can go up to the host and be in root mode. For people having a docker already configured in username space, it would force the uninstallation of the latter in favor of an unsecured docker in order to support your application which is not tolerable.

**Comment by CruzeiroKZ** [comment]
Finally, docker recommends the implementation of a docker in username space : https://docs.docker.com/engine/security/userns-remap/

"The best way to prevent privilege-escalation attacks from within a container is to configure your container's applications to run as unprivileged users. For containers whose processes must run as the root user within the container, you can re-map this user to a less-privileged user on the Docker host."

It's worth mentioning that this is the best way, and almost all applications running in docker have adopted it, so if pterodactyl did it, the user using docker in username space would find compatibility, and obviously security as well recommended by docker, the user with multiple applications on a secure docker could be disgusted with pterodactyl since it wouldn't work and they would have to rebuild their infrastructure by downgrading the security to install pterodactyl. What's a pity is that pterodactyl is still a very good application, very complete, but there is this big black spot that could be fixed.

**Comment by parkervcp** [comment]
We already do that in the container. They run internally as an un-priviledged "container" user.

**Comment by CruzeiroKZ** [comment]
if we could actually install it on a docker in username space, we wouldn't get this kind of permission error.

21:18:39.788Z  INFO wings: Checking if we need to update image quay.io/pterodactyl/core:java, if so it will happen now.
21:18:41.217Z  INFO wings: Pulling image quay.io/pterodactyl/core:java ... this could take a few minutes.
21:18:51.219Z  INFO wings: Pulling image quay.io/pterodactyl/core:java ... this could take a few minutes.
21:18:53.948Z  WARN wings: Server booting is now BLOCKED. (server=9bbd0dc8-73d0-4030-a70d-e0e0fb43162e)
21:18:53.950Z  INFO wings: Blocking server boot until option installation process is completed. (server=9bbd0dc8-73d0-4030-a70d-e0e0fb43162e)
21:18:54.361Z  INFO wings: Writing output of installation process to file. (server=9bbd0dc8-73d0-4030-a70d-e0e0fb43162e)
    file: /srv/daemon/config/servers/9bbd0dc8-73d0-4030-a70d-e0e0fb43162e/install.log
21:18:55.633Z  INFO wings: Pulling image alpine:3.9 ... this could take a few minutes.
21:18:56.966Z  INFO wings: Temporarily suspending server to avoid mishaps... (server=9bbd0dc8-73d0-4030-a70d-e0e0fb43162e)
21:18:56.972Z  WARN wings: Server has been suspended. (server=9bbd0dc8-73d0-4030-a70d-e0e0fb43162e)
21:18:56.978Z FATAL wings: Cannot read property 'StatusCode' of null (path=/v1/servers, method=POST, server=9bbd0dc8-73d0-4030-a70d-e0e0fb43162e)   
    TypeError: Cannot read property 'StatusCode' of null
        at DockerController.run (/srv/daemon/src/controllers/option.js:168:30)
        at handler (/srv/daemon/node_modules/dockerode/lib/docker.js:1379:21)
        at /srv/daemon/node_modules/dockerode/lib/docker.js:73:23
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:262:7
        at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:284:7)
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:253:5)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)
        at IncomingMessage.emit (events.js:203:15)
        at IncomingMessage.EventEmitter.emit (domain.js:466:23)
        at endReadableNT (_stream_readable.js:1145:12)

**Comment by CruzeiroKZ** [comment]
and I'm definitely kvm

**Comment by CruzeiroKZ** [comment]
if it went root obviously it would work.....

**Comment by CruzeiroKZ** [comment]
![Capture du 2020-03-12 22-33-19](https://user-images.githubusercontent.com/62106938/76568648-916c3c00-64b1-11ea-8a6b-2951f332d1aa.png)

So that means we're redoing our dockworker with all the privates, which isn't normal.

**Comment by CruzeiroKZ** [comment]
I would like to point out that portainer, which is a very complex system, can be used in username space, so pterodactyl is necessarily capable of

**Comment by DaneEveritt** [comment]
I do not have the time or resources to completely rewrite the underlying logic of the daemon to support this type of functionality right now. I stand by the design decisions we made when the product was being built 5 years ago, and prioritizing my time to support namespaces like this would only put other project work even further behind.

Sorry, but I won't be making any changes at this time.

**Comment by CruzeiroKZ** [comment]
...
If someone wanted to contribute by sending you a new modified daemon for this, would you accept it?

**Comment by CruzeiroKZ** [comment]
Personally I would have taken advantage of the development of the future major version to develop this. But that's your choice.

**Comment by DaneEveritt** [comment]
If you're able to provide a working change in the wings repo, I will look into merging that in. It won't ever happen for this Nodejs version though.

**Comment by CruzeiroKZ** [comment]
However, with the peertube software used by nodejs version 10, the username space is possible.

**Comment by CruzeiroKZ** [comment]
and I would like to point out that if you look at my error above, you would see that the node is functional in username space but the minecraft server doesn't want to start. It's more of a permission issue that I think could be fixed.

**Comment by DaneEveritt** [comment]
I believe the permissions errors generally stem from the mount bindings, especially given file modification is happening outside the container, so it needs to be able to remap into the container correctly.

**Comment by CruzeiroKZ** [comment]
In that case, it should be easy to correct it ^^
