### ISSUE TITLE
Admin Settings Mail - No Scroll/Swipe

### ISSUE THREAD

**Issue by MatthewSH** [pterodactyl/panel#1591]
Thanks to StrechedResPlayer#0001 on Pterodactyl Discord. I noticed this. This does affect 0.7/0.7-develop.

When browsing the admin settings, when you're on a mobile phone or small windows you have scroll bars on advanced, but when you get mail you don't have the option...even though it's overflow exists.

Now technical reasons for why this happens, haven't looked to in depth. Noticed some inconsistencies with elements changing and attributes being set on page load on advanced and general while not being set on mail. Then I noticed, not all the same scripts were loading.

Not gonna go into Laravel details, I assume we all have a basic understanding. [Here](https://github.com/pterodactyl/panel/blob/0.7-develop/resources/themes/pterodactyl/admin/settings/mail.blade.php#L113) is overriding the [parent layout](https://github.com/pterodactyl/panel/blob/0.7-develop/resources/themes/pterodactyl/layouts/admin.blade.php#L175) and there's no reference to `@parent` at all.

I'm curious if this is intended functionality or not. Simple solution would just be to add `@parent` at the top and then remove the second calls to the scripts and all parent scripts would load like normal fixing this issue. 

It looks like the scripts section was added by @ayan4m1 at c5608b182708ca5544dd74ea73a4f03382d6d751.

If there's no objection to fixing this glitch, I can PR a fix in tomorrow into the 0.7-develop branch

**Comment by ayan4m1** [comment]
The commit you linked to doesn't add or change any `<script>` tags, I think you're looking for [this commit](https://github.com/pterodactyl/panel/commit/c5608b182708ca5544dd74ea73a4f03382d6d751#diff-247274d1206780c43fb36b5582c0f559R113), but in any event the reason they are different is that at the time I did not see a reason to load all of those scripts for what was necessary to make the mail test page viable. If one or more of those JS files is causing a UI issue related to overflow on mobile devices - to me that's a distinct issue to be resolved regardless of whether or not `@parent` is used in that section.

Can you provide some detailed reproduction information? What steps do I take to make the issue occur in my browser / on my mobile device? What browser / mobile device? In particular, I'm having a hard time understanding

> when you're on a mobile phone or small windows you have scroll bars on advanced, but when you get mail you don't have the option...even though it's overflow exists

What JS resource do you think is modifying the CSS on the page such this issue would occur? We should figure out what specific resource is required to resolve the issue - if all of them are, so be it, but I'd prefer to add one file instead of ten if that's all that is necessary, and I don't see offhand how adding a bunch of JS to the page is likely to fix an issue with content overflowing.

**Comment by MatthewSH** [comment]
Sorry for my delay in response. It has to do with AdminLTE's setup with it's layout [reference here](https://github.com/ColorlibHQ/AdminLTE/blob/master/build/js/Layout.js#L44). 

I don't see much change in loadtime when just referencing parent in general, especially cause it caches everything. All the other settings pages have all references and they load just fine. I think in general, since everything is minified and cached...it's probably better to reference parent. I have a hotfix branch I'll PR into 0.7-develop in a moment.

On the technical reason why, I honestly don't know. I've never personally had to do something like AdminLTE is doing. I'm not gonna complain too much about it...just gonna PR a fix.

As for reproduction, since Bootstrap and such uses device size to structure everything...just make it to where you'd have to scroll and you'll see that because of the way some of the CSS classes define elements on the page it restricts it from scrolling. The aforementioned script in AdminLTE fixes that.
