### ISSUE TITLE
Admin index server list should use more descriptive status tags

### ISSUE THREAD

**Issue by AusHick** [pterodactyl/panel#1594]
**Is your feature request related to a problem? Please describe.**
Feature request/consistency

**Describe the solution you'd like**
The admin server list should use the same server statuses as the user server list.  "Active" when the servers are not online is not properly indicative.  The statuses available to the user list are far more descriptive.

resources/themes/pterodactyl/admin/servers/index.blade.php
public/themes/pterodactyl/js/admin/node/view-servers.js
public/themes/pterodactyl/js/frontend/serverlist.js

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MatthewSH** [comment]
The status you're seeing isn't about current server state but the status of the server itself...suspended, installing, active. The admin page isn't prepared to do something like that, nor do I see a need for admins to be able to see the status of the server.

Also, a quick look tells me that it's not likely that it's possible due to the fact that to get the status you need to call the status route as the user who owns the server or is a subuser. Now if you're a root admin it's POSSIBLE to do it. I can maybe do some tinkering and because it's a root admin I could almost force the action...but it may not be pretty and I don't see a real use for it as you can't change the state of a server in admin by default anyway. So what's the purpose of showing the server status?

**Comment by AusHick** [comment]
I don't really see who else could possibly even know the server exists beside the owner, a sub-user, or a root admin?  The root admin server list that shows all servers is the one that I was referencing in the first place.

Having more information immediately available to the admins at a glance is hardly a bad thing, and certainly won't cause any information overload.  It's just that the statuses as they are now aren't really helpful, especially when you want to track down, say, a performance issue across the node, and all the servers say "active", when only 2/10 are actually online.

**Comment by matthewpi** [comment]
Closing as v2 is re-creating the entire admin.
