### ISSUE TITLE
2FA QR Code won't work if company name has a space on it

### ISSUE THREAD

**Issue by luizsusin** [pterodactyl/panel#1624]
**Background Information**
- **Panel or Daemon:** Panel
- **Version of Panel/Daemon:** 0.7.14 
- **Server's OS:** Ubuntu Server 16.04
- **Your Computer's OS & Browser:** Windows 10 - Google Chrome 75.0.3770.100

**Description of the Bug**
When I enable 2FA, it shows up a QR Code. The QR Code generated is scanned by Google Authenticator, but it says "Invalid barcode", and that the bar token is not valid for authentication. Aparently, as I tested, the cause is because the company name of the panel has a space on it. When the space is removed, it works just fine. 
**@Edit:** It can also lock the person in the panel if the Panel Setting "Require 2-Factor Authentication" is set to Admin Only/All Users and the person removes the 2-Factor Authentication for some reason. The user won't be able to unlock it until the company name is set to the name without spaces.

**Steps to reproduce**
1. Certify that the panel name has at least a space on it;
2. Access Account Security menu;
3. Select Enable 2-Factor Authentication;
4. Scan the code with Google Authenticator.

**Expected behavior**
Expected to scan and add it to the Google Authenticator. Not sure what kind of fix could be possible, but maybe parsing it to remove the spaces?

**Comment by Sir3lit** [comment]
Im not able to reproduce this, could you share the name that you're trying to use? I used `Clusterio Panel 2.0` and the google auth app on Android was able to scan it

**Comment by luizsusin** [comment]
> Im not able to reproduce this, could you share the name that you're trying to use? I used `Clusterio Panel 2.0` and the google auth app on Android was able to scan it

Sure! I actually used "Painel CrafTIT", but I've used Google Authenticator on iOS, version 3.0.1. My bad, I should have specified that it was the iOS version. Maybe it's the authenticator fault, then?
A friend of mine also tested on the iOS version, no success either.

**Comment by Sir3lit** [comment]
![image](https://justmyrandomstuff.com/img/og38dLj.jpg)

Seems to work for me? do you have anyone with a non iOS device that could try? or maybe try a third party auth app?

**Comment by luizsusin** [comment]
> Seems to work for me? do you have anyone with a non iOS device that could try? or maybe try a third party auth app?

Sadly, I don't have any non iOS device at the moment, but I may be able to get one later, in case its needed. I've just tried using Authy and it says "Format not supported".

**Comment by MatthewSH** [comment]
I can confirm that the change in 092e7e79fff858ee026608c7dbccab165a67526f does break 2FA for company names with a space. I reproduced it on the demo panel and a testing panel I have.

So it comes down to the first parameter. Google Auth and Authy are parsing `%20` as spaces which is invalid format. How Pragmax solves this? I'm not quite sure yet. There do seem to be some differences in the way 0.7.14 and 0.7.13 are displaying in the authenticator itself. I think it has something to do with the fact that now, instead of displaying a raw data instead of a URL. Maybe there's a variation here. I'll definitely look into this. However, a temporary fix could be to replace all instances of spaces in the company name with a `-` instead. So when the `rawurlencode` option is called, it's not coming back as `Company%20Name` but instead `Company-Name`. Now I have to test this and this is all just theory right now, but I do know it has to do with spaces not being accounted for properly.

I've gone a step further with this. According to Google Authenticator's wiki [here](https://github.com/google/google-authenticator/wiki/Key-Uri-Format#label) the label should be able to contain `%20`. While this is acceptable (in theory) on Android, on iOS it seems to be having issues. It fails with their own example (full URL for QR code [here](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=otpauth://totp/ACME%20Co:john.doe@email.com?secret=HXDMVJECJJWSRB3HWIZR4IFUGFTMXBOZ&issuer=ACME%20Co&algorithm=SHA1&digits=6&period=30), example listed [here](https://github.com/google/google-authenticator/wiki/Key-Uri-Format#examples)). There seems to be an [issue open](https://github.com/google/google-authenticator/issues/674) there as well.

**Comment by Sir3lit** [comment]
I can confirm it works on andorid also.
