### ISSUE TITLE
Rearrangement of Tab Locations on Server Screen

### ISSUE THREAD

**Issue by Blob-Senpai** [pterodactyl/panel#1710]
**Is your feature request related to a problem? Please describe.**
Navigating the server page at first glance is confusing when trying to find SFTP info.

**Describe the solution you'd like**
I purpose a slight modification to the tabs hierarchy and order in a server view. Look at the image below if you do not wish to read the text view. I highlighted all my suggestions in red.
This is under server management

Console
File Management
-- SFTP Info
-- Web Manager (Work on the name)
Subusers
Schedules
Databases
Configuration
--Server Name (Could be removed and an edit button on the right side of the Server Name on the top of the navbar)
-- Allocation Settings
-- SFTP Settings (Probably will vanish if there is no configuration planned for this)
-- Startup Parameters

I feel like this minor change will help the interface to become more intuitive for new users to quickly find the info they need without wasting a few minutes searching.

![image](https://user-images.githubusercontent.com/4673158/65825602-ef300300-e246-11e9-8f1d-a79f15e6c0be.png)

**Comment by Lunaversitay** [comment]
I don't think people get confused when they see the base design, and it especially wouldn't take them a few minutes to notice that they can edit the files by clicking on the "File Management" tab or checking out the SFTP settings.

Only small thing I could see being beneficial is the server name being able to be edited straight from the navbar, but since it doesn't really affect anything in-game I don't think it'd be a worth while thing to add in while 0.8 is being worked on with a completely new UI.

**Comment by Blob-Senpai** [comment]
Oh, I didn't know 0.8 had an entirely new UI coming around. If that is the case, then it would be irrelevant for these changes to even be implemented.

And I do agree with you that it doesn't take more than a few minutes to find it, but IMO, if an action can be taken to resolve these few minutes into using it for something else, then it is a positive modification to add. It would just upset the people who are used to the old way, but with a new UI these talks are quite meaningless.

**Comment by DaneEveritt** [comment]
This won't be happening since 0.8 is a whole new UI. Thanks for taking the time to suggest it though. :)
