### ISSUE TITLE
Mysql connections doesn't close

### ISSUE THREAD

**Issue by Tooxic** [pterodactyl/panel#1717]
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon:  0.7.15
* Server's OS: Centos 7
* Your Computer's OS & Browser: Windows 10

**Describe the bug**
The panel doesn't close mysql connections and after sometime you have to restart the mysql server to get it working again.

**Comment by mayed505** [comment]
This seems to be a configuration at your end. I can safely assume it has to do with the active connection settings. This isn't exactly Pterodactyl's issue.

**Comment by DomiiBunn** [comment]
the panel should keep 4 connections live at any given time unless it needs extra due to load. Furthermore [Laravel autocloses db conections](https://stackoverflow.com/questions/28811274/does-laravel-close-automatically-the-db-connections/28838550). So there is most likely an issue on your side since i am not aware of any modifications done by pterodactyl to laravel not to close them

**Comment by lancepioch** [comment]
http://pterodactyl.io/discord
