### ISSUE TITLE
[Feature Request] Rsync Gameserver files

### ISSUE THREAD

**Issue by SanjaySRocks** [pterodactyl/panel#1764]
[Feature Request]
1. Can you add rsync feature for creating fastdownload for gameserver on remote or current server
2. rsync syncs only the changed/new game server files in order to save time and space.
3. Include files/folders which need to be sync
4. Exclude files/folders from sync
5. rsync must be ssh connection

**Comment by adaliszk** [comment]
Maybe helps, the current way I´m addressing this issue is with the use of docker volumes:

1. I´ve made a little proxy which grabs a game folder, then exposes the files filtered onto an http endpoint.
2. This mini server gets picked up by my ingress-proxy (jwilder/nginx-proxy) and gets served as a https subdomain.

This works well with Enemy Territory, and the files are not duplicated needlessly on the server-side.

**Comment by DaneEveritt** [comment]
Looking back at this now I don't understand exactly what is being requested here, or why this needs to be built into the software specifically rather than done in some other manner since it seems to be pretty specific to a game.
