### ISSUE TITLE
Suggestion - Spiget Integration

### ISSUE THREAD

**Issue by James76931** [Pterodactyl/Panel#178]
## Product
Please check the corresponding boxes below for which products this is about.

- [x] Panel
- [ ] Daemon
- [ ] Dockerfile(s) [Please list if so: __ ]

## Type
- [ ] Bug or Issue
- [x] Feature Request
- [ ] Enhancement
- [ ] Other

Hey,

I thought it would be cool if there could be support for Spiget (https://spiget.org/) for Spigot/Bukkit servers so it is possible to install plugins from Spigot directly from the panel.

Documentation: https://spiget.org/documentation

I hope you consider this to be added,
_- James_

**Comment by schrej** [comment]
With v0.6.0 there will be some significant changes regarding services and service packs. It will then be possible to create your own services and add them to the panel easily. As it is very unlikely that new services will be added before 0.6.0 is released you could try to create a service as soon as 0.6.0 is released.

Currently it is also possible to create own services, just have a look at the existing ones. But because of the massive changes they will probably break with 0.6.0 anyways so if it isn't urgent I would suggest waiting.

**Comment by James76931** [comment]
@schrej Ah yeah, the thing is that Spiget isn't really a "service" of sorts, e.g: not a game server like Minecraft, Team Fortress, etc. Spiget is an API for Spigot which has many capabilities so that panels or other types of software can download plugins from the Spigot resources section by using their API. What I meant was like a section which could only be viewed if you are using a Bukkit or Spigot server which allows you to download plugins directly from Spigot to the game server without downloading to your PC, uploading via FTP etc.

**Comment by schrej** [comment]
Oh all right, should've looked at it more, sorry. It's definitely cool, I would like to see that in the panel, we would have to look how to integrate that though as it is very service specific.

**Comment by DaneEveritt** [comment]
I've received this suggestion a few times, and while I'd love to have something like this, implementing it would also be pulling away from the more general scope of the panel, and moving more into Minecraft specific. Hopefully down the road we will be able to support a little more modularity in the panel, but for now the workload and current feature and enhancement backlog puts this very low on the totem pole.

I'm going to close this, but rest assured it is something that I've considered, and may happen later on down the road.
