### ISSUE TITLE
Wings fails to CHOWN folders

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#1814]
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: Alpha 2
* Server's OS:  Ubuntu 18.04
* Your Computer's OS & Browser: Win10 / Chrome

**Describe the bug**
Upon wings startup, it checks the permissions of the files but fails to change the owner of folders from `root` to `pterodactyl`

Daemon 0.6.12
![](https://justmyrandomstuff.com/img/7IQzTBW.jpg)

Wings Alpha 2
![](https://justmyrandomstuff.com/img/4vtifSE.jpg)

**To Reproduce**
Copy files into the data directory for said server after its created
restart wings to "correct" permissions
Looks at folder owners.

**Expected behavior**
All associated files/folders are CHOWN'd correctly

**Comment by Sir3lit** [comment]
It should be added that it also fails to set 755 permissions on some files as well, in my case executables. 

Wings Alpha 2 
`-rw-r--r-- 1 pterodactyl pterodactyl 146660416 Jan 28 08:54 factorio`

**Comment by matthewpi** [comment]
The problem is caused because the Chown method only updates permissions on files and not folders.

The solution would be to add `os.Chown` on https://github.com/pterodactyl/wings/blob/develop/server/filesystem.go#L375

About the file permission part, the filesystem code never sets file permissions.  If the executable does not have the executable permission it would be a problem with the install script or when the file was uploaded.
