### ISSUE TITLE
Protected allocations

### ISSUE THREAD

**Issue by YWatchman** [pterodactyl/panel#1839]
**Is your feature request related to a problem? Please describe.**
When deploying servers with 'dedicated IP Addresses', we have to manually modify the 'Build Configuration'. This can be done better and faster.

**Describe the solution you'd like**
By creating a property like 'protected' or whatever, and checking on the 'protected' request param you can automatically deploy such IP Address. So what you do is creating allocations marked with 'protected' and by deploying with the API you can pass such a parameter so it will only grab from that collection of IPs.

Consider changing protected to dedicated depending on what applications you think it will be used for.

**Describe alternatives you've considered**
Writing my own module, which I actually have zero time for. I can however contribute to this project if this feature request gets approved...

**Comment by DaneEveritt** [comment]
Isn't this the same as the existing functionality in the API that only selects from allocations that are completely un-unused?

**Comment by YWatchman** [comment]
I guess this is not documented then?

Do you mean by that, that it requires this option?
https://github.com/pterodactyl/panel/blob/3820d4e1567ed7b034b194a0beca0cf579551f74/app/Http/Requests/Api/Application/Servers/StoreServerRequest.php#L67 

Because then you should add an option retrieving unused allocations in: 
https://github.com/pterodactyl/panel/blob/develop/app/Http/Requests/Api/Application/Allocations/GetAllocationsRequest.php

**Comment by TrixterTheTux** [comment]
You can append `?include=server` to the allocations request to get the server it is assigned (and check if it is assigned in the first place).

I don't specifically understand
> When deploying servers with 'dedicated IP Addresses', we have to manually modify the 'Build Configuration'. This can be done better and faster.

as you don't need to modify the build configuration when deploying a server...?

Though instead of "protected" concept I'd probably have something similar to #1012 where the endpoint (or replace/extend the "deploy" option on server creation) would allow choosing one or multiple allocations on certain criteria e.g.
* Truly dedicated IP - IP has only 1 port (or specific amount of ports that could also be sequential depending on game's needs), this would solve the issue of non-dedicated IP deployments having a chance to deploy on the actual dedicated IP.
* Generally just allowing selecting multiple ports on a single IP on specific criteria (either them being sequential or specific offset from the main port)

And depending on how this is implemented, there wouldn't be need to separate the IPs in DB or frontend and just let the application using the API filter them out in its wanted way.

**Comment by YWatchman** [comment]
I've simply didn't see the dedicated_ip option there. Whoopsie.

**Comment by iamkubi** [comment]
The problem with the dedicated_ip option is that it only ensures it's dedicated at provisioning time.  Later new servers created with dedicated_ip=false can end up on the same IP as existing servers that had set dedicated_ip=true.

This isn't the behavior that most hosts would expect, but it at least allows you to ensure the default ports are available.

**Comment by YWatchman** [comment]
hmmmm....
