### ISSUE TITLE
Player Time Out 

### ISSUE THREAD

**Issue by Spartan9802** [pterodactyl/panel#1869]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon:  0.6.13
* Server's OS: Debian 9
* Your Computer's OS & Browser: Windows 10

**Describe the bug**
uname: Linux ns3012651 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux
docker info: https://pastebin.com/RPH4mHdf

**To Reproduce**
1) Launch a server in version 1.15.2 paper or spigot
2) Spawn a lot of entities (1800-2500)
3) Wait a few minutes

This happens only with Pterodactyl, by launching the server without any plugin and directly on the command line with the same arrguments, the problem does not occur.

**Comment by DaneEveritt** [comment]
There is not enough information here to indicate that this is directly caused by Pterodactyl, and I don't have nearly enough time in my schedule to sit and test something like this given the information available.

If you're able to come to a definitive conclusion showing that something we're doing in Pterodactyl is negatively impacting performance and leading to this specific issue, you're more than welcome to reopen this issue with those details.

However, we just defer to Docker to run these processes, which leads me to believe if there truly _is_ an issue, its at a lower level than Pterodactyl. Although it is entirely possible you're hitting some resource limit in the containers.
