### ISSUE TITLE
Backup System Storage Limit

### ISSUE THREAD

**Issue by JordanPlayz158** [pterodactyl/panel#1923]
**Is your feature request related to a problem? Please describe.**
No way to define how many backups can be made or how much storage the backups can consume in total

**Describe the solution you'd like**
Have an option when making the server to specify both the amount of backups that can be made per server, and how much all those backups can take up (Both are optional), If either one of the values is 0, the backup system tab is removed or still there and has a page that says it's disabled, if you want unlimited storage for backups or unlimited amount of backups you put -1

**Describe alternatives you've considered**
Having disk space merged with backup space

**Additional context**

**Comment by matthewpi** [comment]
I think it would be better just to limit the amount of backups a server can have.  Due to the planned integration for offloading backups to other services (S3, etc), calculating how much disk space a server's backups take might not always be possible.

In my opinion, it would probably be better to have a "`x` amount of allowed backups" and a "delete backups once they are older than `x` days" configuration options.  Potentially allowing the user to change the option of how often backups are made (they still wouldn't be able to exceed the amount of allowed backups limit).

**Comment by DaneEveritt** [comment]
I'm closing this as the backup system is not yet complete, and that is noted in the release description. :)

**Comment by zKoz210** [comment]
I understand this will not be implemented in 1.0?

**Comment by JordanPlayz158** [comment]
I don't believe it will be implemented by release but there is a possibility that it will be implemented because Dane only closed this because the backup system (at the time) was not yet completed but I'd say by release it should be completed (just guessing) so it is quite possible that it will be implemented later down the line after release.
