### ISSUE TITLE
Minecraft Version 1.11 Fails to Validate in startup

### ISSUE THREAD

**Issue by necrogami** [Pterodactyl/Panel#193]
Latest downloads 1.10.2 and when i try to use 1.11 in version box it fails to validate the regex, further if i type 1.11.0 it works just fine. but 1.11 does not.

Latest Daemon, Panel,

**Comment by DaneEveritt** [comment]
Known issue, the release tonight will include a fix. For now `latest` should at least download it.

**Comment by necrogami** [comment]
Latest downloads 1.10.2

**Comment by DaneEveritt** [comment]
Really? Theres a spigot post saying that it now downloads 1.11.

As a temporary fix, you can go to *Admin* --> List Services --> Minecraft --> Spigot and edit the `DL_VERSION` regex to be `/^(latest|[a-zA-Z0-9_\.-]{3,6})$/` (rather than `/^(latest|[a-zA-Z0-9_\.-]{5,6})$/`) which should allow versions such as `1.8` as well as `1.11`.

**Comment by necrogami** [comment]
This is vanilla Minecraft service not spigot, but I'll try that regex

**Comment by DaneEveritt** [comment]
Oh, I see, ok I will fix that as well, I believe it has the same regex.
