### ISSUE TITLE
IPv6 support for servers

### ISSUE THREAD

**Issue by 231603** [pterodactyl/panel#1935]
**Is your feature request related to a problem? Please describe.**
Hi. I just got an ISP with native IPv6 support. I was able to allow others with IPv6 to connect to my pterodactyl servers (Minecraft and such), but when they connect instead of saying "[/THEIR_IP:50284] logged in with entity id" blah blah when connecting with IPv6, it says "[/172.18.0.1:46406] logged in with entity id" blah blah. I am not sure why instead of showing the users IPv6 address, it shows 172.18.0.1, when testing on a different computer connecting to IPv6, I was able to see the IPv6 address of the player. 

**Describe the solution you'd like**
I think it would be cool to show the users IPv6 address so that player management can be possible, such as an IP ban. Perhaps I am doing something wrong. 

**Describe alternatives you've considered**
Right now, I have the following on cloudflare: A record to my ipv4 address and AAAA record under the same name to allow IPv6 clients, and IPv4 clients to join under the same address.
**Additional context**
It's not needed but I like messing around with IPv6

**Comment by schrej** [comment]
How on earth is "IPv6 stuffs" a useful title? I feel like closing this Issue without further comment just because of that.

**Comment by danielnaaman** [comment]
I'm not entirely sure about the status of this in versions like 1.15 but generally Minecraft IPv6 support is pretty bad and in ninety percent of the cases would cause too many issues.

There's a good chance the users appear to be logged in like that because of something to do with the server automatically assigning them to some sort of local NAT to make so they can enter the server by technically using IPv4.

I'm just posting my theory here, did absolutely no research on that.

But still, the panel itself fully supports IPv6 per my knowledge, why shouldn't it? :P
And about the daemon I'm unsure but I assume that it does too. Problem is probably on Minecraft's end.

**Comment by danielnaaman** [comment]
This is a clone of issue #1778.
