### ISSUE TITLE
Folders with non-english letters cause an exception when navigating to them

### ISSUE THREAD

**Issue by vilhelmprytz** [pterodactyl/panel#2040]
**Background (please complete the following information):**
* Panel or Daemon: panel (might be wings?)
* Version of Panel/Daemon:  v1.0.0-beta.3 for panel and v1.0.0-beta.4 for wings
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Ubuntu 18.04 with Google Chrome

**Describe the bug**

When I create a folder named `ä` or other characters (Swedish) such as `å` or `ö` it appears to be working properly.

![pterodactyl-folder-name](https://user-images.githubusercontent.com/15460993/82159395-0ed77280-988e-11ea-98f6-fa51e6733016.png)

But when I click the folder name, I get this error.

![something_whent_wrong](https://user-images.githubusercontent.com/15460993/82159415-2b73aa80-988e-11ea-9dae-68a53582682a.png)

On Wings, I can see the HTTP request showing up as an `404` error.

```
[GIN] 2020/05/17 - 20:32:02 | 404 |       72.93µs |       10.0.1.67 | GET      "/api/servers/37d1da4d-c264-424b-92fb-456c5b5d67ed/files/list-directory?directory=%2F%25C3%25A4"
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new server.
2. Once it has finished installing, go to "File Manager" and create a new folder.
3. Name the folder `ä` or `å` or `ö`.
4. Create the folder and then navigate to the contents of the folder by clicking on it.

**Expected behaviour**
I expect the panel to be able to navigate to all folders, even folders with special names. I can verify that the folder is indeed created on the system. I can see it from within the daemon server itself and using an external SFTP client.

**Comment by matthewpi** [comment]
Decoding `/api/servers/37d1da4d-c264-424b-92fb-456c5b5d67ed/files/list-directory?directory=%2F%25C3%25A4` returns `/api/servers/37d1da4d-c264-424b-92fb-456c5b5d67ed/files/list-directory?directory=/%C3%A4`

Encoding `ä` returns `%C3%A4` (I also tested decoding and it returned back `ä`)

If you decode the returned url from the first decode again (run the original url through the decoder and run the response through the decoder again) you then would get `/api/servers/37d1da4d-c264-424b-92fb-456c5b5d67ed/files/list-directory?directory=/ä` which is the proper encoding.

The problem is with the encoding being ran twice, `%C3%A4` is already url-encoded but encoding it again causes the `%` signs to be replaced with `%25`, causing the url to not be decoded properly (unless ran twice).
