### ISSUE TITLE
Source Engine >> Ark: Survival Evolved EGG not working for Scorched Earth map

### ISSUE THREAD

**Issue by UndercoverNL** [pterodactyl/panel#2057]
Hey,
I just want to mention that the ARK: Survival evolved EGG no longer works for certain ARK extensions (maps), in this case Scorched Earth. The RAM hangs around 4000 - 5000 MB and does not go over it.
The server does not appear in the steam server list either

I am currently using your github release for which there are extended installation options. But also the basic EGG on the panel is not working and have the same issue.

the island (map) just goes to the usual 8GB ram, and therefore also appears in the steam ARK server list

I would really appreciate if you can solve this problem when you have time.

Thanks in advance!

**Comment by parkervcp** [comment]
Can you expand on what the exact settings you are using that is causing the issue?

**Comment by DaneEveritt** [comment]
That egg does not ship with the panel by default, please confirm it is an issue caused by this software and not the egg itself. We can reopen the issue if that is determined to be the case.

**Comment by parkervcp** [comment]
ARK most definitely does ship with the panel

https://github.com/pterodactyl/panel/blob/develop/database/seeds/eggs/source-engine/egg-ark--survival-evolved.json

**Comment by UndercoverNL** [comment]
> Can you expand on what the exact settings you are using that is causing the issue?
> 
> @UndercoverNL

With the GitHub EGG:

10GB RAM
50GB Disk

Query Port: 27015
RCON Port: 27020
Max Players: 20

Startup: `./ShooterGame/Binaries/Linux/ShooterGameServer ScorchedEarth_P?listen?ServerPassword={{ARK_PASSWORD}}?ServerAdminPassword={{ARK_ADMIN_PASSWORD}}?Port={{SERVER_PORT}}?MaxPlayers={{SERVER_MAX_PLAYERS}}?QueryPort={{QUERY_PORT}}?bRawScokets?RCONPort={{RCON_PORT}}`

These are the ARK related settings, do you need other settings?

it does not work with any institution. The standard inlaid egg as well as the GitHub egg

**Comment by UndercoverNL** [comment]
> ARK most definitely does ship with the panel
> 
> https://github.com/pterodactyl/panel/blob/develop/database/seeds/eggs/source-engine/egg-ark--survival-evolved.json

Sorry, I tried this egg and it works. I still used the egg from 3 months ago. 

Case closed

**Comment by ByteLocked** [comment]
Some things to note about the ark egg.

First off the rcon will typically connect just be patient and give it time, if the time out happens and the server crashes go to the egg and change the  Start Configuration to 
{
    "done": "Setting breakpad minidump AppID = 346110"
}

and BE PATIENT!!!!!!!!! once ram is high and level and cpu dips you can connect the server ON THE QUERY PORT NOTTTTTT!!!! THE GAME PORT! CONNECT TO SERVERS IN ARK ON THE QUERY PORT!!!


This egg works fine with default setttings if you are patient and give the server enough provisioned resources to not time out while it generates the map.

CONNECT TO ARK SERVERS ON THE QUERY PORT!!!!

(Adding this here because its the most common return on google search and it is astounding how many people think this egg is broken but just do not understand how ark servers work)
