### ISSUE TITLE
API for Externallogin

### ISSUE THREAD

**Issue by Nevercold** [pterodactyl/panel#2069]
Feature-Request
_Sorry for Bad English... xD_

**Describe the solution you'd like**
A API to create a Sessiontoken for a User. 

I have a Website, where user can buy a Server.
There is a Loginbutton to instant login automatic in pterodactyl. 

**Additional context**
Plesk has this feature. 
https://docs.plesk.com/en-US/obsidian/api-rpc/about-xml-api/reference/managing-plesk-server/creating-session-tokens.73865/

**Comment by DaneEveritt** [comment]
I will not be adding this functionality.

**Comment by Nevercold** [comment]
but why?

**Comment by Nevercold** [comment]
Has the SSO Docs? @DaneEveritt

**Comment by FoksVHox** [comment]
As of right now, there isn't an SSO / SSO documentation. I think Dane is referring to #1964. Also I see a huge security flaw if the API got created, due to the fact that you can log the user in with. And it sounds very dumb to say at least. With stuff like Google Password, LastPass, or any other password storage, this wouldn't be necessary at all. @Nevercold
