### ISSUE TITLE
API endpoint to validate connection is successful

### ISSUE THREAD

**Issue by parkervcp** [pterodactyl/panel#2102]
**Is your feature request related to a problem? Please describe.**
When using the api I would like to check if I have a valid token. This would be useful for api applications. (for now I am grabbing the first page of users)

**Describe the solution you'd like**
An endpoint that I can just run a GET (application and client) to and it responds with a 200 OK or a 403 Unauthorized

**Describe alternatives you've considered**
Currently I am just querying the application api for users and the client api to get servers. I know it's an extra endpoint. I just feel like it's making a query I shouldn't need to.

**Comment by DaneEveritt** [comment]
In retrospect, I'm not sure I understand how this is necessary. I attempt to follow valid REST API response codes, so you'd get a 403 if you're not providing valid credential headers, and a 401 if you don't have permission for the endpoint.

Not sure how a single endpoint would solve anything, especially since a token can be valid for one endpoint, and invalid for another.
