### ISSUE TITLE
[DAEMON] Host mode problem

### ISSUE THREAD

**Issue by Talhazzers** [pterodactyl/panel#2115]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.6.13
* Server's OS: Ubuntu 19.10, Debian 4.9.210-1 (3 nodes, same problem)
* Your Computer's OS & Browser:  Windows 10 - Chrome

**Describe the bug**
Docker runs smoothly for 5-6 days, but suddenly network settings are breaking and i can't install new servers, can't get URLs and download files, when I restart the docker service it gets better but after a while it gets corrupted again. Im using daemon in host mode.

**Comment by DomiiBunn** [comment]
Can you provide `docker info`

**Comment by Talhazzers** [comment]
Client:
 Debug Mode: false

Server:
 Containers: 54
  Running: 9
  Paused: 0
  Stopped: 45
 Images: 16
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-55-generic
 Operating System: Ubuntu 19.10
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 68.7GiB
 Name: XX.ekiphost.com
 ID: UANU:WU7W:3MDW:7GSE:HQYD:3MGU:ASUN:26MA:WICV:5IGQ:VWZZ:QINF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

**Comment by DaneEveritt** [comment]
This is unlikely to be an issue with Pterodactyl, especially since you've already pointed out that it appears to be an issue with Docker specifically.

Unfortunately I do not have the time in my schedule to keep issues like this open or even pretend I will look into it, especially for issues like this where there really is not any actionable information, reproduction steps, or widespread reports.

Please feel free to re-open this issue if you come across definitive proof showing this is due to something Pterodactyl is doing. 👍
