### ISSUE TITLE
BETA: Restart of Wings required after each server install

### ISSUE THREAD

**Issue by LaurenceMillward** [pterodactyl/panel#2218]
I can't see this reported anywhere open/closed, but I've seen it raised a few times in Discord and I have the same issue so i'll raise it just in-case. 

Wings Beta 8 (Ubuntu 20) / Panel Beta 6 (Ubuntu 18); when creating a new server Wings has to be restarted each time (service wings restart) for anything to do with that server to be displayed (such as the installation progress of an Egg). Until this the restart is performed, the container will look like it's in a stuck state with no information displayed. The stop/start buttons don't do anything either. 

As soon as a service wings restart is performed, the panel shows the installation progress & data about the container. 

Edit: Here's an image of what the panel looks like after creating a new server: https://cdn.discordapp.com/attachments/658550982975946762/740308180491305030/unknown.png

**Comment by LaurenceMillward** [comment]
From Discord as I just realised there's an update for Wings & the Panel:

```
Lozza Today at 19:52
@Adrawyn @123hotdog1100 - What Wings / Panel version are you running? Just realised there's a new version for both out
Adrawyn Today at 19:55
The last version
v1.0.0-beta.7
v1.0.0-beta.9 for the wings
```

**Comment by 123hotdog1100** [comment]
> 
> 
> From Discord as I just realised there's an update for Wings & the Panel:
> 
> ```
> Lozza Today at 19:52
> @Adrawyn @123hotdog1100 - What Wings / Panel version are you running? Just realised there's a new version for both out
> Adrawyn Today at 19:55
> The last version
> v1.0.0-beta.7
> v1.0.0-beta.9 for the wings
> ```

I have the latest version for both wings and the panel and i am getting this issue here

**Comment by Adrawyn** [comment]
Having this issue too, but I have only tested it on a VPS KVM Starter hosted in OVH.

**Comment by matthewpi** [comment]
Just to clarify this is the issue is when the server console page flashes while installing/reinstalling

**Steps to reproduce:**
1. Create a new server (don't skip the install script) or reinstall an existing server.
2. Go to the server's console (you must open it in a new tab, either using the button in the admin area or middle-clicking on the console tab in the client-area)
3. Watch as Rave Mode™ takes control of your panel.

![tbawRvyvHiCKt5nE](https://user-images.githubusercontent.com/26559841/89353795-770b4880-d674-11ea-83e0-4eab8c4ef0a1.png)

**Comment by parkervcp** [comment]
@matthewpi Is this not related to #2190 then?

**Comment by matthewpi** [comment]
Related to #2190
