### ISSUE TITLE
Generate HASHIDS_SALT from "php artisan key:generate --force" 

### ISSUE THREAD

**Issue by vilhelmprytz** [pterodactyl/panel#2231]
**Is your feature request related to a problem? Please describe.**
While the recommended way is of course to use the built-in `php artisan p:environment:` commands to configure your installation, some users might just directly edit their `.env` files using their editor of choice. This is especially true if you are using some sort of templating software (e.g. Ansible). If a user were to configure their `.env` files manually, the only thing left to run is the `php artisan key:generate` command. Currently, the `HASHIDS_SALT` is set in the `.env` when the user runs `php artisan p:environment:setup`. This is problematic since then `HASHIDS_SALT` is never set if a user edits their `.env` file manually.

**Describe the solution you'd like**
I think it would make more sense if `HASHIDS_SALT` is randomly generated and set in the `.env` file when the `key:generate` command is run.

**Describe alternatives you've considered**
None.

**Additional context**
(I am the author of pterodactyl-installer, a script which installs Pterodactyl)

**Comment by arcdigital** [comment]
We can't change how key:generate works...it's part of Laravel.

**Comment by vilhelmprytz** [comment]
> We can't change how key:generate works...it's part of Laravel.

@arcdigital Is it possible to create a separate command to trigger the generation of `HASHIDS_SALT` only?

**Comment by DaneEveritt** [comment]
Probably, but its equally easy to just generate it using a bash command and using sed to replace the value in the `.env` file if needed. This is such an edge case scenario that a majority of users won't encounter. It'd be quicker for you to just do something like that than us have this issue sit here indefinitely since it isn't really at all a priority for me.

Or you're welcome to write the command and PR it. :)
