### ISSUE TITLE
403 returned when server is suspended on api calls for details/resources. 

### ISSUE THREAD

**Issue by Sir3lit** [pterodactyl/panel#2279]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: rc2
* Server's OS: Ubuntu 18.04

**Describe the bug**
When calling `api/client/servers/<id>` there is a `is_suspended : false`
```json
{
    "object": "server",
    "attributes": {
        "is_suspended": false,
     }
}
```
But when the endpoint is called a 403 AccessDenied is thrown instead. 

Same for `api/client/servers/<id>/resources`
```json
{
    "object": "stats",
    "attributes": {
        "current_state": "offline",
        "is_suspended": false,
        "resources": {
            "memory_bytes": 0,
            "cpu_absolute": 0,
            "disk_bytes": 21256741698,
            "network_rx_bytes": 0,
            "network_tx_bytes": 0
        }
    }
}
```

**To Reproduce**
1. Suspend server.
2. Make API Call

**Expected behavior**
The call to return a 200, with the correct information and with `is_suspended` set to true.

**Comment by DaneEveritt** [comment]
A 403 is certainly the wrong error code to return for a suspended server, since that indicates the wrong authentication headers were being sent. I'll adjust that to be the correct code.

However, I think it is actually fine if the endpoint returns an error back to the caller, since that is how all of the other endpoints work for suspended servers, and a suspended server (forbidding any garbage code on my end) should never even return stats or be in any state other than offline.

The `is_suspended` field is perhaps unnecessary in this context and leading to the confusion.

**Comment by DaneEveritt** [comment]
Actually, yeah it does need to return a 200, I see.
