### ISSUE TITLE
artisan environment commands should write critical values in quotes

### ISSUE THREAD

**Issue by schrej** [pterodactyl/panel#2304]
There has been an [issue](https://discord.com/channels/122900397965705216/658550982975946762/750357809593581668) where a password wasn't read correctly from the .env file as it wasn't quoted. We should make sure that values like passwords are written in quotes in the .env file to prevent this from happening.

**Comment by DaneEveritt** [comment]
It already writes them into quotes if it detects there is a need though?

Can we also please convert those Discord links into screenshots or transcriptions to make these issues more logical rather than having to open up Discord to figure out the context (and god forbid the message just disappears and this issue no longer has context).

**Comment by DaneEveritt** [comment]
```
JellyPiesToday at 7:14 AM
@JellyPies
@schrej The .env file doesn't wrap the sql user password in quotes by default, because of this it was reading some symbols in the password as syntax
```
