### ISSUE TITLE
Middle button for scrolling

### ISSUE THREAD

**Issue by Telesphoreo** [pterodactyl/panel#2322]
**Is your feature request related to a problem? Please describe.**

So my mouse (nothing to do with the panel) has a weird problem where it just doesn't scroll very well. I've adapted clicking the scroll wheel and using the "middle click" feature to scroll through websites. On the 0.7.x panel, you could middle click and scroll through the console. On 1.0.0-rc3 you can only use the scroll wheel to scroll through the console.

**Describe the solution you'd like**
I would like the previously functionality of being able to use middle click to scroll through the console implemented again.

**Describe alternatives you've considered**
The obvious alternative is to just use the scroll wheel, but mine is basically broken. I could also click and drag the scroll bar itself, but it's faster to middle click wherever and scroll.

**Additional context**
Here's a video to show what I mean. Here's me middle clicking and scrolling through my files in the file manager. I would like this exact functionality but for the console
https://packs.smokes-crystal.rocks/M25fgD0Xxx.mp4 (sorry for the lag LOL)

**Comment by Sir3lit** [comment]
I mean, you could click the scrollbar and move your mouse up and down...

**Comment by Telesphoreo** [comment]
@Sir3lit "I could also click and drag the scroll bar itself, but it's faster to middle click wherever and scroll."

**Comment by matthewpi** [comment]
The problem is the console is now using xterm.js which uses a custom scrollbar entirely as it is uses `canvas` instead of a `div` with a bunch of children for displaying lines.  This means that scrolling, highlighting, and other functionality is not handled by the browser directly, it's offloaded to xterm.js (which we didn't write).

Just to be clear, I'm not blaming xterm.js for this behavior.  This functionality might not be easy or really possible to implement as middle-click scrolling is handled either by the OS itself or the web browser which isn't easy to simulate properly.  This behavior must be manually implemented as the `canvas` is the exact size of the console window, it isn't overflowing, the scrolling is entirely simulated.

**Comment by DaneEveritt** [comment]
I'm not implementing this, sorry.
