### ISSUE TITLE
[Users] An error occurs when creating a subuser with a long email

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2408]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/cbedd4539c750fd647ee13dee15c7cb0556029c2 & https://github.com/pterodactyl/wings/commit/f0a4efb242a66c1ec34b1139e8853ab1795cfeea
* Version of Panel/Daemon: 1.0 RC 6
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**
We are trying to create a subuser with email exceeding 255 characters in length. And we get another validation error for long subuser email.

**Comment by DaneEveritt** [comment]
Would you be able to just merge all of your issues regarding the validation errors into a single issue and close the others? Its honestly a lot easier for me to track and fix if they're all in the same issue, since they're effectively all the same issue (and likely to all be fixed with the same code). 👍

**Comment by zKoz210** [comment]
@DaneEveritt I'm sorry if I'm clogging up your repository, I can merge everything if it's more convenient for you

**Comment by DaneEveritt** [comment]
Just would like all of the issues that are the same (validation errors not rendering correctly) to be merged as one issue, and just include the multiple different examples of this happening that you've encountered.

**Comment by DaneEveritt** [comment]
closed in https://github.com/pterodactyl/panel/commit/711efe34bbee5695793934e15a89ac898b09f179
