### ISSUE TITLE
Error when renaming files

### ISSUE THREAD

**Issue by zKoz210** [pterodactyl/panel#2446]
* Panel or Daemon: https://github.com/pterodactyl/panel/commit/e1e079bc1297cc3c2ae70abd2e14b51340332bc1 & https://github.com/pterodactyl/wings/commit/37e59e69286c2b570869acfe93e2cc4219147276
* Version of Panel/Daemon: 1.0 RC 7
* Server's OS: Ubuntu 
* Your Computer's OS & Browser: MacOS, Safari

**Describe the bug**

![image](https://user-images.githubusercontent.com/28255085/95009774-3f495e80-062d-11eb-8bb2-c87a3a362cbe.png)

empty file name:
![image](https://user-images.githubusercontent.com/28255085/95009786-4ec8a780-062d-11eb-803c-4afeb768f2b2.png)

**To Reproduce**
1. Rename file in file manager `PocketMine-MP.phar/wef/we/f/we/fwe/f/`

This bug also appears with archives that can't be moved to folders

**Comment by DaneEveritt** [comment]
The empty file name error is a limitation of how the validator is setup. The 500 error is just going to be a thing that happens when you give it a garbage path.

I'm not concerned with either at this point. One I have no intention of going out of my way to modify, and the other is just an edge case generated by passing obviously invalid rename data. 👍
