### ISSUE TITLE
500 error on creating custom nest

### ISSUE THREAD

**Issue by james090500** [pterodactyl/panel#2489]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0
* Server's OS: Debian GNU/Linux 10 (buster)
* Your Computer's OS & Browser: Windows 10 + Google Chrome

**Describe the bug**
Panel: `PHP 7.2.33-1+0~20201008.48+debian10~1.gbpcb3068 (cli)`
when trying to create a new custom nest a 500 error is recieved. Here is the laravel.log
https://paste.gg/p/anonymous/b75ab403f13e4b099d1dcffadb992bc0

**To Reproduce**
This is an upgrade from 0.7 to 1.0.0. The best reproduction I can explain is to try create a custom nest

**Expected behavior**
Expected behavior is the nest to be created

**Comment by AreYouRlyScared** [comment]
As this shouldn't give you a 500 error... But the issue is that you have an invalid email in the `.env` as the service author. Look for the line below in the `.env` if it's not there add it and make the value a valid email.

`APP_SERVICE_AUTHOR=<email here>`

Side note, you should probably update to PHP 7.3 or 7.4 as that's required by 1.0

**Comment by james090500** [comment]
It seems APP_SERVICE_AUTHOR was ``APP_SERVICE_AUTHOR="php artisan databasestaff@capecraft.net"``. I must have accidentally pasted an artisan command in the email prompt? Odd. Also I will upgrade to 7.4 thanks for th heads up

**Comment by parkervcp** [comment]
I'm considering this resolved then.
