### ISSUE TITLE
Wings - Strange / High memory usage

### ISSUE THREAD

**Issue by Aurelien30000** [pterodactyl/panel#2524]
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: Panel 1.0.1 / Wings 1.0
* Server's OS: Debian 10.6
* Your Computer's OS & Browser: Not related

**Describe the bug**
![image](https://user-images.githubusercontent.com/43724816/96161727-eb395680-0f17-11eb-8ebc-45029e6aad56.png)
As you can see on the screenshot above, wings memory usage seems high and is probably unexpected.
I regularly checked every 6 hours and memory never decreases, expect if I restart the service as well.

`uname -a` : 

> Linux ns3029951 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux

`docker info` 

> ![image](https://user-images.githubusercontent.com/43724816/96161536-b2997d00-0f17-11eb-938c-6be3670718b3.png)

**To Reproduce**
I don't know at all, my setup is good, no massive error in the logs and no issue with panel / server use.

**Expected behavior**
Memory usage should be probably lower and somtimes decreases, it shouldn't increase constanly, I guess...

_Don't hesitate to ask me for more details, thanks!_

**Comment by notAreYouScared** [comment]
A fresh start of wings uses about 32MB of RAM for me. After 3 days of uptime it was at 984MB, do you have a lot of failed sftp logins in the log?

**Comment by Aurelien30000** [comment]
> A fresh start of wings uses about 32MB of RAM for me. After 3 days of uptime it was at 984MB, do you have a lot of failed sftp logins in the log?

A few, for instance only 7 errors concerning sftp login the past 6 hours.

**Comment by Feniksovich** [comment]
By default, systemd's display of RAM usage is disabled. I think this value is incorrect as htop currently shows 22 GB of RAM in use (total). At the same time, I have 10 servers running, each of which uses an average of 2 GB of RAM.

In case wings really consumed that much RAM, htop's memory usage would be significantly higher.

![image](https://user-images.githubusercontent.com/33875970/101363625-d0f27800-38cb-11eb-9d6d-0513ecbff21a.png)
![image](https://user-images.githubusercontent.com/33875970/101364113-6a218e80-38cc-11eb-8234-ca1e16b57ff8.png)

@DaneEveritt

**Comment by matthewpi** [comment]
The `Memory` display in systemd is cached, that value does not provide a good metric for memory usage as it could be as large as your entire system memory if nothing else is running.

Due to the complexity and sheer amount of I/O wings deals with, I'm not going to spend hours hunting down every place where memory usage could be reduced (or finding any potential memory leak).  So, unless you know of something that specifically causes high memory usage (that is not cached), I don't see how this is a bug.

--

I bet if you look in `htop` for wings, it will show lower memory usage than systemd like mine does here:
![](https://user-images.githubusercontent.com/26559841/101366911-c8198c00-3862-11eb-8246-6405144ccbb2.png)

**Comment by Aurelien30000** [comment]
Thanks both for your explanations, so I assume my report is "falsified".
