### ISSUE TITLE
Create a personal network for each users

### ISSUE THREAD

**Issue by Technowix** [Pterodactyl/Panel#266]
Right now, there is the pterodactyl0 network that make containers ables to speak to each others inside the same machine.
The problem is you can reach other users containers that way, and for thoses who rely on the feature that "nobody can be in my localnetwork" (like... every end-user who dosn't setup the panel / aren't really in tech and just want to play).

I think that is a "major" problem, because anybody that have access to the pterodactyl0 network is able to access everybode that have access to this network too.

So, well, this is possible to get per-ser network ? So they can with ease link containers between them, and not passing trought the interwebz.

**Comment by DaneEveritt** [comment]
Switching this to `low` priority, as we already isolate from the host system to some degree, and properly implementing this would take quite some time to manage and test everything. Its a good idea though.

**Comment by DaneEveritt** [comment]
Closing this due to limited development time and capabilities. This feature would require extensive re-working of daemon code, and a lot of work to manage and test properly across systems.

Additionally, I can see this flooding setups and creating a lot of networking nightmares for those with firewall setups. Additionally, unless you used ICC limiting I believe users would still have access to other containers on the host system.
