### ISSUE TITLE
Application API endpoint to get server by UUID

### ISSUE THREAD

**Issue by rxdn** [pterodactyl/panel#2675]
**Is your feature request related to a problem? Please describe.**
Application API endpoint to get server by UUID: the client API allows this, but the response misses some fields, such as numeric server ID

**Describe the solution you'd like**
/api/application/servers/uuid/{serveruuid} should return the server object

**Describe alternatives you've considered**
N/A

**Additional context**
My overall goal is to delete a server by UUID: I need an application API endpoint to get the server's numeric ID by UUID, which can then be used on the delete endpoint.

**Comment by DaneEveritt** [comment]
For now you can just do: `/api/application/servers?filter[uuid]=5e0b3372-e378-42f2-93a5-06faca2d42f0`

Theres another issue open for something similar, so I'm gonna close this. If anything I'll get around to making the internal API act like the client API and use IDs for everything, rather than a mixed bag.

**Comment by rxdn** [comment]
Cheers
