### ISSUE TITLE
Backup fails if it last more than 60 minutes

### ISSUE THREAD

**Issue by GravityCube** [pterodactyl/panel#2688]
**Background (please complete the following information):**
* Panel or Daemon: 1.1.1
* Version of Panel/Daemon: 1.1.1
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Ubuntu & Firefox

**Describe the bug**
I have some backups schedules and the ones that take between 30-60 minutes fail sometimes and always if >60m (several GBs transferred from an ssd to a slow disk). I'm almost sure that it is because PruneOrphanedBackupsCommand executed in the Kernel. I had issues trying to figure it out the issue because it wasn't a consistent behavior until I saw that the task was being executed every 30 minutes.

Panel: v7.4.12
Daemon: Linux fern 5.4.0-52-generic - Docker: 19.03.13

**To Reproduce**
1. Make a backup that takes more than 60 minutes

**Expected behavior**
As long as the daemon is still making the backup it shouldn't be mark as failed.

**IMPORTANT NOTE:** Before wings 1.1.0 it failed because the backup was already marked as completed. Now it fails silently.

**Comment by DaneEveritt** [comment]
You can modify that command to run at a different interval that works best for your machine.

At this time I see no reason to make that change globally. Honestly a backup taking longer than 30 minutes is a symptom of bigger issues, and it is likely that you'd be better served by a custom backup solution to do better incremental type backups rather than full backups.
