### ISSUE TITLE
Composer create homestead files

### ISSUE THREAD

**Issue by DaneEveritt** [Pterodactyl/Panel#27]
@citricsquid suggested the following to have composer setup homestead rather than using the example file.

```
php vendor/bin/homestead make --ip=192.168.10.32", "sed -i '' 's/homestead.app/pterodactyl.local/g' Homestead.yaml
```

**Comment by citricsquid** [comment]
The best way that I've found to do this is to define your own "setup" command within your composer configuration, then encourage people to run that command after cloning your project instead of composer install. For example, a command named `setup` might do the following:

1. Install all the composer dependencies
2. Copy the configuration file
3. Set up the Homestead environment
4. Generate the application key
5. ??? Anything else you need

And you can create such a command in your composer.json like so:

```json
"scripts": {
    "post-install-cmd": [
        "php artisan clear-compiled",
        "php artisan optimize"
    ],
    "pre-update-cmd": [
        "php artisan clear-compiled"
    ],
    "post-update-cmd": [
        "php artisan optimize"
    ],
    "setup": [
        "composer install",
        "php -r \"copy('.env.example', '.env');\"",
        "php vendor/bin/homestead make --ip=192.168.10.32",
        "sed -i '' 's/homestead.app/pterodactyl.local/g' Homestead.yaml",
        "php artisan key:generate"
    ]
}
```

Then someone might do the following:

```shell
$ git clone https://github.com/Pterodactyl/Panel.git
$ composer setup
```

That's the best way I've uncovered so far, I'll update this issue if I ever find something better. Unfortunately it's not possible to do this automatically on `composer install` because there's no "on first composer install", but there's no danger to someone running `composer install` and then `composer setup` after.

**Comment by DaneEveritt** [comment]
Thanks for the note about `.app`, I was unaware of that. I like the idea of using a `setup` command as well. It might be possible to use `post-create-project-cmd`, although I haven't looked into it closely.

**Comment by citricsquid** [comment]
unfortunately the `post-create-project-cmd` event is only fired when you first create a project via composer (`composer create-project --prefer-dist laravel/laravel blog`), so it's not a viable option.

**Comment by DaneEveritt** [comment]
Yeah, it seems like having a custom `setup` command is the way to go. I could potentially include a separate bash script that the install calls each time that checks if it has ready been run, but that is excessive. Plus, if it is its own command they can always redeploy if for some reason it is needed.

**Comment by citricsquid** [comment]
Discovered that the command included for changing the hostname in the Homestead configuration won't work cross platform. Essentially `sed` does not have a cross platform way to rename in place without a backup file ([Stackoverflow discussion of the problem here](http://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux)). The cross platform *solution* is to enable the backup file and then remove it after, so the command looks like:

```
sed -i.bak 's/homestead.app/pterodactyl.local/g' Homestead.yaml && rm Homestead.yaml.bak
```

**Comment by DaneEveritt** [comment]
Still need to provide documentation for editing their hosts file as well, I could echo it in probably, but that would require sudo privileges.

**Comment by DaneEveritt** [comment]
I probably should have a `setup-dev` and `setup` command, but I'll come back to that when we figure out how we will be shipping the final panel.
