### ISSUE TITLE
Seen a lot of people have fullchain.pem no file or directory issues because of case sensitivity

### ISSUE THREAD

**Issue by PeterPerry22** [pterodactyl/panel#2745]
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: 1.0
* Server's OS: Ubuntu 18.04
* Your Computer's OS & Browser: Windows 10 Google Chrome

**Describe the bug**
Please provide additional information too, depending on what you have issues with:
Panel: `php -v` (the php version in use).
Daemon: `uname -a` and `docker info` (your kernel version and information regarding docker)
When manually transferring config file from the panel to wings (and I believe also when generating) if a user enters their domain capitalized, then the config file in /etc/pterodactyl/config.yml will have the directory path capitalized, but certbot directory is lowercase causing wings to fail... (Probably hundreds of users come to discord support with this because the fix is to change directory path then run systemctl reset-failed wings and then start it, which many first timers will not know to do (also support bot in discord has no response for error message file not found in this regard)

**To Reproduce**
1. Make directory path in config.yml capitalized, then restart wings... will fail.

**Expected behavior**
A clear and concise description of what you expected to happen. If applicable, add screenshots or a recording to help explain your problem.
should not be case sensitive, so wings should look for directory path whether or not it matches case as domains do not use case anyways...

**Comment by parkervcp** [comment]
Really we should lowercase all urls it sounds like. Domains are case insensitive and it sounds like certbot auto lowercase all characters.

**Comment by PeterPerry22** [comment]
Yes, exactly... If wings just handled domain paths as all lowercase, then that would easily resolve the issue!

**Comment by goxgrue** [comment]
I am trying to install a SSL certificate on Nextcloud which is running on TrueNas core, I am following this guide [www.youtube.com/watch?v=Agq8LcnAWPo](http://www.youtube.com/watch?v=Agq8LcnAWPo), In his case he is using duckdns to get a domain, but I have my own domain ourcloud.faimanworld.com which is a subdomain I created with google domains by creating an A record which points to my public IP address which points to my local machine due to port forwarding of 80 and 443 enabled. I can access it over the internet but it but it shows SSL not installed, so I want it to be secure http (https), but when I follow this guide and enable my SSL it shows this error

root@nextcloud:~ # service nginx restart Performing sanity check on nginx configuration: nginx: [emerg] cannot load certificate "/usr/local/etc/letsencrypt/live/ourcloud.faimanworld.com/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:systemlibrary:fopen:No such file or directory:fopen('/usr/local/etc/letsencrypt/live/ourcloud.faimanworld.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)

[Here is my google domains configuration](https://i.stack.imgur.com/Ad968.png)

Please help me solve this issue

My local configuration is as follows

TrueNas is available at 192.168.1.10 Nextcloud is available at 192.168.1.8

I have port forwarded 80 and 443 for 192.168.1.8 in my router I am able to access my nextcloud over the internet

I just want the SSL and https enabled it when I access it over the internet
