### ISSUE TITLE
Issue due to HTTP>HTTPS redirect

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#277]
# Issue

**Explanation:** I am using a load balancer listening on ports 80 and 443. The incoming traffic on port 80 is forwarded to port 80 at the Nginx level (therefore it remains at port 80). The incoming traffic on port 443 is also forwarded to port 80 at the Nginx level. Since traffic is being received by Nginx at the HTTP level, I included the following within my pterodactyl.conf to redirect this HTTP traffic into HTTPS:

    if ($http_x_forwarded_proto != 'https') {
    return 301 https://$server_name$request_uri;
    }

The end result looks like this:

**Load Balancer**
Listening on port 80 > Forwarding to port 80
Listening on port 443 > Forwarding to port 80

**Nginx**
Listening on port 80
Redirecting to HTTPS

**Behavior**
What I am experiencing is quite odd when using the above. I would expect that this should work. Basically, I am able to access the website (http:// or https://www.xyelz.com), I am able to login, and I am able to navigate normally. I can even create users. However, if I go to delete a user, change a user's settings, change general settings, add a location, etc. the page simply refreshes and nothing changes. I captured the following data when attempting to delete a user:

    <div class="row">
        <div class="col-md-12">
            <h3>Delete Account</h3><hr />
            <div class="alert alert-danger"><strong>Warning!</strong> There most be no servers associated with this account in order for it to be deleted.</div>
            <form action="http://www.xyelz.com/admin/users/view/8" method="POST">
                <input type="hidden" name="_method" value="DELETE">
                <input type="hidden" name="_token" value="rs5tsCoTeZqdjtgsd0tGxbISb5SGxzHpY7vC46uk">
                <input type="submit" class="btn btn-sm btn-danger pull-right" value="Delete User" />
            </form>
        </div>
    </div>

I posted in the Pterodactyl Discord and was told by @Tactical Fish that this is probably redirecting a HTTP to HTTPS request and clearing the post data. Please keep in mind that this occurs for most settings, including changing general settings, adding locations, etc.

**Comment by schrej** [comment]
Why are you doing https -> http -> https? I wouldn't switch protocols twice, just use only one protocol from the balancer onwards?

**Comment by xyeLz** [comment]
This is typically how it's done at the ALB level. Otherwise, you need to maintain certs at the Nginx level, which don't allow you to take advantage of AWS Certificate Manager. In most cases, this scenario works perfectly.

If I don't specify the following:

    if ($http_x_forwarded_proto != 'https') {
    return 301 https://$server_name$request_uri;
    }

then anything coming in on port 80 remains on port 80. Anything coming in via HTTPS also changes into 80 because the ALB is forwarding 443 to 80. The point of the above config was to take the traffic (80 or 443), and encrypt it at the LB level rather than the Nginx level. My config does this, but for some reason something somewhere doesn't like this.

**Comment by xyeLz** [comment]
As an update, this same kind of odd redirection occurs when logging on initially, depending on your configuration. For example, I can access the site at https://www.xyelz.com which redirects me to http://www.xyelz.com/auth/login/. When I change this to https://www.xyelz.com/auth/login/ I am able to login, but once I enter my credentials and login, it redirects me back to http://www.xyelz.com.

**Comment by schrej** [comment]
Oh  i think i understood you wrong the first time.
Nginx is only listening on Port 80 and your Proxy forwards everything from proxy:443 and proxy:80 to nginx:80. Nginx then redirects HTTP to HTTP as a HTTP redirect correct?

Did you set APP_URL in your .env to https://www.xyelz.com?

**Comment by xyeLz** [comment]
No problem @schrej :)

You are correct, except Nginx redirects HTTP to _HTTPS_ as an HTTP redirect.

Also, yes, my APP_URL is properly configured as https://www.xyelz.com. Unfortunately this hasn't seemed to have any impact on the weirdness yet so I'm hoping you guys will have a solution soon. Unfortunately I can't use the panel over HTTP for obvious reasons, so I'm just waiting for you awesome people to work out this kink before I go live. :)

Thanks for your help.

**Comment by xyeLz** [comment]
Some more information that I found:

If I use status code 307 in my config (instead of 301), I am able to get the panel to function properly (or so it seems so far). I'm not sure if this is a frowned upon approach, but it does seem to allow me to work via HTTPS.

**Comment by xGamingDudex** [comment]
It seems like this issue still persists. I have just finished installing a fresh install of the panel. Everything runs over HTTPS, have set APP_URL in the .env config to use HTTPS under installation and everything works fine, except that most settings forms seem to still use HTTP for some reason. Going to any page on the panel, my browser tells me that the page utilises full HTTPS, except pages that have forms on them, like `/admin/settings` or `/admin/locations`. Also inspecting the DOM I find that indeed these sites have forms that uses HTTP instead of HTTPS.

This behaviour seems to be quite strange and in-consisted (in the way that just some pars use http, even though everything else uses HTTPS) and of course there is the underlying security aspect of it, having some forms running through HTTP instead of HTTPS. I do also find though that simply editing the form urls to use `https://<panel domain>/admin/locations` instead of `http://<panel domain>/admin/locations` still works, so it is probably just some mishap somewhere that formats the HTML code to output wrongly generated urls.

**Comment by DaneEveritt** [comment]
You're running behind a proxy I assume. If this is the case, this issue is only fixed in the `0.6.x` branch of the panel, which is still in beta.

If you're needing this fixed ASAP on 0.5.7, you can install [fideloper/TrustedProxy](https://github.com/fideloper/TrustedProxy) which should be fairly easy if you have a basic grasp of PHP & Laravel's structure.

**Comment by Buh13246** [comment]
Hi, I need help too.

I'm behind a nginx proxy https -> vm with http

the APP_URL is set to https://xyz.de but the login forms have http://xyz.de as the link. Can you give me a wink why that is happening?

**Comment by Buh13246** [comment]
Okay, it seems that it didn't get that it is behind a proxy.... I used certbot to also obtain a second cert for the vm and than changing the proxy from https -> https (pterodactyl vm).

Now the Links are all https and I can login finally...

But the application should always write links with the APP_URL right? than the problem would be solved automatically...

**Comment by schrej** [comment]
Have you found this already? https://pterodactyl.io/panel/0.7/configuration.html#reverse-proxy-setup
Also, further questions regarding this on our Discord please: https://discord.gg/pterodactyl
