### ISSUE TITLE
Revoking user's access to server doesn't take effect until user refreshes the console

### ISSUE THREAD

**Issue by OpenSource03** [pterodactyl/panel#2771]
**Background (please complete the following information):**
* Panel or Daemon: 1.1.1
* Version of Panel/Daemon: Panel 
* Server's OS: Debian 10
* Your Computer's OS & Browser: macOS, Safari 

**Describe the bug**
Revoking a user's access to the server doesn't take effect until the user refreshes the console.

**To Reproduce**
Basically, if we have two users and one server, supposing the server is assigned to user A, he'll have the access to the console. Now, if we reassign the server to user B, change the password of the account of user A, or do pretty much anything, user A will still have access to the console, no matter what, as long as he doesn't refresh it. He will lose access to all other panel parts, but even after navigating off of the console interface, to something like, for example, databases or schedules, and then coming back to the console, he'll still have access to send commands or execute power every power action.

**Expected behavior**
User should no longer have access to the server console or power actions in events of:
- user logging out using another tab in the browser
- he's the server being reassigned to another user
- user being forcefully logged out (such after password change)

**Comment by notAreYouScared** [comment]
Should be noted that tokens still expire every 10 to 15 mins. So user A would eventually lose access depending on when the key expires.

**Comment by M-AlNoaimi** [comment]
Would there be a way to have that key get revoked at the same time? I know this might not be relevant or a priority but I've been in cases where removing a sub user was due to a dangerous reason that required the user to get off immediately.

**Comment by DaneEveritt** [comment]
Subuser removal does revoke the tokens immediately.

**Comment by notAreYouScared** [comment]
What it sounds like is when server ownership is changed from user a to user b, user a can still access the console because their token doesn't get invalidated.

**Comment by zKoz210** [comment]
https://github.com/pterodactyl/panel/issues/2429

**Comment by notAreYouScared** [comment]
Should also be noted that when a subuser is edited the key gets revoked immediately. This was a change that was made in #2656

**Comment by M-AlNoaimi** [comment]
> What it sounds like is when server ownership is changed from user a to user b, user a can still access the console because their token doesn't get invalidated.

Yeah that's basically what happened. A change might've been done after the release of v1, I'll test and see if it still exists.

**Comment by notAreYouScared** [comment]
Able to reproduce on v1.1.1

**Comment by DaneEveritt** [comment]
I've purposefully skipped over the first and third request here when it comes to password stuff. Changing the server owner will trigger a revocation however.

For the first point, just because a user logs out of one browser does not mean they logged out of other browsers, and revoking at that point would end up revoking tokens for every logged in session as well. While the Panel is designed in such a way that it can handle that just fine, it is unnecessary and does not seem relevant IMO. Per the third request, that would be hellish to implement especially for users with a large number of servers, you'd have to make a ton of API calls and queries in order to figure out all of the servers that need tokens revoked. More realistically, the design of the system is as best I can make it using JWTs, which are stateless by nature.

These requests are looking to implement a more stateful solution for session handling in the websocket, and given the sheer number of users and environments we need to support I don't see there being a particularly good solution here without seriously impacting performance of the software. Remember, these tokens reset when wings reboots, or every 10 minutes by default, so they're not incredibly long lived tokens.
