### ISSUE TITLE
Backups fail with error, causing the daemon to crash and not restart

### ISSUE THREAD

**Issue by RickyB98** [pterodactyl/panel#2839]
**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.1.1
* Server's OS: Debian GNU/Linux 9 (stretch) - Kernel Version: 4.9.0-14-amd64
* Your Computer's OS & Browser: macOS, Safari for macOS

**Describe the bug**
The scheduled backups fail throwing the exception in the image (from journalctl) and crashing the daemon. It seems to be related to `tar`.

<img width="1444" alt="Screen Shot 2020-12-09 at 08 34 44" src="https://user-images.githubusercontent.com/7370908/101599061-68091e00-39f9-11eb-87b7-16427bb9e379.png">

**To Reproduce**
1. Run a backup.
2. See it crash.

I understand this is rather generic, and most likely dependent on the specifics of my server setup, but I wouldn't even know where to start looking in terms of why it only happens for one of the servers and not the others.

**Expected behavior**
The backup should happen. Again, very generic.

**Comment by notAreYouScared** [comment]
The issue is when the backup is being made the server is still editing the files.

Duplicate of #2068

**Comment by RickyB98** [comment]
Alright, closing then.

**Comment by matthewpi** [comment]
The panic is also caused by the logger which was fixed in `v1.1.3` of wings.  For the `tar: write too long` error, I've limited the size of the reader that is used to write to the archive which means it should no longer error out, however this can lead to problems with individually corrupted files that were truncated while the archive was in the middle of reading from them.

**Comment by RickyB98** [comment]
I'll be waiting to update then until a more stable solution is found. Thanks for the heads up!

**Comment by matthewpi** [comment]
> I'll be waiting to update then until a more stable solution is found. Thanks for the heads up!

`v1.1.3` is more stable overall including for backups, that solution is one of the only ways to prevent that error from occurring other than having whatever is writing to the file, stop writing to the file.  There will most likely not be anything else we can change to improve that problem due to the way disks operate.
