### ISSUE TITLE
Wings random freeze (Too many open files)

### ISSUE THREAD

**Issue by VibeGAMESNL** [pterodactyl/panel#2900]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.1.3
* Server's OS: Ubuntu 20.04

**Describe the bug**
We experienced some random wings freezes that caused the SFTP and game panel server management to stop working. So I runned wings in debug mode and found out that these error where causing the issue:

![image](https://user-images.githubusercontent.com/66668585/102901593-19826780-446e-11eb-94a9-e00cfe2b925e.png)

**To Reproduce**
- No idea

**Expected behavior**
Wings should not freeze 👍

**Comment by matthewpi** [comment]
This usually happens when the process (or system) reaches the open file limit, this could be for many reasons, some of the common ones are: not closing a connection after it is no longer needed or actually having that many open connections.  Based off of how many people are running wings for large quantities of servers and connections, I'm going to assume it is the latter.  Unless you have a way to reproduce this (like by opening and closing a bunch of connections or something), I'm going to assume that this is a system issue rather than a wings issue.
