### ISSUE TITLE
Docker Host Mode switch per server/egg

### ISSUE THREAD

**Issue by hexed** [pterodactyl/panel#2910]
**Is your feature request related to a problem? Please describe.**
Yes. Allow certain eggs to run docker host mode but the rest of the eggs to run docker bridged mode.
As some games require Host mode most others don't.

**Describe the solution you'd like**
Add a section either in the eggs or per server to enable docker host mode on that egg or game server.

**Describe alternatives you've considered**
I have tried every possible way to get certain games to work on bridged mode but they just won't connect specifically steam servers with multiple ips.

**Comment by trenutoo** [comment]
You should not be using host mode at all for commercial usage. Once you've enabled it, then everything is exposed and users can use any IPs and ports, even the ones that are reserved or not allocated.

Your steam server issue is due to it sending everything to steam servers through the main interface IP. You could make rules to forward the requests through the other IPs

**Comment by DaneEveritt** [comment]
Not interested in adding such functionality at this time, thanks for the suggestion however.
