### ISSUE TITLE
SendBackupStatus fails because of too fast backup

### ISSUE THREAD

**Issue by Kopf02** [pterodactyl/panel#2962]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: v1.2.0
* Server's OS: Debian 10
* Your Computer's OS & Browser: independent (Win 10 & Chromium based Edge)

**Describe the bug**
The Backup fails with given Error and the Panel shows a timeout after a few minutes.
The same node also has Servers with working Backup and sometimes also the Backup of the Server in the example work.
Also if I add more / larger files, so it takes longer for backup, the backup finishes without any problems.

It seems like the Backup fails, because the backup is finished and tries to send the Information back to the Panel, before the Panel inserted the Backup information to the Database.

`uname -a`: `Linux <hostname> 5.4.78-2-pve #1 SMP PVE 5.4.78-2 (Thu, 03 Dec 2020 14:26:17 +0100) x86_64 GNU/Linux`
`docker info`: https://hastebin.com/kovilirayo.yaml

![image](https://user-images.githubusercontent.com/19476209/103463618-f5583d80-4d2d-11eb-8b55-b2b80037cffc.png)

**To Reproduce**
_1. Run Database on HDD
2. Run Wing on SSD_
3. Create Server with small amount of Data (In my case a small Bungeecord)
4. Creating a Backup
5. See Error in Wing log
6. See failed backup status in Panel after a few minutes

**Expected behavior**
For example retry the request after an certain amount of time (for Example 10 seconds), if the the send fails.

**Comment by DaneEveritt** [comment]
Should be resolved by https://github.com/pterodactyl/wings/commit/3f47bfd292dcfd37739c20065537f10f325d95d4, https://github.com/pterodactyl/wings/commit/49dd1f7bdecddcb18d934b5d06efef5969544044, and https://github.com/pterodactyl/wings/commit/c1ff32ad32e37ae7046e87d77b8162d5b225311b.

There is an underlying issue with how the Panel handles this because it has to make sure the API call to Wings succeeds before marking the backup as starting successfully. However in these cases where it executes instantly it will at least retry for a bit and should just self-resolve.
