### ISSUE TITLE
Daemon SFTP ports over 16-bit integer limit cause reset to port 32767

### ISSUE THREAD

**Issue by AlbertSPedersen** [pterodactyl/panel#2992]
**Background (please complete the following information):**
* Panel or Daemon: Panel and/or Daemon
* Version of Panel/Daemon: Panel 1.22 and Wings 1.23
* Server's OS: Debian 10
* Your Computer's OS & Browser: Windows 10 20H2 and Firefox 84

**Describe the bug**
Setting the Daemon SFTP port to anything higher than 32767 (16-bit integer limit) will cause it to "reset" to 32767.

**To Reproduce**
1. Go to the settings of a Node
2. Input an SFTP port higher than 32767
3. Click "Save Changes"
4. Refresh the page (F5)
5. Notice how the port number has been reset to 32767

**Expected behavior**
The port number should not reset to 32767 and should instead stay at whatever port number was input.

**Comment by FC-FailCoder** [comment]
`Just me explaining in a bit more depth` Don't mind me :)

Due to the `daemonSFTP` having no attributes on the MySQL database (by default) the highest int you can go is '32767' without it resetting back to the default. To change this you would have to add the `unsigned` attribute to the `daemonSFTP`. The highest it can go after this is `65535`. Which is the highest port you can go.

`Little edit:` I'm not sure of the reason why the int is not unsigned by default. Maybe there's a reason but I could see the possibility of it being potentially missed, as it is such a small thing to check. Note that I don't have knowledge in networking and this is probably done for a reason.

**Comment by DaneEveritt** [comment]
It is just a bug, nothing special about why it is a signed int, it should have been unsigned all along but people almost never change the port, especially not to such a high value.

**Comment by FC-FailCoder** [comment]
oh cool. xD

**Comment by VinGal0** [comment]
I was bored so I made a pull request for it #3115
Just to save you a little time.
