### ISSUE TITLE
unicode characters in variables are not translated properly

### ISSUE THREAD

**Issue by parkervcp** [pterodactyl/panel#3009]
**Background (please complete the following information):**
* Panel or Daemon: Daemon/Panel
* Version of Panel/Daemon: 1.X
* Server's OS: Docker Image
* Your Computer's OS & Browser: Windows 10

**Describe the bug**
unicode characters are expanded to they string version 

`§` becomes `\u00a7`

**To Reproduce**
per this issue with the bedrock egg - https://github.com/parkervcp/eggs/issues/929

when updating the config `§` a `\u00a7` is placed instead

probable cause
1. panel converting automatically on input.
2. wings using strings and not runes or something that converts to unicode

**Expected behavior**
actually place the `§` in the file

**Comment by DaneEveritt** [comment]
This was changed by https://github.com/pterodactyl/panel/issues/2308 which means fixing this would therefore break that issue...

The underlying issue here is that games all seem to handle this completely differently and it is super painful for us to figure out if the user is entering a string literal UTF-8 escape or not. This is (IMO) impossible to actually fix with the current structuring since we would still need to handle files where the user is literally typing in the UTF-8 escape sequences, and there is just no way to know at this point without needlessly complicated logic.

I'm closing this issue out in favor of keeping the existing logic because I remember that issue being very prevalent and causing a lot of breakage in different games.

**Comment by DaneEveritt** [comment]
The underlying issue here is that games all seem to handle this completely differently and it is super painful for us to figure out if the user is entering a string literal UTF-8 escape or not.

**Comment by MistakingManx** [comment]
Unsure if it's related, but utf8 conversion just absolutely destroyed my BDS custom content. Anything with any symbols in it that aren't in UTF8 are trashed, which is required for the packs.
