### ISSUE TITLE
Incorrect Timezones

### ISSUE THREAD

**Issue by nackerr** [pterodactyl/panel#3070]
I have my Daemon running on an Ubuntu 20.04 dedicated server, and the timezone is set to America/New York. This is also where my game servers are running.

Panel & Daemon are completely updated. Panel is running Nginx with SSL.

Daemon: Linux 64.40.8.158 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Docker Info:
- Kernel Version: 5.4.0-26-generic
-  Operating System: Ubuntu 20.04 LTS
-  OSType: linux
-  Architecture: x86_64
-  CPUs: 12
-  Total Memory: 62.75GiB

<img width="1011" alt="Screen Shot 2021-02-04 at 12 44 03 AM" src="https://user-images.githubusercontent.com/25311402/106850216-163fe580-6682-11eb-9695-733f01dabc5c.png">

My panel is running on an Ubuntu 20.04 VPS, and timezone is set to the same.

<img width="1011" alt="Screen Shot 2021-02-04 at 12 44 59 AM" src="https://user-images.githubusercontent.com/25311402/106850280-37a0d180-6682-11eb-844b-7d574d0a03b7.png">

I have set my .env correctly as well. 
<img width="219" alt="Screen Shot 2021-02-04 at 12 45 35 AM" src="https://user-images.githubusercontent.com/25311402/106850318-4c7d6500-6682-11eb-8d80-5c5aedf2d1c5.png">

So.. any ideas why times are showing up correctly?

<img src='https://i.ryz.sh/oLq6.gif'>

**Comment by nackerr** [comment]
Also, I've even gone as far as modifying my Dockerfile to include TZ=America/New_York

**Comment by fabm3n** [comment]
For support visit the Discord.
Please follow the Templates for issues.
Also check you wings configuration file.

**Comment by nackerr** [comment]
I've provided all necessary and relevant information. I've shared my concerns in the Discord to no avail. This seems like an issue with the containers not setting the time correctly, because I've set the timezone everywhere.

**Comment by DaneEveritt** [comment]
Set the timezone explicitly in the Wings configuration file, and don't use `EST`, use something like `America/New_York`. Other than that I've got nothing, and there are about 10 other timezone related issues that have been opened and closed because timezones are a disaster and impossible to get perfect for every system out there.

If I'm being honest, I just truly am not motivated to fix an edge case where occasionally a random part of the software handles a timezone incorrectly.

P.S. For future bug reports, please avoid using GIFs/Images to explain issues. Search won't pick up on them, and its a lot of cognitive overhead for people to figure out what the context of the image is, what it is supposed to be showing, and I usually have to watch it multiple times just to see what you're pointing out. Describing the bug using words is far more useful, falling back to an image as supplemental information. 👍🏼

**Comment by nackerr** [comment]
It's set explicitly everywhere to America/New_York. Including the Wings configuration too.. extremely confused here.

**Comment by nackerr** [comment]
Also, yeah sorry about the GIF I was trying to make it easy.

**Comment by schrej** [comment]
Using GIFs is totally fine to demonstrate the issue, but it should always be _in addition_ to a textual explanation.
