### ISSUE TITLE
Select language don't work

### ISSUE THREAD

**Issue by skylide** [pterodactyl/panel#3136]
Panel or Daemon: Panel
 Version of Panel/Daemon: 1.2.2
 Server's OS: debian 10
 Your Computer's OS & Browser: Chrome

Hello, I wanted to create a directory called "fr" in "/var/www/pterodactyl/resources/lang". I copied the "en" folder and I translated into my language in the "fr" folder. Then I rebuild the assets. But by selecting French and validating it. a change has taken place but pterodactyl is still in English. is this normal?

**Comment by trenutoo** [comment]
There's no translation system in place at this moment for the panel. The majority of the text is hard-coded into the panel files with only a small portion of strings being in the /lang/en file. You'd have to edit all the panel files and then [rebuild the panel assets,](https://pterodactyl.io/community/customization/panel.html) together with making a backup since all the changes would disappear on the next panel upgrade.

**Comment by skylide** [comment]
Okay I understand better, and you know when the system will be set up? In the meantime, I'll take a look at the snippets and see how I'm going to do it.

**Comment by trenutoo** [comment]
There's no estimated time for when the translation system would be implemented, it will be released whenever it's ready
