### ISSUE TITLE
Self upgrade doesn't upgrade if you manually download the files. 

### ISSUE THREAD

**Issue by FoksVHox** [pterodactyl/panel#3161]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.3.0
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Windows 10 Student & Brave

**Describe the bug**
I use PHP 8.0.3 and I've followed the installation guide. 

When you run `p:upgrade` and choose "no" when it asks you if you'd like to download the files, assuming that you've downloaded the files manually it won't unpack the panel.tar.gz, it'll run the composer, and migrations, but it won't unpack. 

**To Reproduce**
1. Download the files from GitHub manually using `curl -Lo panel.tar.gz https://github.com/pterodactyl/panel/releases/latest/download/panel.tar.gz` 
2. Run `p:upgrade`
3. Choose "No" when it asks you if you'd like to download the files
4. Say yes to the two next questions
5. It'll run, and then you go to the admin area and see that your panel version hasn't changed. (And assumingly it hasn't upgraded)

**Expected behavior**
It'll unpack the files, and upgrade the panel correctly.

**Comment by matthewpi** [comment]
I believe this is expected behavior, if you use choose not to download the files, it will not extract a local archive, it's expecting you to have already done that.  However, the command will still run the rest of the commands that are generally needed for the upgrade process (`down`, `chmod`, `composer install`, `view:clear`, `config:clear`, `migrate`, `chown`, `queue:restart`, and finally `up`).  If you would like this "already downloaded" behavior, that seems like it would be a feature request, but this behavior seems to be working correctly.

**Comment by FoksVHox** [comment]
> I believe this is expected behavior, if you use choose not to download the files, it will not extract a local archive, it's expecting you to have already done that. However, the command will still run the rest of the commands that are generally needed for the upgrade process (`down`, `chmod`, `composer install`, `view:clear`, `config:clear`, `migrate`, `chown`, `queue:restart`, and finally `up`). If you would like this "already downloaded" behavior, that seems like it would be a feature request, but this behavior seems to be working correctly.

Okay, I just thought it would extract the archive :)
