### ISSUE TITLE
Extend the API to allow for more control and information about servers

### ISSUE THREAD

**Issue by CubitsDev** [pterodactyl/panel#3182]
**Is your feature request related to a problem? Please describe.**
It's not a problem, however it feels like the API provides good information on the servers running, but would be extremely helpful to show more.

**Describe the solution you'd like**
Simply adding the current power state to the result of GET /servers and GET /server/{id} would already be extremely helpful, and to even go the extra mile, additional PATCH routes to change the power state allowing for remote rebooting, etc.

**Describe alternatives you've considered**
Building a mod on to open my own API points, but this seems like something that should be in core functionality, and would be especially useful for remote control of servers.

**Additional context**
[Current API link](https://dashflo.net/docs/api/pterodactyl/v1/#req_84bfb3c0e9084b0db4319b98f41f9e13). Proposed changes are under any /servers endpoint - both client and application

**Comment by trenutoo** [comment]
Power state can be already changed with POST to `/api/client/servers/<uid>/power` and is documented in the API docs that you've linked

**Comment by CubitsDev** [comment]
@Software-Noob Missed that - having that in the application route would also be beneficial for when you want to do it with an app wide API key

**Comment by trenutoo** [comment]
> @Software-Noob Missed that - having that in the application route would also be beneficial for when you want to do it with an app wide API key

New endpoints might be useful, that's up to Dane.

At this moment you can retrieve power state when you perform a resource usage lookup `/api/client/servers/<uid>/resources` where it will be displayed with `current_state`

**Comment by matthewpi** [comment]
The panel is not aware of any server states or resource usage and has to query it from wings.  So adding that information to the `GET /api/client/servers` or `GET /api/client/server/{server}` endpoints isn't going to happen.  The application api is being overhauled with react-admin due to the need of more endpoints and data, however I don't think adding anything resource/status endpoints within access of the application api will happen.

**Comment by DaneEveritt** [comment]
@matthewpi is correct here, adding power state to any of these endpoints is a non-starter due to the way it works. Since that seems to be what this issue is about I'm going to close it. Perhaps we can look into a way to return all of the power details for a single node? If so feel free to edit this issue and we can re-open it if that would do what you need.

**Comment by arturod67** [comment]
We can't do power request with application key (admin)
