### ISSUE TITLE
Orphaned Backups Not Removed

### ISSUE THREAD

**Issue by Brandin** [pterodactyl/panel#3185]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.3.1
* Server's OS: CentOS 8
* Your Computer's OS & Browser: Windows 10 (19042)

**Describe the bug**
A deleted backup file in `/var/lib/pterodactyl/backups/` doesn't cause the entry in the Backups section of the panel to be removed. There appears to be no job when you hit the page to validate which files exist, or to clean these up.

**To Reproduce**
1. Create a backup
2. Access `/var/lib/pterodactyl/backups/`
3. Remove the backup using `rm`
4. Refresh the Backups Tab, immediately, or wait some time, either or

**Expected behavior**
Backup is no longer there if the file is gone, considered orphaned 

**Potential solution routes**
Check files on Backups page load, removes orphaned files; or
Cron task that checks backups table against files, removes orphans

**Comment by DaneEveritt** [comment]
This is by design, you shouldn't be manually deleting backups outside of the Panel and expecting it to know about that. There is no operation that runs through and keeps track of things like that since it really isn't designed to allow for that type of action.

If you're going to be manually deleting archives off the disk outside the realm of the Panel you need to come up with a way to keep your database in sync. I don't consider this a bug.
