### ISSUE TITLE
Use consistent container names

### ISSUE THREAD

**Issue by schrej** [Pterodactyl/Panel#323]
This would greatly simplify connecting to other containers on the same host.

It requires additional logic on container rebuild, should be possible imo though.

**Comment by DaneEveritt** [comment]
So effectively just remove the safety check that keeps the old container until the new one is around.

Should be fine really, since the containers are simply the environment to run the server. If the container is missing and we fail to make a new one, I'm not really sure what should happen (or would happen even).

**Comment by schrej** [comment]
The startup should just fail and throw some error. If container creation does not work something is probably wrong with docker anyways.
