### ISSUE TITLE
Database dump functionality

### ISSUE THREAD

**Issue by joshcannotcode** [pterodactyl/panel#3288]
**Is your feature request related to a problem? Please describe.**
Sometimes users might want to download a .sql/.sql.gz dump of one of their databases. This can be achieved by installing phpMyAdmin, however this might not be suitable for some users.

**Describe the solution you'd like**
I think an integrated solution such as a database "Dump" button would be pretty easy to add and would simply download a compressed archive of their database in .sql.gz format to their machine.

Thanks.

**Comment by i-eat-burgers** [comment]
If it's easy, just add it yourself. Wouldn't say that's "easy to add" at all.

**Comment by joshcannotcode** [comment]
> If it's easy, just add it yourself. Wouldn't say that's "easy to add" at all.

If only I could code 😔

I thought it would be relatively simple as it could be built off the existing MySQL system (the mysqldump command can be used).

**Comment by FoksVHox** [comment]
This is already done via Laravel.
```
php artisan schema:dump [--database [DATABASE]] [--path [PATH]] [--prune]
```
![image](https://user-images.githubusercontent.com/37844753/115887787-917b9100-a452-11eb-8b35-84b1e2125955.png)
https://artisan.page/

**Comment by joshcannotcode** [comment]
> This is already done via Laravel.
> 
> ```
> php artisan schema:dump [--database [DATABASE]] [--path [PATH]] [--prune]
> ```
> 
> ![image](https://user-images.githubusercontent.com/37844753/115887787-917b9100-a452-11eb-8b35-84b1e2125955.png)
> https://artisan.page/

This isn't available to users without CLI access.

**Comment by matthewpi** [comment]
> This is already done via Laravel.
> 
> ```
> php artisan schema:dump [--database [DATABASE]] [--path [PATH]] [--prune]
> ```

That doesn't do what you think it does; that command is used for dumping the schema of Laravel databases in order to speed up running the initial migration process, nothing else.

--

While this feature would be useful for users, it isn't just as easy as calling `mysqldump` from the panel, saving to a file, and giving the user a download URL.  Specifically people dumping multi-GB databases will exceed request timeouts unless configured properly (which isn't a wise idea to do).  The best way to implement this would be to either use the queue worker or an entirely separate microservice which could solely manage dumping (and/or importing) databases.  This process should be done in the background, then give the user the option to download the dump once it is completed.  The other challenge with this feature is running it at scale as many people don't have large amounts of storage or networking overhead to allocate to dumping databases where they run their panel, not to mention if your panel is load-balanced.

**Comment by joshcannotcode** [comment]
> 
> 
> > This is already done via Laravel.
> > ```
> > php artisan schema:dump [--database [DATABASE]] [--path [PATH]] [--prune]
> > ```
> 
> That doesn't do what you think it does; that command is used for dumping the schema of Laravel databases in order to speed up running the initial migration process, nothing else.
> 
> --
> 
> While this feature would be useful for users, it isn't just as easy as calling `mysqldump` from the panel, saving to a file, and giving the user a download URL. Specifically people dumping multi-GB databases will exceed request timeouts unless configured properly (which isn't a wise idea to do). The best way to implement this would be to either use the queue worker or an entirely separate microservice which could solely manage dumping (and/or importing) databases. This process should be done in the background, then give the user the option to download the dump once it is completed. The other challenge with this feature is running it at scale as many people don't have large amounts of storage or networking overhead to allocate to dumping databases where they run their panel, not to mention if your panel is load-balanced.

That's a good point, perhaps the feature would only work with small databases e.g. < 1GB? Or would the size be hard to detect without dumping it in the first place?

**Comment by DaneEveritt** [comment]
I'm not interested in pursuing this feature, there are far too many foot-guns to run into and it really feels like something that hosts need to be figuring out and implementing for their specific setups.
