### ISSUE TITLE
An error occurred in the automatic modification of Egg's configuration file

### ISSUE THREAD

**Issue by echoker** [pterodactyl/panel#3302]
* Panel or Wings:Panel(I think)
* Version of Panel/Wings:1.3.2
* Server's OS:CentOS 7.8
* Your Computer's OS & Browser:Windows 10,Edge

**Describe the bug**
When I run a Minecraft Server,the file such as **server.properties** or **config.yml** will be automatically modified by the **Egg-Configuration-Process Management-Configuration Files**,the **Configuration Files**(Bedrock Dedicated Server) is:

```
{
    "server.properties": {
        "parser": "properties",
        "find": {
            "server-port": "{{server.build.default.port}}"
        }
    }
}
```

after started or restarted the server,the "server-port" will be changed normally,but the **comments will disappear between different configuration items**,like this:

before started a server:

```
...
white-list=false
# If true then all connected players must be listed in the separate whitelist.json file.
# Allowed values: "true" or "false"

server-port=19132
# Which IPv4 port the server should listen to.
# Allowed values: Integers in the range [1, 65535]
...
```

after:

```
...
white-list=false
server-port=25559
...
```

What's more,the **special symbols,Chinese characters, Japanese characters, Russian characters and so on** will be unusual,here is an example:

before:

```
server-name=测试
...
```

after:

```
server-name=\u6d4b\u8bd5
...
```

These errors did not appear in the **0.7.x version** of  panel.

**Comment by parkervcp** [comment]
This is in part due to wings being written in go. runes are treated differently and get converted to the utf char.

**Comment by echoker** [comment]
> This is in part due to wings being written in go. runes are treated differently and get converted to the utf char.

So does this mean that comments can't be preserved?

**Comment by DaneEveritt** [comment]
Correct, the library we use for parsing the file does not preserve comments. I have no intention of dealing with changes to that either, sorry.

As for the characters being switched to their UTF-8 sequence, that has been a _constant_ back and forth and I'm not changing how it works currently. There are multiple different issues that have been opened and closed and looked into. There is literally no way for me to correctly handle this because some games want the raw sequence, other games want the actual character, and in the code it would just be stupid complex to keep track of what character should be what based on what the value was when the file was read.
