### ISSUE TITLE
Can’t create an server anymore with the external API

### ISSUE THREAD

**Issue by LogischJo** [pterodactyl/panel#3390]
**Background (please complete the following information):**

* Panel or Wings:Panel
* Version of Panel/Wings:1.4.1
* Panel Logs:No errors in
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: API 

**Describe the bug**
My issue is that I can’t create an server with the pterodactyl api anymore. This is the issue I get 

![3F04157C-1A73-4E71-BB4D-ACE7030375F5](https://user-images.githubusercontent.com/66436499/120539819-45742280-c3e8-11eb-9036-b0271c3d233a.jpeg)

I checked every node I have about the automatic allocation, which is enabled, I checked the ram limit etc and every node have enough ram + disk etc and enough Allocations aswell. 

Panel: PHP Version 7.4

**To Reproduce**
Steps to reproduce this behavior:

1. Delete an Node in the panel
2. Try to create an server with the API

**Expected behavior**
It should, like before just create the server.

**Comment by DaneEveritt** [comment]
There is not enough information here to reproduce this issue. Additionally, there are hundreds if not thousands of people running this software using the API to create servers, nothing has changed in the last month that would suddenly cause it to no longer work.

Most likely you're passing invalid details to the API, or are overlooking something causing the automated deployment process to be unable to actually find a node, but you've not provided enough information for me to take a guess otherwise.
