### ISSUE TITLE
[Suggestion] Option to make a backup of the complete dashboard.

### ISSUE THREAD

**Issue by Ferks-FK** [pterodactyl/panel#3420]
**Is your feature request related to a problem? Please describe.**
A somewhat strange feature, but it can be useful in some cases.

**Describe the solution you'd like**
It would be interesting for the panel to support a backup of itself, so if you have to do something on the machine where the panel is running, like an update, (or anything like that) ensure that the panel won't be harmed.
Maybe a button? I don't know, but something that backs up the entire dashboard, or the things it needs to run, in case something goes wrong.

**Describe alternatives you've considered**
I've tried to restore a backup of the dashboard database, and the .env file to a fresh install, but to no avail.

**Additional context**
How to do this?
I think creating a command that is used inside the panel directory (var/www/pterodactyl), or some button on the front-end admin panel.

**Comment by trenutoo** [comment]
This feels like something you should manage on your system itself instead of relying on the panel to do it. You dump the database and backup the .env file. After that, you import the database and .env file to restore the data. 

Apt updates and so forth don't touch the panel itself, and any backups would be of no use because what that would do is possibly break the dependencies (ex. PHP, docker) and not the database or files.

**Backup data**
`mysqldump -u root -p --opt panel > /var/www/pterodactyl/panel.sql && tar -zcvf panel-backup.tar.gz /var/www/pterodactyl`

**Importing data back**
`mysql -u root -p panel < panel.sql && tar -xvf  panel-backup.tar.gz -C /var/www/pterodactyl`

In the examples above, it would compress the whole pterodactyl folder. You only need the `.env` file if you don't have any panel modifications. The backup archive would be placed in the directory from where you initiated the command.

**Comment by Ferks-FK** [comment]
I understand, but now there is a part that for me is very difficult to get through.
On the second machine I have, I install pterodactyl, to configure everything needed (PHP, docker, domain)
After I have the second machine with a dashboard installed and working, I get all the backups from machine 1, and try to transfer to machine 2.
And that's where several problems come up

First:
Different domains.
assuming machine 1 has the domain ptero1.domain.com
And machine 2 has the ptero2.domain.com domain, there is a certain incompatibility between the domains in the files of the two machines.
Why SSL certificates that are in the directory (/etc/letsencrypt/live/)
They will own the different domains (machine 1 and machine 2).
And it's no use renaming the machine's domain 2 to ptero1.domain.com, it just caused more problems for me.

This is where I can't understand.
Regarding the backup of the panel and its databases, I do it without any problem, but getting the panel from machine 1 to work on machine 2 with the same domain is very difficult.

**Comment by trenutoo** [comment]
This post is not relevant to the original suggestion or something that a panel backup would resolve. Backup creates a copy of your existing data, it has nothing to do with reconfiguring it for your new machine IP or domain.

What you're asking is migrating the panel to a different machine, not creating a backup. You have to update the DNS records, web config virtual host/server block in `pterodactyl.conf`, regenerate the certificates, update APP_URL in the `.env` file, and update your Wings `config.yml` to match the new panel domain.
