### ISSUE TITLE
Unable to start pteroq.service

### ISSUE THREAD

**Issue by OceanTechnic** [pterodactyl/panel#3422]
* Panel or Wings: Panel
* Version of Panel/Wings: 1.4.2 needs to be 1.4.2 **(No error on 1.4.1!!)**
* Panel Logs: Clean
* Wings Logs: /
* Server's OS: Ubuntu 20.04LTS **This happend on 3 totally different machines 2 running Ubuntu 20.04LTS and 1 Running Debian10**
* Your Computer's OS & Browser: Windows 10 NT & Opera GX and Google Chrome Canary

**Describe the bug**
Unable to start pteroq.service or it will start for 2 seconds and then it will crash _as seen on picture_
![image](https://user-images.githubusercontent.com/63557993/122652700-5ccd4280-d140-11eb-97f2-a564ca050428.png)

**To Reproduce**
Install the pterodactyl as written in guide
Try to restart pteroq.service

**Expected behavior**
This error
![image](https://user-images.githubusercontent.com/63557993/122652700-5ccd4280-d140-11eb-97f2-a564ca050428.png)

**Comment by VottusCode** [comment]
Well, it says "Permission denied", indicading the application doesn't have permissions in the filesystem; given the `The stream or file "/var/www/pterodactyl/storage/logs/laravel-XXX.log"`, my best guess is that the application doesn't have enough permissions to write into a log file, this could be because of the following:

- You did not set the correct permissions for the `/var/www/pterodactyl` folder.
  - Fix: See https://pterodactyl.io/panel/1.0/getting_started.html#set-permissions
- Your webserver does not run under the same user
  - Fix: Check your webserver config (nginx/apache/caddy, etc..) and make sure the user is `www-data`; if it isn't, either change it to `www-data` or run the commands from above link but change `www-data` to your user (the first solution is recommended, however depending on why is your webserver running under a different user you may not be able to do that)
