### ISSUE TITLE
Files present in egg deny list, still allows end users to download them.

### ISSUE THREAD

**Issue by notAreYouScared** [pterodactyl/panel#3441]
**Background (please complete the following information):**
* Panel or Wings: Wings
* Version of Panel/Wings: 1.4.4

**Describe the bug**
The file deny list currently protects files in the list from being edited, moved, uploaded, and renamed. But not downloaded.

**To Reproduce**
1. Add file to deny list.
2. Download.

**Expected behavior**
Files in the egg deny list shouldn't be allowed to be downloadable.

**Comment by DaneEveritt** [comment]
You can still view their contents on the Panel, correct? If that is the case there is no reason to prevent downloading.

**Comment by notAreYouScared** [comment]
Correct, the file in question is a executable, viewing the contents are kind of useless cause it just shows a bunch of?s and diamonds

**Comment by DaneEveritt** [comment]
~Since you are one of the first people to accurately describe that use case I'll just turn this into a feature request. Notably if you give a user SFTP access there will still be nothing stopping them from downloading a file, so I'll make sure the permission makes that abundantly clear.~

Thinking about this more, that isn't even a solution. Because the read permission allows you to get the file contents disabling download permissions will solve nothing. A user could very easily use the API to fetch the contents of the file and pipe it into a file on their machine of choice.

If you give a user permission to read files they're going to be able to download them, there is no such thing as a difference between read/download other than how the UI behaves (or making it ever so slightly more hard for someone that wants the file to get it).
