### ISSUE TITLE
Redundant Port Range Option

### ISSUE THREAD

**Issue by regulad** [pterodactyl/panel#3448]
**Background (please complete the following information):**

* Panel or Wings: Panel
* Version of Panel/Wings: `Panel@1.4.1`, and up.
* Panel Logs: Not needed.
* Wings Logs: Not needed.
* Server's OS: `5.4.0-74-generic`
* Your Computer's OS & Browser: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0` 

(Just sharing my user agent, it's not important)

**Describe the bug**

![image](https://user-images.githubusercontent.com/52430642/123862408-4ff5df00-d8f6-11eb-8905-c7443f328cdf.png)

Next to the option to enable automatic allocation creation, there are options to specify a port range.

This option is redundant and has no effect, since the ports used are those available to the node the server is on.

**To Reproduce**

1. Go to "Settings" under "Basic Administration".
2. Go to the "Advanced" tab.
3. See the "Automatic Allocation Creation" section. 

**Expected behavior**

No option to declare a port range should be given, or the option should be per-node.

#### Confirmed by @Software-Noob, see https://discord.com/channels/122900397965705216/658550982975946762/859509048121884713

**Comment by matthewpi** [comment]
Your choice of wording for describing this issue is poor.  The option is not redundant, that would imply that the option is not used and completely avoided.  The port range is only used if no existing allocation exists; within the code, this is intentional behavior, but according to the description of the fields from your screenshot, it's not.  There are two solutions I see for this, the first one being to change the logic to only look for existing ports in that range or add a toggle denoting if existing ports out of that range should be included.

**Comment by matthewpi** [comment]
Closing due to lack of response, the settings page is being rebuilt in v2 so this should be revisited at a later date.
