### ISSUE TITLE
Allow for easy upgrade of Wings

### ISSUE THREAD

**Issue by FoksVHox** [pterodactyl/panel#3491]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Currently we’ve the `php artisan p:upgrade` command, which makes it easy to upgrade the panel, however, not wings. This can cause that the panel wont work due to an old version of Wings. So if we got an easy way to do this, it could potentially cut down some “bug” reports.

### Describe the solution you'd like.

I propose that we could get one of two solutions.

## Solution A
That there is a button on the admin side of the panel got a “Upgrade” section or something like it.

This would be dependent on react-admin… 

**What would this require?**
- Endpoints getting added to Wings to receive update orders
- Endpoints getting added to the Panel for report of successful/unsuccessful update attempt

## Solution B
That Wings got an `upgrade` command that would run the steps to download and finish the update.

**What would this require?**
- That a Cobra got added.

### Differences
The main difference between A and B is that one of them is giving a better UX to the users.

### Additional context to this request.

None

**Comment by matthewpi** [comment]
Let's not make it this easy for wings to break itself.  I don't see how a wings upgrade command is any better than the 3-4 command upgrade from the docs.  While the panel idea is neat, it's a lot of work for very little return.  It would be much better for people to develop their own workflows and solutions such as using Ansible.  The panel upgrade command was added to more easily handle running all the php artisan commands properly and in order, rather than making updating a one command process.  This feature also would break any modified version of wings.
