### ISSUE TITLE
Unarchive does not keep empty folders

### ISSUE THREAD

**Issue by ghost** [pterodactyl/panel#3502]
### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.

### Current Behavior

Unarchiving a zip doesn't keep/create empty folders

![Screenshot 2021-07-26 025258](https://user-images.githubusercontent.com/43488129/126970072-5b26c4ff-6ede-42ef-a568-3627ca67eec8.png)
![Zip](https://user-images.githubusercontent.com/43488129/126970075-af5220d0-d05f-4660-8e9a-258d67392cb3.gif)

### Expected Behavior

All folders, empty or not, are present on the panel after an unarchive.

### Steps to Reproduce

1. Upload a ZIP file with empty folders in it.
2. Unarchive the ZIP on the panel
3. Observe that the empty folders are missing.

### Panel Version

1.4.2

### Wings Version

1.4.4

**Comment by hwalker928** [comment]
I seem to recall Windows doesn't even let you create .zip files with explorer with empty folders. (I'm on mobile so cannot double check)

**Comment by ghost** [comment]
> I seem to recall Windows doesn't even let you create .zip files with explorer with empty folders. (I'm on mobile so cannot double check)

Windows's built-in compression doesn't let you create one, but applications such as 7zip and WinRAR do.

**Comment by matthewpi** [comment]
This is intentional behavior.  Empty folders won't be created when extracting or be added to any archives (such as creating an archive with the file manager, server backup, server transfer, etc).

If you need an empty folder to be preserved, add a file within it (such as a `.keep` or `.hold`).  This isn't behavior that will be changed.
