### ISSUE TITLE
When logging in, if you enter incorrect credentials, the user box clears itself instead of remembering the last name

### ISSUE THREAD

**Issue by xyeLz** [Pterodactyl/Panel#363]
The subject pretty much tells it all, but when logging in, if you enter incorrect credentials, the user box clears itself instead of remembering the last name that was entered. The code appears to be trying to get it to remember the last username, but for some reason it's not doing so.

**Comment by DaneEveritt** [comment]
The form is submitting [`user`](https://github.com/Pterodactyl/Panel/blob/develop/resources/themes/pterodactyl/auth/login.blade.php#L50) as the field name, but it seems [`this function`](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php#L124-L135) is looking to return `email` as the field.

Should be easy enough to override `username()` to return `user` rather than `email`.

**Comment by schrej** [comment]
why didn't you just do that yourself? 😅

**Comment by DaneEveritt** [comment]
I had to leave for a bit, and figured someone could probably do it before I got back.
