### ISSUE TITLE
Codemirror undo history is not cleared when changing files without saving

### ISSUE THREAD

**Issue by PadowYT2** [pterodactyl/panel#3656]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

When you try to ctrl+z, it could copy the file that u ctrl+z before

### Expected Behavior

It should copy that file

### Steps to Reproduce

1. Go to a file
2. Type something
3. Click `Ctrl+z`
4. Open another file without saving
5. Click `Ctrl+z`

### Panel Version

1.6.2

### Wings Version

1.5.1

### Error Logs

Panel logs - (no logs, `tail: cannot open '/var/www/pterodactyl/storage/logs/laravel-2021-09-28.log' for reading: No such file or directory`)

**Comment by PadowYT2** [comment]
Heres a video

https://user-images.githubusercontent.com/71085027/135085507-75f1bbac-4536-4bdc-b7ff-86694ba062c5.mp4

**Comment by superhealing** [comment]
So far to explanation for people didn't understand english.
The user want to change the name that sit on header when the command of CTRL+Z (eg, go ops and go to another file, ctrl+z, the file go to ops, but the name on header stay the "another file".)
@PadowYT2 your issue is not related to panel, and nor idea. Go and complain the main provider/developer.

**Comment by RTK23-dev** [comment]
Well isn't Ctrl Z is meant to undo changes

**Comment by YusufYaser** [comment]
> Well isn't Ctrl Z is meant to undo changes

yeah but it is meant to clear the undo history when you open another file.
like you are editing File1.yml, after that you go to File2.yml without saving and try to undo it will show File1.yml contents

**Comment by matthewpi** [comment]
This is most likely due to the modifications you have made to your panel.  They seem to update the content of the editor without resetting the state.  This seems very unlikely to happen on stock Pterodactyl (I cannot reproduce it on v2) due to the editor being re-rendered entirely when switching files.
