### ISSUE TITLE
New feature to prevent users from deleting allocated additional ports

### ISSUE THREAD

**Issue by AmoxAmox** [pterodactyl/panel#3703]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Added an option to prevent a specific server from making changes to its assigned ports.

### Describe the solution you'd like.

An option on the server creation page that can be checked and prevent the user from making any changes to the ports such as "remove them, change the main port".

### Additional context to this request.

This option will help admins a lot **(especially if there are a lot of servers)**, some users delete their ports by mistake or change the main port which may prevent the server from working normally with the original port order.

**Comment by DaneEveritt** [comment]
I think to avoid additional code complexity and more feature toggles all over the place, this probably makes the most sense to just disable the deletion option when a server is set to not allow any additional allocations.

This would mean you can just set the additional allocations to `0` for a server and manually assign them as an admin (or via the API as normal) and the user just can't remove them. I'm re-tagging this as a "bug" since it doesn't make sense to allow a user to delete allocations if they can't also re-add them anyways.
