### ISSUE TITLE
Implementing Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by Pankraz01** [pterodactyl/panel#3737]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Implementing Google's new Analytic Tool to use the `G-` codes instead of the `UA-` Universal Analytics codes 

### Describe the solution you'd like.

![grafik](https://user-images.githubusercontent.com/19345513/140894252-1c4016ef-86ce-45a7-9945-a06e998dfc8c.png)
Make this Possible here.

**Comment by notAreYouScared** [comment]
While this would be idea the package we use currently has no plans to support the new and old at the same time due to the complexity of Google tags. With that being said we would have to support one or the other it seems or make some type of logic to see what key the user puts in and load the correct one accordingly.

@DaneEveritt I haven't dabbled in the GA world in a while to know what the heck tags are in Google analytics... I do know changing to just ga4 would be a breaking change for many users that use it. 

@Pankraz01 it does seem you can still make a universal analytics code like this guy did 
![Screenshot_20211109-100425_Chrome](https://user-images.githubusercontent.com/1757840/140950187-658ff02d-32d0-4e98-bc15-959efba82c1a.jpg)

**Comment by DaneEveritt** [comment]
To be honest I just don't care enough about Google and their ridiculous tracking to put any effort into keeping up with their spyware. :)

So I'm not changing anything, and yes it would be a breaking change.
