### ISSUE TITLE
Wings requests being blocked by Chrome CORS for private networks (RFC1918) Policy

### ISSUE THREAD

**Issue by ncopeland78** [pterodactyl/panel#3863]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Starting with Chrome 92 HTTP requests to private network resources are being blocked which shows Nodes to be offline which in reality they are not actually offline. Nodes are actually online and connected but show offline in the panel as shown in the attached screenshot. Top is Chrome and the bottom is Safari. Ports are also open as well when checked with two different sources and running nmap from the wings instance. 

This also prevents file uploading via the upload button or drag and drop. You are presented with a "Network Error" banner message at the top of the file manager page. 

This is due in part to the [https://developer.chrome.com/blog/private-network-access-update/?utm_source=devtools](url) CORS for private networks (RFC1918) flag that was added as part of Googles new policy. Need to pass `Access-Control-Request-Private-Network: true` header to fix it

![Screen_Shot_2021-10-30_at_12](https://user-images.githubusercontent.com/49995575/148648023-cbb8e2de-4e66-4dbc-8931-b8a4175109a0.png)
 

### Expected Behavior

Nodes should show that wings is connected and online in the node section of the panel. when in fact the ports are open and service is verified as started. 

### Steps to Reproduce

This issue presented itself when Chrome was updated to Chrome 92+ and the [chrome://flags/#block-insecure-private-network-requests](url) was set to default or enabled. 

@Software-Noob was able to replicate this issue and should be able to provide further information on how he was able to reproduce it since he did not have this issue from the beginning. It was a constant issue for me from when I upgraded. 

### Panel Version

1.6.6

### Wings Version

1.5.3

### Error Logs

```bash
https://ptero.co/egejuqepox

http://bin.ptdl.co/w1hs0
```

**Comment by TheDarthFather** [comment]
I have the same problem since last evening. I updated the wings config to disable crash detection ... and restarted wings.
I belive I also changed the subdomain of wings to be the same as the pannel before in the day (as I realised I dont need different ones) ... but worked after for a few hours.
I am behind a wireguard VPN and a nginx .... and I have 2 reverse proxy rules for 443 and 8080. 
Any quick fixes / workarounds ? 

`nodes:1 Access to XMLHttpRequest at 'https://mysub.domain.com:8080/api/system' from origin 'https://mysub.domain.ws' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by trenutoo** [comment]
> `nodes:1 Access to XMLHttpRequest at 'https://mysub.domain.com:8080/api/system' from origin 'https://mysub.domain.ws' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Your issue is not the same as reported here. Please use the Discord server for configuration issues, as your Wings are not reachable.

**Comment by TheDarthFather** [comment]
> Your issue is not the same as reported here. Please use the Discord server for configuration issues, as your Wings are not reachable.

Thank you!
PS: I did, but discord is quite challanging :( .. if you dont get the right person at that moment ... or the next moment ... :)
