### ISSUE TITLE
Custom scrollbar does not work on Firefox

### ISSUE THREAD

**Issue by Jelcoo** [pterodactyl/panel#3868]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

The custom scrollbar does not work on Firefox browser. 

Firefox:
<img width="960" alt="Yqcame4P3J" src="https://user-images.githubusercontent.com/53396500/148696785-7e06f341-e635-47cd-9cc7-f71edd3052cf.png">

Edge:
<img width="960" alt="msedge_K7g7cKrWCL" src="https://user-images.githubusercontent.com/53396500/148696803-05cca535-061b-4d5b-90f2-91cf7ffa519a.png">

### Expected Behavior

The scrollbar should work on all browsers

### Steps to Reproduce

1. Download Firefox browser
2. Open the panel
3. Go to a page with a scrollbar

### Panel Version

1.6.6

### Wings Version

1.5.3

**Comment by yesBad** [comment]
Sorry what exactly doesn't work?

https://user-images.githubusercontent.com/87938689/148697139-d636c984-ee41-4718-8748-fd5e2514d0c1.mp4

**Comment by yesBad** [comment]
What doesn't work?

https://user-images.githubusercontent.com/87938689/148697220-985441b6-f0d8-4a76-8ea1-a4ea056224d7.mp4

**Comment by parkervcp** [comment]
As a Firefox user I can say this works fine for me.

**Comment by Ferks-FK** [comment]
> custom scrollbar

_custom scrollbar_

**Comment by Ferks-FK** [comment]
> What doesn't work?
> 
>  LOhU0sbJY5.mp4

_custom scrollbar_

**Comment by Ferks-FK** [comment]
> ### Current Behavior
> The custom scrollbar does not work on Firefox browser.

The same for me.

**Comment by yesBad** [comment]
> > ### Current Behavior
> > The custom scrollbar does not work on Firefox browser.
> 
> The same for me.

I don't see what's broken?

**Comment by yesBad** [comment]
Oh you mean the custom scrollbar doesn't show...

Could've phrased it better imo

**Comment by matthewpi** [comment]
![image](https://user-images.githubusercontent.com/26559841/148698092-bec799ef-f1da-438d-b522-0761e839bcdb.png)
*That is not a custom scrollbar set by Pterodactyl, that is how Firefox scrollbars look on Linux.*

Firefox doesn't support custom scrollbars because they not currently standardized.
https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars (while based on a standard, it is still experimental and is only implemented in Firefox, not to mention it lacks any decent styling options)

Because of this, there is nothing we can do as this is expected behavior.  If or when custom scrollbars become standardized, it will be implemented, until then there is no point in tracking this.
