### ISSUE TITLE
Allow setting `PID` value in the settings page of nodes page

### ISSUE THREAD

**Issue by FoksVHox** [pterodactyl/panel#3871]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I like to see a possibility to change the PID limit from the panel, much like how Pterodactyl does it with the maximum file upload, storage, storage overallocation, memory, memory overallocation etc.

### Describe the solution you'd like.

This should be done on the v2 branch. 
Adding a way to provide the PID limit, by a field input. The limit shouldn't be allowed under the default limit.

### Additional context to this request.

#3845

**Comment by matthewpi** [comment]
We are not going to be adding any individual options to configure nodes unless absolutely necessary.  While this suggestion is good, this applies to every option in the wings config.  Dane and I have briefly discussed having Wings load the YAML config from the Panel, and just leaving the required configuration options in order to authenticate and fetch the config from the Panel on every node.  This would also make it possible to specify a custom default config for every node and add "global options" like container registry credentials.

This is something that needs to be further discussed in a separate issue.  For now, I'm going to close this.

@DaneEveritt
