### ISSUE TITLE
Wings memory leak problem

### ISSUE THREAD

**Issue by wyywang** [pterodactyl/panel#3882]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

Hello everyone, I found that wings has a memory leak problem.has anyone also encountered the same?
![image](https://user-images.githubusercontent.com/17702144/149451703-f50a1f27-cba6-4b95-9316-b02bd472efe8.png)
![image](https://user-images.githubusercontent.com/17702144/149451718-2482e91c-a44e-4147-8f93-5cd8e7738ad6.png)
I used pprof to discover the presence of wings in the installation process.

The Realease of 1.5.3 is also the same problem,I build a develop version to use pprof to find the problem.
It looks like the installprocess make lots of gc which is taking many CPU times and big memory use.
![image](https://user-images.githubusercontent.com/17702144/149452008-c4346303-d661-4e1d-bb9a-e8e5fffecfd0.png)

thanks u a lot!

### Expected Behavior

Memory used.

### Steps to Reproduce

Just waiting..

### Panel Version

1.6.6

### Wings Version

1.5.3(also the develop)

### Error Logs

```bash
https://ptero.co/gycujahywa
```

**Comment by matthewpi** [comment]
Looking at `ScanReader`, I found this ([system/utils.go#L74](https://github.com/pterodactyl/wings/blob/develop/system/utils.go#L74)), all the currently processing lines are being split which will allocate a slice to fit all of them, even though we just end up passing them one by one into a callback.

To optimize that, I came up with this, by using a scanner rather than splitting we should be able to more efficiently use memory, this change affects both the installation output and regular console output.

<details>
  <summary>Click to expand (diff)</summary>

```diff
diff --git a/system/utils.go b/system/utils.go
index 785b505..8476351 100644
--- a/system/utils.go
+++ b/system/utils.go
@@ -8,7 +8,6 @@ import (
 	"fmt"
 	"io"
 	"strconv"
-	"strings"
 	"sync"
 	"time"
 
@@ -43,9 +42,9 @@ func ScanReader(r io.Reader, callback func(line string)) error {
 	// Avoid constantly re-allocating memory when we're flooding lines through this
 	// function by using the same buffer for the duration of the call and just truncating
 	// the value back to 0 every loop.
-	var str strings.Builder
+	buf := &bytes.Buffer{}
 	for {
-		str.Reset()
+		buf.Reset()
 		var err error
 		var line []byte
 		var isPrefix bool
@@ -57,7 +56,7 @@ func ScanReader(r io.Reader, callback func(line string)) error {
 			// in line with that it thinks is the terminal size. Those returns break a lot of output handling,
 			// so we'll just replace them with proper new-lines and then split it later and send each line as
 			// its own event in the response.
-			str.Write(bytes.Replace(line, cr, crr, -1))
+			buf.Write(bytes.Replace(line, cr, crr, -1))
 			// Finish this loop and begin outputting the line if there is no prefix (the line fit into
 			// the default buffer), or if we hit the end of the line.
 			if !isPrefix || err == io.EOF {
@@ -71,8 +70,9 @@ func ScanReader(r io.Reader, callback func(line string)) error {
 		}
 		// Publish the line for this loop. Break on new-line characters so every line is sent as a single
 		// output event, otherwise you get funky handling in the browser console.
-		for _, line := range strings.Split(str.String(), "\r\n") {
-			callback(line)
+		s := bufio.NewScanner(buf)
+		for s.Scan() {
+			callback(s.Text())
 		}
 		// If the error we got previously that lead to the line being output is an io.EOF we want to
 		// exit the entire looping process.
```

</details>

---

I still need to figure out how to optimize the event bus, how to bypass the event bus, or both.

---

Any changes I make to wings for this issue will be available on the [issue/3882](https://github.com/pterodactyl/wings/tree/issue/3882) branch

**Comment by wyywang** [comment]
thank u for your hard working!! ;)

**Comment by wyywang** [comment]
thanks! :))
