### ISSUE TITLE
Add Cyrillic support in console

### ISSUE THREAD

**Issue by kistanov96** [pterodactyl/panel#3940]
### Current Behavior

When Cyrillic characters are used, the console does not read them and, accordingly, does not send them to the server.

![image](https://user-images.githubusercontent.com/13833222/152545823-6ac69c8e-3be2-48e8-bf08-a10d4968aebc.png)

### Expected Behavior

I want Cyrillic support in the console

### Steps to Reproduce

Send a Cyrillic character to the console

### Panel Version

1.7.0

### Wings Version

1.6.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by trenutoo** [comment]
That looks like an issue isolated to the source engine. I can't replicate this on non-source games, e.g., Minecraft or Rust. Does it work natively when you host source servers without Pterodactyl?

**Comment by FC-FailCoder** [comment]
99% sure it is an issue with source, not the panel. Loaded up a LAN csgo server "the long way" (through SteamCMD) that one percentage is because I used Windows. All Cyrillic text came up as question marks, I did not try through Sourcemod (sm_say).

Pretty sure it comes down to the encoding part as when typing Cyrillic in game it shows fine, but not translated correctly when looking on the server chat logs.
