### ISSUE TITLE
Getting node information timeout

### ISSUE THREAD

**Issue by TreeHD** [pterodactyl/panel#4023]
### Current Behavior

While I visiting 
https://panel.xxxxx.net/admin/nodes/view/5
I facing https://panel.xxxxxx.net/admin/nodes/view/5/system-information Timeout in console (JQuery Request)
![image](https://user-images.githubusercontent.com/23317010/160183855-8c628547-753b-4b94-a691-309f1c2cecfd.png)
But While I open  https://panel.xxxxxx.net/admin/nodes/view/5/system-information in browser,it works
But aleast need 5-8sec 

Also all of node directly access from my browser is working
![image](https://user-images.githubusercontent.com/23317010/160184963-e02711f7-7a8b-4822-9c55-5d716ce87da1.png)

### Expected Behavior

Information could be read normally

### Steps to Reproduce

visiting admin/nodes/view/5

### Panel Version

1.7.0

### Wings Version

1.6.1

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by TreeHD** [comment]
I use laravel debugbar to view it

I saw that `Illuminate\Log\Events\MessageLogged` using about 5s to complete it
![image](https://user-images.githubusercontent.com/23317010/160233685-c429a796-0fa7-429a-97b5-dd3214b08b40.png)

Anyone got this problem?

**Comment by DaneEveritt** [comment]
Seems like a slow API response from Wings since all that endpoint does is act as a proxy:

https://github.com/pterodactyl/panel/blob/14cc98f75f405fccf9353e8c989c9a33ffe9c1fd/app/Repositories/Wings/DaemonConfigurationRepository.php#L16-L25

The 5 seconds to log the warning is either including the whole request time for some reason, or whatever system you're using for writing logs is struggling to perform. That isn't a bug in Pterodactyl, and this specific issue seems more probable to be a system bug.

You can try increasing the timeout here from 5 seconds to something higher.

https://github.com/pterodactyl/panel/blob/develop/resources/views/admin/nodes/view/index.blade.php#L157
