### ISSUE TITLE
Too many requests on full server startup

### ISSUE THREAD

**Issue by eduardopilati** [pterodactyl/panel#4042]
### Current Behavior

I have a CentOS 8 Server with some VMS:
VM with web server: Apache / PHP / Pterodactyl Panel
VM with minecraft servers: Wings + mine servers

If I reboot entire CentOS server the panel cannot connect to wings and spam this error on browse consele:
bundle.5cdda223.js:1 JWT validation error from wings: Error Event [9138549e-7bca-4cc2-9960-0dc24303dbf7]: jwt: created too far in past (denylist)

The problem only stops happening if I restart minecraft VM

### Expected Behavior

On full server restart both VMS starts gracefully and the panel can connect to wings

### Steps to Reproduce

Described on current behavior

### Panel Version

v1.6.6

### Wings Version

1.5.3

### Games and/or Eggs Affected

all servers, paper an forge

### Docker Image

ghcr.io/pterodactyl/yolks:java_17 and ghcr.io/pterodactyl/yolks:java_8

### Error Logs

```bash
https://ptero.co/uqumyqigow
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by eduardopilati** [comment]
Updated to latest versions and problem persists:
Panel 1.7.0
Wings: 1.6.1

**Comment by DaneEveritt** [comment]
This isn't anything to do with the number of requests, something is wrong with the clocks on your systems, thus leading to: `jwt: created too far in past (denylist)`.

**Comment by jportner** [comment]
Apologies for replying to a long closed issue, but I ran into this today and found a solution, so I thought it was worthwhile to leave a comment for other folks in the future who run into this --

### Problem

I've run into this twice now, right after a system reboot. If I access a Server in the Pterodactyl Panel, the page just shows a spinner and nothing happens -- the browser is spamming requests to generate a new JWT, and the console is filling up with these "jwt: created too far in past" errors.

Oddly enough, everything I saw in my browser console -- both the network request and decoding the JWT response -- indicated that my system and Pterodactyl have synchronized time.

It turns out that when Wings starts up, it generates a "boot" timestamp". Later when it validates a JWT, it uses that timestamp to check whether the JWT is valid or not:

https://github.com/kristiangarcia/wings/blob/3b22cbdb6bf123d31836a6687178494f6ecc71cb/router/tokens/websocket.go#L74-L78

In my terminal, I ran `service wings status` and the start time of the service was in the future:

```
Active: active (running) since Mon 2025-07-28 20:57:37 EDT; 3h 28min left
```

I restarted the service and re-ran the command to check the status, and that temporarily fixed the problem:

```
Active: active (running) since Mon 2025-07-28 17:29:38 EDT; 2s ago
```

However, that didn't explain why this service started in the future.

I found this StackExchange answer that gave me the answer, my hardware clock and OS clock are out of sync: https://unix.stackexchange.com/a/336029

I ran `timedatectl` and it showed the right time, but `hwclock` showed the wrong time:
```
2025-07-28 21:33:59.948814-04:00
```

I guess when Linux boots up, the OS clock starts out using the hardware clock, but shortly afterwards it syncs with internet time servers. In other words, Wings started before the OS time changed.

### Solution

I ran `hwclock -w` to synchronize the hardware clock with my OS clock, and now the `hwclock` command shows the correct time:

```
2025-07-28 17:34:34.600044-04:00
```

The machine I installed Pterodactyl Panel/Wings on is currently running Linux Mint, but it used to run Windows, and I think this might have caused the problem.
