### ISSUE TITLE
Email not sending properly

### ISSUE THREAD

**Issue by vlssu** [pterodactyl/panel#4148]
### Current Behavior

Except the 'test email' on the settings page is normal, a series of content such as resetting passwords and inviting users cannot be sent normally.
I use Outlook mailbox.

### Expected Behavior

To reset passwords or invite users, etc., should send emails to users normally.

### Steps to Reproduce

In the User Management section of the Users page, add users
Or click Reset Password when you are not logged in

### Panel Version

7197d28815cc39b9da5830f4c20b0c597c71579d

### Wings Version

1.6.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Goksi** [comment]
More of a [discord](https://discord.gg/G5PV56zm) question and misconfiguration then bug with software

**Comment by vlssu** [comment]
> More of a [discord](https://discord.gg/G5PV56zm) question and misconfiguration then bug with software

![image](https://user-images.githubusercontent.com/43847794/174552795-fd5ec5ee-0a36-4b64-9dd5-4d33e3d71161.png)
Mainly, he suggested that it was sent successfully, but it was not actually sent, and the "test mailbox" was sent normally.

**Comment by trenutoo** [comment]
This would be a duplicate of #4024 #3669 #3645 #3570 and not a bug in the software, but rather an issue with your [queue worker](https://pterodactyl.io/panel/1.0/getting_started.html#create-queue-worker), unless you're able to provide more error logs proving otherwise - right now you've provided none. The manual test doesn't use the queue worker and instead executes the task when you click test, hence why it works.

>  I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

Please use the Discord server or discussions tab for configuration issues.

**Comment by vlssu** [comment]
It's solved, thanks for the reminder
