### ISSUE TITLE
Feature request - Force node creation

### ISSUE THREAD

**Issue by jffz** [Pterodactyl/Panel#415]
Some DNS providers have really slow replication and it's annoying to be stuck waiting for the entry to replicate before being able to configure the node.

A force create button could be nice here.

**Comment by DaneEveritt** [comment]
This comes down to the DNS servers you're using on your host. Unfortunately that check must be there because of the number of users who enter non-resolvable IPs or Domains in that field.

I *need* to be able to resolve the domain back to an IP in order for everything to function, there is just no way around it. You can always enter an IP and then later switch it back to a FQDN once everything resolves.
