### ISSUE TITLE
Better Graphs

### ISSUE THREAD

**Issue by KaspianDev** [pterodactyl/panel#4224]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would love to see chart makeover, current charts have no animation, no hover tooltip like other panels have.

### Describe the solution you'd like.

Use a different chart library or add animation to existing one. With hover tooltips, animation, maybe zooming?

### Additional context to this request.

I tried doing animations myself, but they look odd in chart.js.

**Comment by DaneEveritt** [comment]
Animations cause browser performance issues, not to mention they look really bad because we're trying to build a live graph. This requires hiding data points at each end and then scrolling the vector across a viewable area, which isn't really something I feel is important enough to go through the effort of doing.

Static updates work fine and display the relevant data. In addition, the tooltips I've tried a few times and they just don't work at all because of how fast the graph is updating.

Its much like why viewing CPU/Memory usage on macOS/Windows doesn't have tooltips or fancy animations on their respective graphs either, and you just look at the sidebars and active values to determine what is going on.

The tooltips only make sense if you're viewing historical static data.

**Comment by KaspianDev** [comment]
What about just animating the transition between updates? That's what I mostly see other panels do. I don't think it's super heavy for the client.

And actually my system monitor has animated graphs 😂. I'm on gnome.

**Comment by DaneEveritt** [comment]
> This requires hiding data points at each end and then scrolling the vector across a viewable area, which isn't really something I feel is important enough to go through the effort of doing.
