### ISSUE TITLE
Double ports in server menu when is added a port in IP Alias to an ip.

### ISSUE THREAD

**Issue by StancuGaby** [pterodactyl/panel#4237]
### Current Behavior

Double ports when is added a port in IP Alias to an ip.
https://prnt.sc/zqOLhMEt-v_7

### Expected Behavior

I expected the assign port to the allocations will be hide when I add a port to IP Alias.

### Steps to Reproduce

Add a port( : ) in IP Alias section and you will have double ports when you are in server menu(and anywhere).

### Panel Version

1.8.1

### Wings Version

1.6.3

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DaneEveritt** [comment]
Aliases were not designed to use ports, so this is working as intended.

**Comment by StancuGaby** [comment]
I know,but is kind of bug

**Comment by DaneEveritt** [comment]
It was never designed to work with a port, if anything that would be a feature request but it would be super low. The point of the alias was to allow users with internal networking due to NAT to specify the external public IP users should be using, or a CNAME value for easier connecting.

It isn't meant to be a proxy value, which seems to be how you're using it.

**Comment by StancuGaby** [comment]
I understand this,I need to make a new issue for this "feature"?
