### ISSUE TITLE
IPs aren't accepted for node FQDNs

### ISSUE THREAD

**Issue by Boy132** [pterodactyl/panel#4405]
### Current Behavior

Any ip for the node FQDN is seen as "not valid" by the panel. (shows `The FQDN or IP address provided does not resolve to a valid IP address.`)
https://github.com/pterodactyl/panel/commit/7b91c38396fbcda117d38a6d1e1e668d338a1acd introduced this bug.

### Expected Behavior

Allow ips as node FQDN.

### Steps to Reproduce

Try to create a new node with an ip (e.g. `127.0.0.1` or your servers public ip) as node FQDN.

### Panel Version

1.10.3

### Wings Version

1.7.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
did you try `localhost`? I don't expect it to work but it's worth asking

**Comment by parkervcp** [comment]
On another note, to be able to use a node your computer has to be able to reach it. So even if you got the panel to add a node at `127.0.0.1` you wouldn't be able to use it.

**Comment by Boy132** [comment]
`localhost` doesn't work either. And I used `127.0.0.1` as an example because I first thought this only applied to local ips.
But it applies to ips in general.

**Comment by Jcodeerd** [comment]
This also happens to all ips indeed

**Comment by matthewpi** [comment]
Guess it makes sense that `dns_get_record` would ignore `/etc/hosts`.  It seems our best bet is to allow IPs directly and bypass the DNS lookup, and fallback to `gethostbyname` if the DNS lookup returns nothing otherwise you cannot use `localhost` or any host specified in `/etc/hosts` which I believe would break the Docker development environment, only downside being `gethostbyname` only works for IPv4, but I don't think that should be too big of a problem.
