### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by Syntax3rror404** [pterodactyl/panel#4406]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

The world is changing and kubernetes has become the new standard in recent years when it comes to containerization. The question is how we can make pterodactyl compatible with kubernetes. 

### Describe the solution you'd like.

Helm chart for kubernetes to set up and be able to update pterodactyl. 

### Additional context to this request.

I think the only major problem will be switching from the docker socket to the kubernetes api.

**Comment by kddige** [comment]
Just giving my tought on this, as i have tought the same.

As pterodactyl is kinda like an orchestra ish already, what features from kubernetes do we need in Pterodactyl? I can see a few benefits. However, those require great enterprise kubernetes setups, like shared storage and multi node clustering.

At the end of the day, it's just a game server. So the high availability it gives (imo the only real benefit) vs. the complexity, maybe isn't worth it.

**Comment by Syntax3rror404** [comment]
The question is not what features from kubernetes we need to implement into pterodactyl to make it a better orchestra the feature request is about make pterodactyl usable within kubernetes which is now **state of the art**. Most other applications move from docker to kubernetes or they are already kubernetes ready. Kubernetes have much more benefits then only HA you are much more flexible, you can just destroy your cluster and rebuild it without any data loss and other things. Without a docker socket you are also much safer. 

With solutions like Rancher a installation of k8s and k3s are really easy and **I dont mention to remove the docker support** for small setups **only to make this great piece of software able to run on a kubernetes setup**. And a storage class can be a stupid nfs so thats not the point and you can also run a single node cluster fine if you not need HA.

**Comment by matthewpi** [comment]
You posted this issue <https://github.com/pterodactyl/panel/issues/1741> awhile ago, I don't see how anything has changed.

There are core parts of Pterodactyl that aren't designed with systems like Kubernetes in mind.  Specifically the file manager, allocations system, and the concept of nodes entirely.  On Kubernetes you don't tell pods what IPs they should use, they just get one.  While allocations might be able to be used with services, the entire networking concept of Kubernetes breaks down when what you are running is usually a publicly exposed single-replica stateful app.  This is all also ignoring the complexity of having a file manager when 99% of people using Kubernetes will be mounting ReadOnlyOnce PVs which we can't attach else where.

This software is designed for both individual users and traditional hosting companies, not people with the bandwidth to manage an entire Kubernetes cluster.  If people want something like Pterodactyl for Kubernetes, they are better off modifying it to their specific needs themselves or finding something else.

In terms of running the Panel itself on Kubernetes, that should definitely be possible and documented, but running Wings and servers for that matter on Kubernetes won't be implemented officially.

**Comment by srounce** [comment]
> On Kubernetes you don't tell pods what IPs they should use, they just get one.

This isn't strictly true, it's indeed quite possible for pods to be assigned to a specific node (either via PVC binding or node affinity configuration in podspec). In addition if it were exposed via a NodePort Service, it wouldn't matter if the pod were moved around anyway as it'd still be accessible on the original IP.

In combination with this Pterodactyl seems like it'd be really great for running a fleet of game servers and across a bunch of machines and not really having to worry about which one it ended up on.

**Comment by Syntax3rror404** [comment]
In kubernetes the ip adresses are not a problem. There are kubernetes services which points to the pod and is reachable over the service name like in docker. 

In kubernetes everything and much more is possible compared to docker.

**Comment by ethan-gallant** [comment]
@matthewpi sorry to bring up an old thread here but I was wondering if you'd accept a contribution to support Kubernetes. 

Considering your feedback (and assuming it still holds) if Pterodactyl integrated in a configurable fashion:
-  Runningn servers in Kubernetes 
- Had configurable "public IP" assignment through services. 
- Registered actual Kubernetes nodes as Pterodactyl panel nodes and removed them based on cluster state

Would a contribution satisfying that criteria be welcome?

**Comment by S0ly** [comment]
no news on that ?

**Comment by S0ly** [comment]
kubernetes whit shared storage could be a crazy experience for pterodactyl

**Comment by schrej** [comment]
No, it wouldn't. There are two (architectural) options for integrating Pterodactyl with Kubernetes:

First, one could do as @ethan-gallant suggested, and register all nodes within a cluster as nodes in Pterodactyl. And then what? With the current architecture you need to run wings on each node. So lets say we do that and deploy wings on all nodes using a DaemonSet. How do servers get deployed? Wings just does it the way it always does and spawns a container on the node? What's the benefit of Kubernetes here?
It spawns a Pod? But pins it to a specific node? Again, what's the benefit here? What feature does k8s provide that gives any advantage whatsoever? Logs? already there. Scheduling? Not used. Rescheduling when a node fails? Not used (and not useful, as the game session terminates anyway). Networking? Not used.

The second, probably the more reasonable approach would be to integrate Pterodactyl with entire Kubernetes clusters resembled as a single "Node". That is an entirely different level though and would require at least a major rewrite of wings. A entirely different daemon (or operator/controller in k8s terms) is probably the more sensible option though. While it's definitely possible to recreate all of Pterodactyl's features on top of Kubernetes, it is a lot of work. And it doesn't play well with the current architecture of Pterodactyl either. Especially the upfront ip/port assignment is tricky.

Not everything has to run on Kubernetes. Sometimes a regular VM, container or bare metal server is just fine.

**Comment by Syntax3rror404** [comment]
> No, it wouldn't. There are two (architectural) options for integrating Pterodactyl with Kubernetes:
> 
> First, one could do as @ethan-gallant suggested, and register all nodes within a cluster as nodes in Pterodactyl. And then what? With the current architecture you need to run wings on each node. So lets say we do that and deploy wings on all nodes using a DaemonSet. How do servers get deployed? Wings just does it the way it always does and spawns a container on the node? What's the benefit of Kubernetes here? It spawns a Pod? But pins it to a specific node? Again, what's the benefit here? What feature does k8s provide that gives any advantage whatsoever? Logs? already there. Scheduling? Not used. Rescheduling when a node fails? Not used (and not useful, as the game session terminates anyway). Networking? Not used.
> 
> The second, probably the more reasonable approach would be to integrate Pterodactyl with entire Kubernetes clusters resembled as a single "Node". That is an entirely different level though and would require at least a major rewrite of wings. A entirely different daemon (or operator/controller in k8s terms) is probably the more sensible option though. While it's definitely possible to recreate all of Pterodactyl's features on top of Kubernetes, it is a lot of work. And it doesn't play well with the current architecture of Pterodactyl either. Especially the upfront ip/port assignment is tricky.
> 
> Not everything has to run on Kubernetes. Sometimes a regular VM, container or bare metal server is just fine.

It seems like you have some misunderstandings about the potential ways to operate within Kubernetes. Pterodactyl doesn't need to run as a DaemonSet. In fact, a single instance would suffice.

We can even completely do away with Wings. What we actually need is just the web interface with all its functionalities, and instead of communicating with the Docker Daemon (which is increasingly less favored for operations), we could interact with the Kubernetes API. Instead of a daemon, a Pterodactyl controller could be used to manage all the game servers.

Kubernetes would significantly enhance Pterodactyl. Not only would we gain security advantages, but we could also link multiple computers into a cluster, providing built-in redundancy and failover capabilities.

If there's a perfect use case for Kubernetes, it's Pterodactyl. The ability to efficiently manage resources, minimize downtime, and flexibly adapt the infrastructure makes Kubernetes the ideal platform for software like Pterodactyl. With Kubernetes, we could greatly optimize the management and deployment of game servers while simplifying maintenance and scalability.

I hope this clarifies some misunderstandings and demonstrates how beneficial Kubernetes can be for Pterodactyl.

For example: https://agones.dev/site/

What is a kubernetes controller? https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#custom-controllers

**Comment by Syntax3rror404** [comment]
Please reopen this issue

**Comment by schrej** [comment]
> It seems like you have some misunderstandings about the potential ways to operate within Kubernetes. Pterodactyl doesn't need to run as a DaemonSet. In fact, a single instance would suffice.

If you would've bothered to read my entire reply, you might have noticed that I suggested two options, the latter being what you're describing. It is possible, but I don't see it as a good fit with this project. If you want to run your servers on k8s, just use Agones. Or feel free to create a fork of Pterodactyl and reengineer it for k8s.

Also, adding Kubernetes support to Pterodactyl doesn't "simplify maintenance", since the old deamon can not just be abandoned in favour of k8s. Therefore, maintenance would require more effort instead of less. Haven't heard of scalability to be an issue with Pterodactyl, I think you can run quite a few nodes with one instance.

I also disagree that hosting game servers is a "perfect use case" for k8s. The perfect application to run on Kubernetes is stateless and horizontally scalable, without any storage requirements and it's database hosted externally. Game servers are the exact opposite: they are usually single-instance, hold a lot of state, require storage and should never be terminated while users are connected. The best "failover" you can get is restarting the server as quickly as possible, but all players will get disconnected anyway.
From what I can see Agones is primarily intended for publishers/studios that host a large fleet of public game servers, for games like COD or Fortnite.

**Comment by Syntax3rror404** [comment]
Thats why Kubernetes have StorageClasses and statefull sets

Agones has also Not a ui as ptero. I agree to implement k8s Support takes some time.

**Comment by ethan-gallant** [comment]
I'm wondering here if it's already possible to implement the Wings interface with Pterodactyl to get use out of the UI.

I worked for some major Minecraft networks and if we had the Pterodactyl UI and could plug it into our backend (custom, Kubernetes, whatever) it would have been a huge win for us. 

In my opinion, regardless of if the project is aiming to adopt Kubernetes, the Wings API should be generic enough to allow developers to implement it on their own.

Adding Kubernetes would be a massive undertaking that only a small subset of users could really leverage. So I think not directly supporting it at this time is the right move for the overall projects health, maintainability, and longevity. 

I would however appreciate if the Pterodactyl project was open to long-term gentrifying the Wings API in a way so users may implement a "Daemon" / Wings fork. Providing other developers an opportunity to DIY it would give the Pterodactyl project an opportunity to observe (or not observe) organic growth to determine if it's worth adopting. 

Some examples of Wings daemons users could implement:
- Kubernetes
- ESXi / Hyper-V / KVM
- OpenStack API
- Custom server orchestration tools, like large Minecraft networks leverage

Just an idea, there would be a lot to resolve like having Wings offer optional feature support which would increase the overall complexity of the project itself as-is. But it would be neat to see for sure.

**Comment by Syntax3rror404** [comment]
For Kubernetes support you dont need the deamons anymore because this job is done by kubernetes and this way better. You need only the panel but with some modifacations, so that the panel can talks with kubernetes instead of the deamons. 

Kubernetes runs everywhere on bare metal on every cloud on openstack on vmware on proxmox etc etc etc

Its industry standard and the cloud native way. 

Docker is basicly dead and nowdays only a development tool.

**Comment by fleeco** [comment]
> I also disagree that hosting game servers is a "perfect use case" for k8s. The perfect application to run on Kubernetes is stateless and horizontally scalable, without any storage requirements and it's database hosted externally. Game servers are the exact opposite: they are usually single-instance, hold a lot of state, require storage and should never be terminated while users are connected. The best "failover" you can get is restarting the server as quickly as possible, but all players will get disconnected anyway.

So - there is no "perfect application" for Kubernetes, because Kubernetes is designed to be able to orchestrate pretty much any application / workload.  It's great for managing state, it's great at managing storage (check out Rook / CEPH).  It's far more robust when it comes to networking and simplifying ingress / cert creation.  

Developers find Kubernetes "hard" because Kubernetes can pretty much do literally anything.  That being said, the primitives (deployment, statefulset, pods) are basically 1:1 to Docker.  Kubernetes isn't hard, it's just the swiss army knife of "It can do everything" and because of that - the depth can be overwhelming for some.

That being said, I do think there _is_ a path for this project to support Kubernetes, and it doesn't necessarily have to use all the Kubernetes primitives to do so.  I'll take a crack at generating a helm chart for Wings.  Unless there is some seriously complex voodoo under the hood (I'm not seeing anything) it could be a first good step.  

Through my research, I just found this project and I have to say - it looks cool!  Going to give this a whirl as well.
https://playfab.github.io/thundernetes/

**Comment by srounce** [comment]
@fleeco how does it compare with Agones?

**Comment by ethan-gallant** [comment]
@srounce Agones and Thundernetes are basically the same thing, just the Google vs Microsoft version.

In reality Pterodactyl is a VERY different system more focused on the user representable view of Game Servers. Opposed to tools like Agones / Thundernetes where it's more focused on large scale games companies running hundreds of game servers.

A good use-case of Agones / Thundernetes would be a large scale Games company such as CubeCraft / Mineplex which focuses on gameserver orchestration.

**Comment by srounce** [comment]
Yes I'm quite familiar with Agones, I'm in the process of building a controller and a bunch of frontend services on top of it. I was more curious if there was any major conceptual/functional differences in Thundernetes' approach.

**Comment by spensireli** [comment]
I agree with @Syntax3rror404 . If docker support exists there should be k8s support and preferably a helm chart.  I'd be happy to contribute if a decision is made for Pterodactyl to embrace k8s.

**Comment by schrej** [comment]
> So - there is no "perfect application" for Kubernetes, because Kubernetes is designed to be able to orchestrate pretty much any application / workload.

The fact that Kubernetes _supports_ running a lot of different kinds of workload doesn't invalidate my point. You can also run VMs on a k8s cluster, but that's not a perfect use-case for it.

> Kubernetes isn't hard, it's just the swiss army knife of "It can do everything" and because of that - the depth can be overwhelming for some.

I wasn't arguing that it's hard to integrate because Kubernetes is "hard". I said it doesn't make sense for this project because
- Pterodactyl's data model makes it very hard to integrate with k8s in a useful way. You can't just replace wings with something that talks to k8s and then expect it to work well. A lot of the things that k8s could take over are currently handled by the panel, and it would be a lot of work to allow doing those from a wings replacement.
- not integrating on a high level doesn't provide any significant benefits. Setting up a k8s cluster just to deploy wings on multiple machines is a bit overkill, don't you think? Creating a helm chart for it and deploying it on a cluster shouldn't require explicit support from the project either, if you really want to do that. Feel free to create and publish a helm chart. If it's any good we can talk about referencing it from the documentation for anyone that is interested.

And just to clean up some confusion, even though I'm repeating myself: Agones/Thundernetes are intended for Game Development Studios/Publishers, not game server hosting companies. It's intended for hosting automated game server systems that provide instances for lobbies that are created on demand, either by matchmaking or by someone starting a lobby from within a game. It's not intended to sell individual dedicated servers to customers directly. Nitrado, the only "hosting" company on Agones' website is also not using it to sell individual servers, they're using it to offer this kind of hosting services to studios: https://gamefabric.com
