### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by RedixCoreBG** [Pterodactyl/Panel#450]
Can you make a way to grand XX user with "XX" node and they would have full perms for it (Like creating servers with the ram/disk space they got.)

**Comment by schrej** [comment]
Has been suggested in the past, not planned in the near future, see the old issue for details.

Also, when you have a feature request, please be a little more specific, especially in the title. Maybe something like `[Suggestion] Permissions per node` or something and a little more text in the description itself. It's not like i didn't get what you would like to have in the panel. But as you want something done, just put a little more love into the request. And if its just setting a proper title so we can see what the issue is about at a glance.

Duplicate of #199
