### ISSUE TITLE
SFTP - Problems

### ISSUE THREAD

**Issue by HLF-Raideer** [Pterodactyl/Panel#452]
We're experiencing a problem when using the latest version of pterodactyl.
We're updated from 6.0 beta-2 to the latest stable and when I go to the SFTP section in the panel, it gives back an error ONLY ON THE SERVERS which are created before the update. I got no problems during update. 

If I try to use a server which is created after update -- it is working well.

The laravel error log:
```
Next ErrorException: The MAC is invalid. (View:
*/resources/themes/pterodactyl/server/settings/sftp.blade.php) in
*/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:184
```

I tried to report it on discord, but @FlantonEZ said that possible could be good if I report it on GitHub.

**Comment by DaneEveritt** [comment]
Your issue is that you re-ran the `php artisan key:generate` command, which the documentation is pretty clear about only running once (as well as the command itself).

This has reset your encryption key, thus causing that issue with anything that was previously encrypted. The only fix available is setting the `sftp_password` column in the `servers` table to be `NULL` for any of the old servers having the issue.
