### ISSUE TITLE
GitHub Integration (pull/push changes)

### ISSUE THREAD

**Issue by Nzii3** [pterodactyl/panel#4626]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

A GitHub integration where you can link your GitHub account so that way when you make changes to your code you can push the changes to your repository, or pull changes (similar to the GitHub Desktop Client).

### Describe the solution you'd like.

A GitHub integration, where you can push and pull changes to a link repository.

**Comment by lordofpipes** [comment]
Generic OAuth2 support would be cool, perhaps for supporting Microsoft accounts, Discord accounts, and Github accounts (Microsoft accounts being the logical choice for Minecraft admins)

In the past there have been plugins for this, but they were proprietary.

I see that a previous discussion lead to the conclusion that it's too much of a time investment to make this, though - https://github.com/pterodactyl/panel/issues/3990#issuecomment-1060678213

There was another previous discussion about potentially allowing reverse proxies to do the authentication for you, so that a 3rd party auth system could be made entirely outside of pterodactyl - https://github.com/pterodactyl/panel/issues/4026 - Seems like a great solution for keeping complexity as low as possible

**Comment by yesBad** [comment]
Technically possible already. Eggs can have git(hub) sync so when you restart your server it pulls new files. 👀

**Comment by Doc94** [comment]
Also the github with actions and the panel api can help for a few things.

**Comment by FoksVHox** [comment]
I think what @Nzii3 looks for is a git integration with the panel, so that you can pull/push files in your server to a git repo.

**Comment by Nzii3** [comment]
> I think what @Nzii3 looks for is a git integration with the panel, so that you can pull/push files in your server to a git repo.

Yes this

**Comment by Nzii3** [comment]
> Technically possible already. Eggs can have git(hub) sync so when you restart your server it pulls new files. 👀

How can I do this exactly @yesBad?

**Comment by yesBad** [comment]
> > Technically possible already. Eggs can have git(hub) sync so when you restart your server it pulls new files. 👀
> 
> How can I do this exactly @yesBad?

Most if not all generic _lang_ eggs have this.

**Comment by Nzii3** [comment]
@yesBad I mean how do I actually connect a repo with git so when I want to pull changes I can?

**Comment by yesBad** [comment]
> @yesBad I mean how do I actually connect a repo with git so when I want to pull changes I can?

They have that.

**Comment by Nzii3** [comment]
> > @yesBad I mean how do I actually connect a repo with git so when I want to pull changes I can?
> 
> They have that.

@yesBad HOW can I do that

**Comment by 1kgk** [comment]
anyone figure out how ?
