### ISSUE TITLE
Tasks queue broken

### ISSUE THREAD

**Issue by Jelcoo** [pterodactyl/panel#4660]
### Current Behavior
`QUEUE_CONNECTION` is set to `sync` by default, which will cause all tasks to run at once.

### Expected Behavior

`QUEUE_CONNECTION` should be set to `database` by default.

### Steps to Reproduce

Create a schedule with 2 or more tasks, with the second task having a delay, and run the schedule. You will see both tasks being run at once.

### Panel Version

1.11.2

### Wings Version

1.11.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
It would also be nice if `sync` would be explained somewhere. Either in the docs or in the env setup command.

**Comment by trenutoo** [comment]
> It would also be nice if `sync` would be explained somewhere. Either in the docs or in the env setup command.

It's Laravel-specific, see https://laravel.com/docs/9.x/queues

sync shouldn't have made it into the production release, because it's used for local development and not having to wait for subsequent tasks to run in the background. It's a default value for new Laravel setups, and during Laravel 9 upgrade it's one of the things that slipped.

This should only affect new installations though. Don't see a reason to have it as an available option in the AppSettingsCommand.

**Comment by matthewpi** [comment]
The `.env.example` defaults to `sync` for development and easier initial setup (though I can see the confusion with `configs/queue.php` defaulting to `redis` if no value is specified).  During `php artsian p:environment:setup` it will ask you what queue driver you would like to use, however `sync` is selected by default which is not intended.

This shouldn't affect existing installs or people who select the proper option during setup, but I will change `.env.example` to use `redis` to prevent this from becoming a bigger problem.
