### ISSUE TITLE
Updating panel from v1.11.2 to v1.11.3 

### ISSUE THREAD

**Issue by TUNEinBattles** [pterodactyl/panel#4673]
root@gp:/var/www/pterodactyl# php artisan migrate --step --force

   INFO  Running migrations.

  2023_01_24_210051_add_uuid_column_to_failed_jobs_table ........... 13ms FAIL

In Connection.php line 760:

  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'uuid' (
  SQL: alter table `failed_jobs` add `uuid` varchar(191) null after `id`)

In Connection.php line 545:

  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'uuid'

Currently trying to revert back to v1.11.2

I don't know if this is a bug or just my installation doing this. This is NOT a new install.

**Comment by gOOvER** [comment]
you add the table before update was out. I gave you a solution in disord; so its not a Bug, because it worked for me and a lot of other guys

**Comment by matthewpi** [comment]
I tested that migration before pushing out the update, you likely modified the table yourself or applied someone else's fix.  While I could edit the migration to ignore column errors, people should not be manually editing the database schema.

You have two options to fix this, edit your database manually again and drop the `uuid` column, or edit the migration (`database/migrations/2023_01_24_210051_add_uuid_column_to_failed_jobs_table.php`) and comment out the lines that add the `uuid` column in the `up()` function, run the migrations, then revert the changes you made to the migration file.  I'd recommend you drop the column rather then editing the migration code.

**Comment by TUNEinBattles** [comment]
I haven't touched the tables so I did nothing of the sorts. I hate touching mysql databases unless devs tell me exactly what to put in for commands. I did the update this morning right before I went onto discord for help so I haven't applied anyones fixes as of yet. I will go in and drop the uuid column and see if this fixes it. Hopefully I don't have to do the commit out way :) here's to hopefulness!

**Comment by gOOvER** [comment]
> I haven't touched the tables so I did nothing of the sorts. I hate touching mysql databases unless devs tell me exactly what to put in for commands. I did the update this morning right before I went onto discord for help so I haven't applied anyones fixes as of yet. I will go in and drop the uuid column and see if this fixes it. Hopefully I don't have to do the commit out way :) here's to hopefulness!

i allready told you to drop this table in discord

**Comment by haugli92** [comment]
I ran into the same issue as @TUNEinBattles.

My problem occurred because my "failed_jobs"-table was over 130MB and PHP could not allocate that much data.

Solution for me:

- Export "failed_jobs"-table.
- Drop "uuid"-field in "failed_jobs"-table.
- Truncate "failed_jobs"-table.
- Run "php artisan migrate --seed --force".
- Import data from "failed_jobs"-export (if you really want to have this data).

**Comment by Brandin** [comment]
I encountered this issue and used the solution that @haugli92 presented above. The problem occurred for a similar reason, due to table size. I would say this issue should be reopened and allow for a check during these migrations that if returned error is that the column exists, the migration should be considered applied.
