### ISSUE TITLE
Docker not working on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by fede1132** [pterodactyl/panel#4801]
### Current Behavior

When I try to start a server I get this error:

```
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from pterodactyl/yolks 
Digest: sha256:cdf9461a87dff73748de6f7ef81903df893e97825346f6a43a9a3766430e2261 
Status: Image is up to date for ghcr.io/pterodactyl/yolks:java_17 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Server marked as offline...
container@pterodactyl~ Error Event [4c687336-8c24-478d-90cc-ea08c063c161]: environment/docker: failed to start container: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: openat2 /sys/fs/cgroup/system.slice/docker-cd3c29e647070601d87bc65a8a1faa06ae0d1f78157c320c25049a87156043e1.scope/io.weight: no such file or directory: unknown
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from pterodactyl/yolks 
Status: Image is up to date for ghcr.io/pterodactyl/yolks:java_17 
Digest: sha256:cdf9461a87dff73748de6f7ef81903df893e97825346f6a43a9a3766430e2261 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Server crash was detected but an error occurred while handling it.
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
```

### Expected Behavior

Start the server normally

### Steps to Reproduce

Install ptero panel and wings on ubuntu 22.04 lts using a raspberry pi 4 8gb

### Panel Version

1.11.3

### Wings Version

1.11.6

### Games and/or Eggs Affected

Paper

### Error Logs

```bash
https://ptero.co/letylurafe
http://bin.ptdl.co/8gnjv
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by QuintenQVD0** [comment]
I only got wings ever to run a pi 4 with the debian os and some magic. As cgroup are not in the ubtunu release for thet pi and pterodactyl needs them.

**Comment by sommersdev** [comment]
@QuintenQVD0 can you teach me the magic?

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0 can you teach me the magic?

In the discord:
https://discord.com/channels/122900397965705216/658550982975946762/1053686750570086460

**Comment by sommersdev** [comment]
Sorry for the late response but I got it running yesterday with the Pterodactyl script

**Comment by LunaDotGit** [comment]
For me the issue was that the block scheduler did not support I/O Weights, thus the error.
I think I found a workaround which might help some people, especially trying to get it working on a raspberry pi with the rpi-eeprom bootloader.

My System:
- OS: Ubuntu 24.04 LTS
- Hardware: Raspberry Pi 5 Model B (8GB)
- Kernel: 6.8.0-1005-raspi
- Bootloader: rpi-eeprom on SD-Card (mmcblk0)
- Docker Version: Docker version 26.1.4, build 5650f9b
- Daemon: Systemd

The "fix":
Try running `sudo modprobe bfq` and see if the error persists. You may also test the error behaviour outside of pterodactyl by executing `docker run -it --name c1 --blkio-weight 500 ubuntu:24.04 /bin/bash` for example. If the error disappears, you may try creating a new game server within pterodactyl on your system. 
If that also works, great! You may then try the following to automatically add `bfq` to your Block Schedulers on boot:
1. sudo vim /etc/modules-load.d/bfq.conf
2. Press "i"
3. Enter "bfq"
4. Press "Escape"
5. Enter ":wq"
6. Enter "sudo reboot" in your shell so the System reboots.

bfq should now always appear within your Block Schedulers e.g. when Checking: `cat /sys/block/mmcblk0/queue/scheduler` (`mmcblk0` may be different on your system, depending on your configuration)

I hope this helps.

**Comment by August7337** [comment]
> The "fix": Try running `sudo modprobe bfq` and see if the error persists. You may also test the error behaviour outside of pterodactyl by executing `docker run -it --name c1 --blkio-weight 500 ubuntu:24.04 /bin/bash` for example. If the error disappears, you may try creating a new game server within pterodactyl on your system. If that also works, great! You may then try the following to automatically add `bfq` to your Block Schedulers on boot:
> 
> 1. sudo vim /etc/modules-load.d/bfq.conf
> 2. Press "i"
> 3. Enter "bfq"
> 4. Press "Escape"
> 5. Enter ":wq"
> 6. Enter "sudo reboot" in your shell so the System reboots.
> 
> bfq should now always appear within your Block Schedulers e.g. when Checking: `cat /sys/block/mmcblk0/queue/scheduler` (`mmcblk0` may be different on your system, depending on your configuration)
> 
> I hope this helps.

thx you very much it's work for me
