### ISSUE TITLE
Weird behavior if Panel and Wings are on different domains

### ISSUE THREAD

**Issue by Gabgobie** [pterodactyl/panel#4856]
### Current Behavior

I recently bought a dedicated domain for playing with friends to separate it from business and clear the private use from the business domain. This has led me to find interesting and unwanted behavior in ptero.

Let's establish some things first:

- we are working with one internal and two external domains (all placeholders to not dox myself):
 - business.net   <- external
 - private.net      <- external
 - internal.net     <- internal (not yet in use and therefore not relevant but I would like to move the wings here in the future)
- Where is it hosted
 - The panel was initially hosted on pterodactyl.business.net
 - Now I made the panel also accessible through pterodactyl.private.net
 - The wings were initially and still are hosted on wings.business.net

Now the issue:

When I access ptero through the original domain (pterodactyl.business.net) everything is working flawlessly, however when I access the panel through the new domain (pterodactyl.private.net) I will be presented with up to date information on the servers (are they running) in the dashboard and when going into the admin section I can see up to date information on the node (wings version etc.) but the heart will appear red instead of green telling me that there is no connection. I am still 100% certain that they communicate mostly correctly since the information on ram, cpu and storage consumption of servers is up to date and the status (online/offline) is also displayed correctly in the dashboard. I did verify that the configuration of the node still states the correct FQDN and it does (wings.business.net). The non admin server control panel is not working from the new domain (private.net) but will work when the domain is matching the one the wings agent is using (business.net). It will open but then fail to connect to the server. "We're having some trouble connecting to your server, please wait..." as a red bar on the top of the page.

For now I can work around this by using a split horizon dns and moving both to the new domain but since I plan on having the wings agent (at least the API) only respond to the local domain (internal.net) while the panel is on the external domain this will become problematic

### Expected Behavior

The expected behavior would be to have the panel connect to the defined wings agent FQDN without regarding the domain itself was dialed up on.

### Steps to Reproduce

1. Get yourself two different domains (internal/fake domains should work as well)
2. Set pterodactyl and the wings agent up on the same domain (panel/wings.domain1.fake)
3. Set up any gameserver on the install to validate its functionality now and later
4. Make a dns record for the panel on your second domain (panel.domain2.fake)
5. Open your panel using the second domain (panel.domain2.fake)
6. Try to open the non-admin server control panel

Unfortunately my time is very limited right now and will be for the next few weeks but I will try my best to provide you with any help I can so feel free to ask.

### Panel Version

1.11.3

### Wings Version

1.11.7

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Gabgobie** [comment]
Just after submitting the issue there was one more thing that came into my mind. I will go ahead and guess that the issue stemms from the configuration on the wings side which includes a "remote" parameter with the URL from the panel. This URL obviously doesn't match the URL I am using when accessing the panel from a different domain, however I feel like even if it probably is the issue right now this should not be the behavior. For now both domains are still pointing to the panel so the panel is still accessible on the configured wings remote and can therefore transmit data. I believe that the quickfix would be to just change this value for the new URL of the panel and we would have a working system, however the panel would still be broken if it is supposed to be accessible from multiple domains (internal and external) like in my setup.

In my case the Panel in its final form would be reachable on pterodactyl.private.net and pterodactyl.internal.net while the wings agent is only on wings.internal.net. Now I would have to set the variable of the wings configuration to "remote: 'https://pterodactyl.private.net'". However this would render pterodactyl.internal.net unusable.

**Comment by matthewpi** [comment]
This is likely caused by CORS.  Communication between the Panel and Wings is mostly proxied by the Panel, however the "heart" display on the nodes list is a direct request from the Browser to Wings without being proxied by the Panel backend.  The same thing occurs for the server console, it's a direct websocket connection from the Browser to Wings.  Wings is only configured to allow the panel url as a CORS allowed origin, all other origins are blocked by default.   To resolve this you would need to update the panel url in the Wings config to be the new domain, or add the new domain to the `allowed_origins` config setting, both are accessible on the `/etc/pterodactyl/config.yml` file on each node running Wings.

Keep in mind that this software was not really designed to be accessed by multiple different domains.

**Comment by Gabgobie** [comment]
Thank you for your insight. If I understand correctly, this would then require the wings API to be exposed to the web directly at all times just like the panel because otherwise the non-admin control panel won't work at all. My intention in ultimately moving the wings to an internal domain was to create a more secure environment.

Would it be something worth exploring to have the panel proxy everything API related and have the wings only expose the game servers to the web or should I mark this issue as resolved?

Please excuse my lack of technical knowledge that led to me opening this issue in the first place.

**Comment by Boy132** [comment]
> Thank you for your insight. If I understand correctly, this would then require the wings API to be exposed to the web directly at all times [..]

Correct. Wings needs to be exposed too so your browser can connect to it. You can't make it internal only.

**Comment by Gawie-Schneider** [comment]
@Gabgobie I am currently running the exact same scenario. I am running my CtrlPanel.gg and Pterodactyl Panel on the free Oracle servers and I am running wings on my local machine sitting on my desk at home because it has a xeon processor and not ARM.

Anyway, I had to ensure that my wings instance is defined using a FQDN and is publicly available for 2 reasons

1. When the client connects to the game host, it connects to wings and not to the panel
2. The panel has to have access to the public fqdn of the wings server so it can manage and deploy to it.

There is nothing tricky to setup here. I'm on the same domain but different subdomains with different ssl certs.

Hope the information helps if you're still stuck
