### ISSUE TITLE
CopyOnClick animation instantly disappears

### ISSUE THREAD

**Issue by PadowYT2** [pterodactyl/panel#4884]
### Current Behavior

When copying an element on click (such as address), there's an animation for Fade in, but not out

https://github.com/pterodactyl/panel/assets/71085027/2648f9d7-3abe-4594-aafb-1e44bca39edd

### Expected Behavior

There should be an animation for Fade out

### Steps to Reproduce

1. Go to a server
2. Copy the address
3. Wait for the popup to disappear

### Panel Version

1.11.3

### Wings Version

1.11.7

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by zvikasdongre** [comment]
There is a [conditional wrapping the Fade and Portal Components](<https://github.com/pterodactyl/panel/blob/v1.11.3/resources/scripts/components/elements/CopyOnClick.tsx#L47>),
And instead of triggering something to hide the popup, the code sets `copied` to false after 2.5s, removing the element from the DOM, which results in no exit animation.
