### ISSUE TITLE
Error when opening "databases" tab on a server page

### ISSUE THREAD

**Issue by zmiguel** [pterodactyl/panel#4898]
### Current Behavior

This happens when I try to go to the databases tab on a server 

![image](https://github.com/pterodactyl/panel/assets/4400540/75845205-9538-40ff-8396-bcde45ef3ec8)

I've just setup a database host and the panel seems happy about it.
I could create a database but when I click to view the password I get that message.
I also get a 500 HTTP Error on the page `.../api/client/servers/<server_id>/databases?include=password`

### Expected Behavior

It to works and show my the databases and view their password

### Steps to Reproduce

Go to the databases tab on a server

### Panel Version

1.11.5

### Wings Version

1.11

### Error Logs

```bash
https://pteropaste.com/nyfhce273nu4/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [ ] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
Please visit the Discord for configuration related issues. This is not a bug.

**Comment by iceHtwoO** [comment]
@zmiguel Could you find a fix? I have the same issue and the discord server wasn't much help

**Comment by Boy132** [comment]
> @zmiguel Could you find a fix? I have the same issue and the discord server wasn't much help

Please visit the Discord for configuration related issues. This isn't the place to ask.

**Comment by abaurens** [comment]
Doccumenting the solution here for anyone else finding this issue.
I did not find the solution myself. Credits goes to Loki on the pterodactyl discord for finding the reason and solution to the issue.

Turns out the pannel docker image is missing the `HASHIDS_SALT` and `HASHIDS_LENGTH` environment variables.
`HASHIDS_SALT` should probably be generated by the entry point just like other variables of the same kind, but isn't right now.
`HASHIDS_LENGTH` should be set to `8` but it has a default value in case it's missing anyway.

You can fix the error by generating a random alphanumeric string of length 20 (no special chars) and then adding these variables to your container's environment either directly with docker, or in pterodactyl's `/app/var/.env` file:

> /app/var/.env
> ```env
>   APP_KEY=79fA6r2Psc6Dj5L32ZiyiWHx3ceolnpD
>   HASHIDS_LENGTH=8
>   HASHIDS_SALT=sXDDV7Vw65XbvV64yzaM
> ```

> docker compose:
> ```yml
>   environment:
>       ...
>       HASHIDS_SALT: "sXDDV7Vw65XbvV64yzaM"
>       HASHIDS_LENGTH: 8
> ```

Finally, here is a pull request (#5131) someone made 6 month ago to fix this. But it seems like it's stuck in testing
