### ISSUE TITLE
Install scripts in Packs

### ISSUE THREAD

**Issue by jffz** [Pterodactyl/Panel#492]
As Packs are already implemented, it could be interesting to have pretty the same service but using scripts instead of archives.

This would be a lot easier to manage through updates.

**Comment by DaneEveritt** [comment]
This is not going to happen. If you want something like this use the script and hook into the pack itself which is also available during the install script process.

**Comment by schrej** [comment]
What are packs for then? I mean you can create your own ones with serverfiles and everyting but sharing them on a hub would be difficult because of copyright (Minecraft for example).

**Comment by DaneEveritt** [comment]
They're designed to provide local file resources as needed for different servers. There are always going to be copyright issues with distributing files, which is why they have not taken priority in the design of this panel.

You should be using service scripts for the installation of specific server types that cannot have files distributed, and use variables to define different changeable values, such as what version to install.
