### ISSUE TITLE
Get data from wings agent through the panel

### ISSUE THREAD

**Issue by adrianprofir** [pterodactyl/panel#4950]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

"User story": I am running the panel and wings on my local server and then I connect to my panel from the web from a domain that is mapped to point to my local server.

I can login into the panel, I can see the Node and the server that are running, but I can't get any information about the server status and logs when I access it. Please see screenshot:
- ![image](https://github.com/pterodactyl/panel/assets/43696926/9e80d541-dbc7-4874-b3a9-4765cafb8c06)

### Describe the solution you'd like.

I would like the panel to make all the requests to the wings agent and then give the response back to the user.

I want to go from this way of getting data:
- ![image](https://github.com/pterodactyl/panel/assets/43696926/7004deac-df9f-4e63-971c-7b87385ffb15)

to this:
- ![image](https://github.com/pterodactyl/panel/assets/43696926/ae5dc279-2158-4da2-9839-1d25f78d682d)

### Additional context to this request.

If you agree with this change, then
Actually I would like to help with this feature but I need a bit of intro about how data is being served to the front-end from someone familiar with the project.

I am quite experienced with django and python and I would like to help :)

**Comment by parkervcp** [comment]
Doing it this way could put significant stress on the host that is the proxy for these connections. You would take what is essentially a spread out load and putting it on a single point of potential failure.

While I understand the reasoning behind why you would proxy all the connections though. My word is not the projects. I am just calling out potential issues.

**Comment by adrianprofir** [comment]
I think I should have been more specific in the feature description. I want to get only the information about the server status and logs to the front-end. The game traffic, meaning users connecting to the wings, would work as they have been until now meaning directly from user to the node.

For example, on the front-page of the panel I can see that my servers are actually running at the moment and on what IP+Port. In this case information is transmitted from the wings agent to the panel and from the panel to the front-end. 

I definitely agree with you that proxying all the traffic through the node is not a good idea. However, sending telemetry data such as CPU usage, RAM usage, logs and the status on those servers should not be a huge amount. 

Please let me know if the above makes sense or if I am completely wrong in understanding how this works..

**Sorry, clicked on close issue by mistake**

**Comment by parkervcp** [comment]
I wasn't saying to proxy the game servers though the panel server. I was talking about wings.

The panel directly connects to wings already, it just doesn't proxy the console. It's a faster connection to make it direct. I know this doesn't cache the output in the panel.

**Comment by adrianprofir** [comment]
Ah alright. So I guess we don't want to proxy the console :(. Should we close this issue?

**Comment by wdhdev** [comment]
I had this issue as well when using a local IP address. What if there was an option or something that you could set which would proxy the console through through the panel? Not defaulted, but just there for some specific use cases?

**Comment by StarbugGamer** [comment]
I also have excatly this problem. I have a configured a Minecraft server that starts up perfectly fine, but the Console does not connect to it. I can press the Stop button, but with no effect. It seems to me the Console has crashed somehow, but I see no error messages neither in Wings (runnig with --debug) or in the nginx error log of the panels webserver.

**Comment by parkervcp** [comment]
This issue you are all describing is that your computer is unable to reach the wings instance. This is not a pterodactyl issue so much as it is a configuration issue.

There are all kinds of network configurations that can cause this issue.

**Comment by matthewpi** [comment]
This isn't going to happen.  Most actions are already proxied through the panel and the few that aren't were designed to hit the node directly.

The actions that hit the node directly are:
- WebSocket (console output, live events, sending power action, etc)
- File Uploads
- Backup Downloads (when using the local storage driver)
- SFTP

There may be a few others, but these are the ones I know of that hit the node directly either due to protocol complexity (proxying websockets is a pain) or high bandwidth usage.

If you need all of these to work on an internal network externally, run a Layer 7 (or Layer 4) reverse proxy that fronts the connection to Wings.

But this behaviour will not be changed.  Support for different public/private endpoints options (like panel -> wings vs client -> wings) may be added, but we are not proxying everything through the panel.

**Comment by Sharktheone** [comment]
The simplest solution is probably to use the webserver to proxy the connection to wings.
I do exactly that in my setup (Nginx). Not sure how this would look like for Apache or caddy.

**Comment by wdhdev** [comment]
> The simplest solution is probably to use the webserver to proxy the connection to wings.

How would I go about doing this? I'm using Nginx.

**Comment by Sharktheone** [comment]
First you need to add the `default_server` tag to the listen entry like this:

```nginx
server {
    listen 443 ssl http2 default_server;
    server_name panel.<domain>;  
    # ....
}
```

Note that you need to give the exact domain (e.g panel.example.com) on at `server_name`

The second step is to add a new server block like this

```nginx
server {
        listen 443;
        server_name wings.<domain>;
        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass https://<wings domain or ip>:<wings port>;
        }
}
```

You can also add the second server block (for wings) as a new file in `/etc/nginx/sites-avaiable/pterodactyl-wings.conf` and link it to `sites-enabled`

Note: You can also add your ssl certificate in the wings nginx configuration instead of giving it wings.
