### ISSUE TITLE
Bot Panel

### ISSUE THREAD

**Issue by ItAlive** [pterodactyl/panel#4969]

**Comment by Boy132** [comment]
I'm not sure what your intention with this issue is but if you are looking for a Discord bot that can control the panel/ servers hosted with the panel there are some online. (this is not the place to ask)

If you want to host a bot yourself with the panel look at [these eggs](https://github.com/parkervcp/eggs/tree/master/generic).

If you actually have a question you can also visit the [Discord](https://discord.gg/pterodactyl).
