### ISSUE TITLE
Unable to connect to wings if cloudflare proxy on

### ISSUE THREAD

**Issue by DontUseUseServerForServerComponents** [pterodactyl/panel#5082]
### Current Behavior

I'm unable to connect to wings if I have cloudflare proxy on.
I need it on for security and to mask my ip

If its on, I get a error like failed to connect to wings

### Expected Behavior

I should be able to connect to wings

### Steps to Reproduce

Turn on cloudflare proxy and point it to ip of wings and attempt to use it.

For the third checkbox, I haven't checked the discord server because I'm unable to join it, because I got banned when I attempted to ask the issue that I was unable to connect to wings with the official install
![image](https://github.com/pterodactyl/panel/assets/166639513/09c8c734-c337-47f4-9975-f1dc51041f0d)

### Panel Version

1.11

### Wings Version

1.11

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by rowansc1** [comment]
Pterodactyl has features which allow for using cloudflare (and other services) as a proxy. However, the pterodactyl team/discord will not support the use of proxy's due to the complexity of some people's network setup. It can be very difficult to support everyone's proxy without having direct knowledge or access to the system. Therefor, it is outside the scope of support of this project. You're welcome to continue to try and use cloudflare as a proxy.

**Comment by BurntRouter** [comment]
@idkwhoiam-dontask Cloudflare proxy needs wings to run on port 8443, are you doing that?

**Comment by matthewpi** [comment]
https://pterodactyl.io/wings/1.0/configuration.html#enabling-cloudflare-proxy
