### ISSUE TITLE
Daemon not respecting local CA store

### ISSUE THREAD

**Issue by Volxz** [pterodactyl/panel#548]
I have a local certificate authority on my network and the CA cert is installed on the machine just fine (i can curl the panel) but when i try to start the daemon on the same machine this happens:

https://hastebin.com/secoyokina.sql

**Comment by schrej** [comment]
This is due to nodejs not using the system's CAs.
The optimal solution would be to add an option to provide additional CAs, as we are on feature freeze on the daemon this is not going to be implemented though. We'll have to check if the same occurs for golang's HTTP server as well and find a solution for the new daemon.

In the meantime, here are people with the same issue and some workarounds:
https://stackoverflow.com/a/39113115/4430124
https://github.com/nodejs/node/issues/4175

**Comment by MarkL4YG** [comment]
Until this is fixed one can also set the following system var for the daemon: ``NODE_TLS_REJECT_UNAUTHORIZED``.
Just don't use this for actually productive environments as it completely disables certificate verification!

**Comment by DaneEveritt** [comment]
closed in https://github.com/pterodactyl/daemon/commit/3cb74bd49547de4b2f71948704ed0ea2eec67b69
