### ISSUE TITLE
Ability to label ports

### ISSUE THREAD

**Issue by Derkades** [pterodactyl/panel#561]
..so other server managers know what purpose each port serves. (suggested by PR3M1UM_PIX#4326 in Discord)

An example of what this might look like:

![image](https://user-images.githubusercontent.com/15892014/28516992-4e67894a-7063-11e7-98b2-31672862eb7e.png)

**Comment by Polarcraft** [comment]
That is what the Alias is for?

**Comment by Derkades** [comment]
@Polarcraft Alias is an alternate ip/domain to use instead of "IP Adress". In this case it's the only usable ip since "IP Adress" is 0.0.0.0

**Comment by PR3M1UM** [comment]
'Description' instead of 'Tag' would be sufficient aswell, so it can be the same input field as Alias.

**Comment by parkervcp** [comment]
saying `In this case it's the only usable ip since "IP Adress" is 0.0.0.0' is only technically correct. You can technically put anything you want in the alias. If you allocate the IP then it would be a null point and the alias could be anything. In this context setting the alias to the hostname makes sense.

**Comment by LeCodeCo** [comment]
I think "Note" instead of "Description" would better suit the port. I also think when a server is deleted and created, the notes on an allocation should be deleted, so it's fresh for each server.
