### ISSUE TITLE
Uploading folders using File Management converts them to text

### ISSUE THREAD

**Issue by xyeLz** [pterodactyl/panel#599]
I know you can use SFTP for this stuff, but as I've begun hosting more and more servers for people, they continue to want to use the file manager. Since it's built in, it really _should_ support the addition of folders. Presently, if someone clicks and drags a folder into the file manager, it uploads that folder as a text file. None of the contents within are brought over.

**Comment by DaneEveritt** [comment]
At this point it should just toss a warning that you can't upload folders. I do not believe it will ever do that since there would be a significant amount of logic required to pull that off, and it was never designed to replace SFTP for complex actions such as uploading an entire folder and its subfolders.
