### ISSUE TITLE
Use Swagger for API documentation

### ISSUE THREAD

**Issue by schrej** [Pterodactyl/Panel#812]
We should use https://swagger.io/ for our API documentation as it allows to have the docs within PHPDoc in the code. Then you can dynamically or statically create a swagger.json file that can be looked at with the [swagger-ui](https://swagger.io/swagger-ui/).

There is a package for php available: https://github.com/zircote/swagger-php
It allows to have a route that creates an up-to-date swagger.json or just create a static swagger.json file.

We can then host a swagger-ui instance pointing to a hosted swagger.json and people could also enter a link to their swagger.json to see all routes to their api and also test them.

**Comment by DaneEveritt** [comment]
I already gave this an attempt with the new API previously and it was an absolute mess trying to get all of the annotations setup in the correct place, and required annotating the models which is not really possible since they make use of magic methods for many fields.

While it looks nice, it was a pain to write and maintain. I think a more effective use of time would be properly documenting the API from the get-go. If someone wants to make a PR once I have the API written and is willing to go through and all of the swagger-php annotations they can, but I don't plan on adding that right now.
