### ISSUE TITLE
Suggestion: Mounting Files

### ISSUE THREAD

**Issue by sgtaziz** [Pterodactyl/Panel#825]
This is mainly a Daemon suggestion, but I could not create it for some reason in the Daemon repo.

In a lot of my uses, I am required to use the same plugin files and maps across multiple servers. This can cause use a lot of disk space, especially since for example my maps folder is over 200GBs. Here is how I have it setup right now to mount these files:
1. In daemon-data, I made a "packs" folder which includes maps, addons etc. These are the files that will be shared across servers.
2. Inside server.json for each server, I added a "mounts" key under build, which is an object containing local directory as the key and container directory as the value. Here is a screenshot to better explain:
![Example](https://i.imgur.com/sDFjXdz.png)
I am currently adding these values manually, but ideally it would be handled by the web panel.
3. The docker controller under daemon/src/controllers/docker.js must be edited to mount these directories. This can be done by simply adding the values from server.json config into the mounts variable that gets passed to CreateContainer. I've also added these directory under the binds variable, but I am not sure if that's necessary. 

I'm currently doing this in my personal gamepanel and it's working flawlessly. I did have issues in terms of permissions, but I was able to remedy that by making all containers use the same user. Obviously this can be a bad practice for most setups, but it works fine for the purposes I need it for. A better way to do it would be to make containers run under the same group and setting the permissions for the packs folder in favor of that group, but I wasn't exactly sure how to run a container with a group permission or if it's even possible.

I can send out PRs from my personal setup if necessary.

Thanks for hearing me out :)

**Comment by DaneEveritt** [comment]
Thanks for the suggestion, I believe someone else had also requested this, I'll see if I can find that issue. Your permissions issue for number 3 is actually resolved in the beta version of the daemon as we switched all containers to run under the same user. While this might deduct a point in the security column, we believe that the number of other security features we have implemented negate this concern, and it does make permissions management significantly easier for users.

I think Panel wise, this would be easily done on a per-node level, otherwise you would need the exact same mounts across all nodes which isn't how some people run their setups. These mounts could then be passed to each server (with UI elements to make this quick but also very flexible).

UI wise I envision the mounts being configurable as read only versus read/write so that if you have customers sharing a mount point you can control access to it, but also control access at the R/W level per-server.

**Comment by MarkL4YG** [comment]
Would love this. We do have metric-tons of binaries and assets too and could optimize storage space this way.

**Comment by MarkL4YG** [comment]
@DaneEveritt I guess what you mean could be #552 ?

**Comment by DaneEveritt** [comment]
Yeah, good call. I knew there was one somewhere.
