### ISSUE TITLE
Configuration Files adds unnecessary characters

### ISSUE THREAD

**Issue by GwtLabs** [pterodactyl/panel#989]
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 0.5.2
* Server's OS: n/a
* Your Computer's OS & Browser: n/a

------------------------
Configuration Files parser properties adds unnecessary characters. Settings Egg "Configuration Files" in Panel:
```
{
    "config.cfg": {
        "parser": "properties",
        "find": {
            "QueryConnection::FfmpegPath": "/usr/local/bin/ffmpeg"
        }
    }
}
```
Badly formatted line after start (added characters '\'):
```
QueryConnection\:\:FfmpegPath=/usr/local/bin/ffmpeg
```
There are no additional characters for this server in the /srv/daemon/src/services/configs/*.json file.

**Comment by schrej** [comment]
This is actually caused by the properties file parser, see [here](https://github.com/xavi-/node-properties-parser/blob/master/index.js#L248).
The issue here is that properties can either use `=` or `:` to separate key and value, so this is intended behaviour to match the specs of properties files so we will keep it that way. If software isn't using the format properly that's not our fault. You should be able to use the plain file parser to avoid this issue, at least with properties files.
